### ISSUE TITLE
Update donate link on /what-you-can-do

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#10129]
Update the Donate Now button link on https://foundation.mozilla.org/what-you-can-do/ to open the FRU modal instead of linking to our donate site.

<img width="1267" alt="Screenshot 2023-02-09 at 12 15 38 PM" src="https://user-images.githubusercontent.com/1068783/217954808-fb4525f4-5ac7-4ac1-a253-08b665f12dc3.png">

### AC
- [ ] As a visitor, clicking the "Donate Now" button on https://foundation.mozilla.org/what-you-can-do links to https://foundation.mozilla.org/what-you-can-do/?form=donate

**Comment by danielfmiranda** [comment]
Hi @kristinashu, after taking a look at this, it appears that this button's link can be set in the CMS under the "CTA 2" section:

![Screenshot 2023-02-10 at 13-59-49 Wagtail - Editing Participate page2 What you can do](https://user-images.githubusercontent.com/18314510/218207975-d944a3a6-0bd1-4906-ba8c-fa752b0eedfb.png)


I have also updated it to include the relative link "?form=donate". Now instead of being linked to the donate site, it instead renders the FRU modal as requested.

Can you please take a look when you have a free moment and let me know if everything is working as expected? Thanks!

**Comment by kristinashu** [comment]
I should have known that! Thank you Daniel, it's linking properly now!
