### ISSUE TITLE
Opportunity Page - Navigation Position

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1013]
The side navigation looks like it is sitting a bit low beneath the title on opportunity pages like MITI and Fellowship Advisory Board:
![opportunity-nav-bug](https://user-images.githubusercontent.com/2492510/35457516-09c6d38c-028e-11e8-8002-381ba2cacc0c.jpg)

Can this be moved up and be made sticky when users scroll down these pages?

**Comment by taisdesouzalessa** [comment]
For reference, this was the designed behaviour (please disregard the header): https://taisdesouzalessa.github.io/simple-model-ui/ - if I am not mistaken, we focused on an MVP first, so it would be great if we could improve this MVP, as Sabrina mentioned above :)

**Comment by anweshknayak** [comment]
Looks like opportunity app is not been implement in this project. Where to make these changes? @taisdesouzalessa

**Comment by kristinashu** [comment]
@alanmoo can we resurface ticket since [this page](https://foundation.mozilla.org/campaigns/aadhaar/) is getting a lot of attention now?

**Comment by alanmoo** [comment]
Sure! Do we want to go with the header image approach or move the side nav up?

@anweshknayak, the opportunity pages are based on `opportunity.pug` as a template, which gets generated into `landingpage.html` which is used as a django template.

**Comment by kristinashu** [comment]
Yay! Move the side nav up please. So the top to the nav lines up with the top of the title. 

Example: there is a faint blue guideline to show how they should line up

<img width="822" alt="screen shot 2018-02-02 at 11 09 00 am" src="https://user-images.githubusercontent.com/1068783/35750411-bf10c18c-0809-11e8-9b41-ebb245b7156b.png">

**Comment by alanmoo** [comment]
With this approach, the default positioning for the mobile nav is to go above the page heading (assuming we revert to a single piece of markup for both mobile and desktop nav). Would that be preferred, or do you want to keep it as is, where the mobile nav is under the page heading?

**Comment by kristinashu** [comment]
Yes, please move the secondary nav up so it's just below the main nav on mobile.

Production (right) | Comp of how it should be (left)

![screen-shot-2018-02-02-at-11 42 22-am3](https://user-images.githubusercontent.com/1068783/35752101-8cdd5c88-080f-11e8-8d82-3a98a5bb86cd.jpg)

**Comment by alanmoo** [comment]
Great. I think this should be enough detail for someone to take it on. For whoever does take it on:

This seems like it should require only markup changes in 2 files: `opportunity.pug` and `campaign.html`. (It's a bit confusing the way it runs right now, and we do need to clean that up so they're using a similar template. But that's a separate issue)

**Comment by kristinashu** [comment]
Sorry, I spoke with @taisdesouzalessa and she pointed out this bug https://github.com/mozilla/foundation.mozilla.org/issues/977 where the sub menu and title names are wrong.

So once that bug is fixed, the original order (main nav, title, secondary nav) will make more sense. So let's keep the order as is. 

SO only update for this ticket is to move the nav up on desktop view.

**Comment by xmatthewx** [comment]
Before we move ahead, I'd like to consider two things: 
 - how we use CMS title vs header
 - stacking two nav's on mobile

On mobile, I'm a little concerned about moving the nav above the title because it could feel like site nav, rather than section nav. It sits so close to the hamburger.

I think we can up the style a bit and change how we use author's header. Adding margin on sides of sub-nav can help it sit better within the section. And we can tighten vertical margins. 

![image](https://user-images.githubusercontent.com/53411/35827359-b6d15612-0a89-11e8-9fcb-74c251448de0.png)

In the CMS, authors can set a `title` and a `header`

![image](https://user-images.githubusercontent.com/53411/35826689-7250aeea-0a87-11e8-910a-70537dcac646.png)

 - `title` => currently used for URL and sub-nav
 - `header` => currently used at top of page content

We could instead:
 - title => URL, sub-nav, top of the page
 - ~~header~~ subtitle => smaller subtitle at top of the page

**Comment by taisdesouzalessa** [comment]
+1 to tighten vertical margins and add margins to sub-nav - it does look a lot better.

Correct me if I am wrong here, @xmatthewx but your suggestion is to make the info in "A" match the info in "B" (screen 1), right? I ask that because we are currently fixing the menu (for Fellows and I think it will reflect here as well - screen 2) so the selected item (sub-nav) shows on the top. In this way, we couldn't make the info of A to match the info of B in the CMS. 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/22157921/35874834-66b35150-0b22-11e8-8135-2bca0b559b0a.png">

Another concern that was raised when I talked to @kristinashu last week was having the same title for all the pages on the desktop view. I don't think it is a very big issue now that I see in the comp since the section the user currently is appears highlighted on the left. But it could potentially cause some confusion. 

<img width="850" alt="image" src="https://user-images.githubusercontent.com/22157921/35875115-295ee7e6-0b23-11e8-8ad0-74a87dd12cb0.png">


Kristina, feel free to edit this comment or add a new one if I missed something from our discussion.

Matthew, please let me know if I am misinterpreting things.

**Comment by alanmoo** [comment]
I think some items are being conflated and I want to straighten them out. Currently every page has 2 relevant fields: Title and Header

Title:
* Name of page in side nav
* Name of page in browser title bar ("Mozilla Foundation - {Title}")

Header:
* Big text at the top of that specific page

The first page does double-duty because it's the parent page of the group, so its title should be an encompassing term for all the pages below it.

That being said, I'm no longer clear on what the ask of this ticket is. Should we close it in favor of a discussion ticket to solve the broader navigation issues we need to solve for?

**Comment by kristinashu** [comment]
Agree! 

I've opened a design ticket to discuss the header/title/dropdown #1029

And a separate one to move the navigation up on desktop #1028 (this one should be a small ticket that will help make the page look less broken).
