### ISSUE TITLE
Design Page Templates for the CMS

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1021]
### Description
This is a discussion ticket on how templates are designed, created and used in the CMS. 

I have a few questions about the design and build of reusable templates on Mezzanine. I think this is an important system to build out as we expect more requests to include content on the site and it to be a central hub for foundation content moving forward.

**Current Inconsistencies** 
▪ headings on Opportunity pages
▪ spacing for type and images on Opportunity pages
How do we revise these to align with our main pages?

**Templates**
It’s currently pretty tricky to implement any designs on the CMS that has images across various columns. How do we want to approach designing templates with images or content with different column widths? There has been mentions of templates but I didn't find much on the CMS and found the current one limiting.

**Components**
There is a signup widget and was wondering how do we make more pieces into widgets/components? What is the process to submit a new widget to our components list?
________

### Application
This can be applied to opportunity pages coming up such as [Web Literacy](https://github.com/mozilla/foundation.mozilla.org/issues/985) and Global Sprint pages. I want to learn more about how we should approach making the design consistent with our main pages and how they can be maintained so we can keep track of any suggestions, thoughts and ideas here.

cc  @xmatthewx @kristinashu @taisdesouzalessa

**Comment by sabrinang** [comment]
**Note:** Sub Navigation patterns should also be considered in these templates

**Comment by alanmoo** [comment]
@sabrinang can you find a time to get @gvn up to speed with this?

**Comment by kristinashu** [comment]
I echo Sabrina's concerns here. We will be using these CMS pages a lot (example [Aadhaar campaign](https://foundation.mozilla.org/campaigns/aadhaar/aadhaar-challenges-and-the-path-forward/)) so we should really invest in getting them up to the standards we have on the rest of the site.

As Sabrina mentioned, headings definitely need to match the rest of the site. For example, h3 on these CMS pages should be the same as h3 on the main site (i.e. be Zilla rather than Nunito).

The spacing also makes it hard to read and scan content.

[Example: About page is great how there is a larger vertical space above the title than below (helps group the title with the content below)](https://foundation.mozilla.org/about) 

<img width="844" alt="screen shot 2018-02-01 at 10 23 52 am" src="https://user-images.githubusercontent.com/1068783/35695669-172cf53c-073a-11e8-80ef-4a7ed096afda.png">


[Compared with the CMS pages where the spacing is the same and it takes more mental effort to group the content](https://foundation.mozilla.org/campaigns/aadhaar/aadhaar-challenges-and-the-path-forward/)

<img width="844" alt="screen shot 2018-02-01 at 10 24 13 am" src="https://user-images.githubusercontent.com/1068783/35695670-1748f53e-073a-11e8-8dad-71df2759fdf9.png">

**Comment by xmatthewx** [comment]
Thanks all. I'd like to prioritize: 
 - style consistency between cms pages and site pages
 - simple cms-based recipes for style (like tais did on the miti page). authors will break things. authors will learn to not break things. that's cool. we're all about web literacy. 

We need to be conservative and realistic about engineering new templates and capacities for cms. These are a serious investment, and realistically will require more bandwidth than we have available.  We can collect ideas (example two levels in left-hand nav), but these can't be blockers to launching pages for global sprint and web lit.

**Comment by kristinashu** [comment]
I'm going to close this since Pomax will be fixing a lot of it in Wagtail. If there are still issues, then we can open up small tickets.
