### ISSUE TITLE
Do an anchor stylings audit and update style guide if needed

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#1022]
[Style guide](https://foundation.mozilla.org/style-guide/) shows that all anchors on the Foundation site should be in bold (`font-weight: 700`) There has been some discussion about tweaking font weight for certain link type. e.g., secondary nav link so they are semibold (600). I'm hesitant to just add a new style there... Let's discuss and maybe do an anchor stylings audit before we commit to this change.

/cc @taisdesouzalessa @gvn 

---

### Notes for devs:

From https://github.com/mozilla/foundation.mozilla.org/pull/1020#discussion_r164964011

We should probably change all `opp-link` and `opp-link-active` class names to something more general like `multipage-link` and `multipage-link-active`, since these classes aren't only sued on opportunity pages only.

**Comment by taisdesouzalessa** [comment]
Adding @kristinashu to the discussion as well because she has been working on the style consistency across properties.

Context: for the Fellowship site, we have a secondary menu. I used Nunito to follow our rules but the styling was identical to our body copy style, which would make the menu almost blend with the body copy. The solution I got was to make it semibold and that would introduce a new style, as Mavis pointed out. 

<img width="970" alt="image" src="https://user-images.githubusercontent.com/22157921/35655159-45918388-06a5-11e8-80ca-bb8b815256a5.png">

**Comment by kristinashu** [comment]
I am always reluctant to add new styles but nav is so important that I think it's ok for it to be an exception. 

@taisdesouzalessa would font styling for this horizontal secondary nav also work for the vertical secondary nav? Or would the font size might be too small? As we talked about yesterday, we should at least update it to Nunito.

Example for horizontal nav on production:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/1068783/35694358-ee9216d8-0735-11e8-93f1-ec9cc8b2b249.png">

**Comment by taisdesouzalessa** [comment]
@kristinashu thanks for your input here. I think we can use the same styling but if we could use the size 18px for the side menu, it would be better.  Also, we will need to increase the line height because currently, the yellow highlight looks a bit odd if we only change the font:

Screenshot with Nunito Sans semibold, 16px
<img width="825" alt="image" src="https://user-images.githubusercontent.com/22157921/35712730-6efad552-0778-11e8-82c6-4a80e6c676d3.png">


Screenshot with Nunito Sans semibold, 18px and line height is 1.8):
<img width="750" alt="image" src="https://user-images.githubusercontent.com/22157921/35712691-2785e2e8-0778-11e8-943f-9d1eed9b912d.png">

Any thoughts?

**Comment by kristinashu** [comment]
Yes, your second comp looks good! 

Cross-linking this ticket with the navigation position bug https://github.com/mozilla/foundation.mozilla.org/issues/1013 since they are slightly related.

**Comment by kristinashu** [comment]
I totally forget about this ticket but opened a new one yesterday https://github.com/mozilla/foundation.mozilla.org/issues/1465

@taisdesouzalessa @mmmavis does that ticket cover this one?

**Comment by taisdesouzalessa** [comment]
@kristinashu that one covers it, except for one part: the line height has to be increased (to 1.8). would you mind adding to that ticket?

**Comment by kristinashu** [comment]
Ok updated!
