### ISSUE TITLE
Opportunity page - design header titles and dropdown on mobile

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1029]
Based on conversations from here down https://github.com/mozilla/foundation.mozilla.org/issues/1013#issuecomment-363213176

**Comment by kristinashu** [comment]
@taisdesouzalessa @xmatthewx based on what you have both said and designed, would something like this work?
 
![untitled-1](https://user-images.githubusercontent.com/1068783/35882527-5d63beb6-0b39-11e8-87ef-3ae475947d84.jpg)

![global sprint home copy 4](https://user-images.githubusercontent.com/1068783/35882902-719d678c-0b3a-11e8-8d53-3c4e8607fa31.jpg)

**Comment by xmatthewx** [comment]
@kristinashu - we don't currently display the parent page title at the top of child pages. While it would be nice to label the mini-site like that, it'll probably require a chunk of engineering. I'd like to solve the easier problem first and quickly, and then follow up on that. I worry it will confuse what would otherwise be a quick fix and a big improvement. 

Your comps look great. 

Here's what I suggest in terms of mapping the fields:
 - html title = title (as built)
 - nav item label = title (as built)
 - page content h1 = title (current header)
 - page content h4(??) = header (in comp. currently doesn't exist)

**Comment by kristinashu** [comment]
Okay I've taken another stab at this! Let me know if this makes sense https://redpen.io/p/myec85141a1f7a03a5 I'm aiming for blue sky, best case scenario. If we all think would make for better user experience, then I will talk to Alan to see what is actually possible!

**Comment by taisdesouzalessa** [comment]
I think it solves the problem :). I like the hierarchy you created there, I think it works very well for the user experience. If we implement that, we may add the instructions to our [Network Site User Guide](https://docs.google.com/document/d/1WGWhfUY2mrQQGm-idP137S4CWdcdizL-UXI6DI_2QeU/edit?usp=sharing) so it is clear to editors.

**Comment by xmatthewx** [comment]
This looks good. And I like how you've put cms fields above the designers. Very helpful. 

I added a comment about the use of Title on subpages in redpen. They're critical for browser nav and history (html title). I also think they're better for sidebar nav since they tend to be shorter and less wordy.

**Comment by kristinashu** [comment]
Talked with Alan and he thinks he has found a way to do this! He's still working on the language but ticket for implementation is here https://github.com/mozilla/foundation.mozilla.org/issues/1047
