### ISSUE TITLE
[QA Fellowship mini-site] Paragraph: margin-bottom

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1094]
Issue:
This issue is a nice to have, not a must-have. 

In all pages in which we have a paragraph followed by the gradient bar, there is an extra space on the bottom of the paragraph that makes the spacing between those 2 elements too big and inconsistent with other spacings (yellow- highlight). That happens because the <p> has a margin-bottom of 1rem by default.

Could we make the margin-bottom for those cases = 0? 

<img width="326" alt="image" src="https://user-images.githubusercontent.com/22157921/36622732-f843390c-18b3-11e8-9730-8324912c5059.png">

This issue happens in the following pages: [main](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/), [Science](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/science/), [Open Web](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/open-web/), [Tech Policy](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/tech-policy/) and [Media](https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/media/)

**Comment by mmmavis** [comment]
I'm leaning towards keeping the bottom margin there so all `<p>` have the same stylings across our site. We _could_ remove bottom margin for specific paragraph `<p>` but that'll lead us writing a ton of custom CSS(or applying special `class`) for every special case of `<p>` on the site, which is not ideal.

**Comment by mmmavis** [comment]
If we are talking about "the paragraph followed by the gradient bar" *only*, I can take a look and see what I can do there. 😉

**Comment by taisdesouzalessa** [comment]
Oh yeah! I meant followed by a gradient bar only :)  The others are fine, we need that space. Tksss!!

**Comment by mmmavis** [comment]
@taisdesouzalessa I did a quick check. Short answer is "let's leave it as is". 

Because of the section layout we have on these pages, there isn't a clean way to do this that would work for both CMS-based and non-CMS based pages. I _could_ just manually add `mb-0` `class` to every last paragraph before a `<hr>` but 1) this requires manual work 2) we'll have to do this again for every future page that share the same layout 3) this approach won't work if the content is managed by CMS (unless you edit HTML directly in CMS, which is a bad idea anyway)

**Comment by taisdesouzalessa** [comment]
Cool, Thanks for the context here, Mavis!
I guess we can address this issue in the future as a more systemic way as we polish the components :). Closing the issue.
