### ISSUE TITLE
Add placeholder image for fellows without a profile image

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1106]
While all fellows should have an image, this is a useful fallback to have so things don't break if there isn't one or something goes wrong. @taisdesouzalessa do we have an image we can use?

**Comment by kristinashu** [comment]
There is a ticket open to design Pulse avatars https://github.com/mozilla/network-pulse/issues/881

Grey circle should be fine for now though, fallback avatar design shouldn't be a blocker.

**Comment by taisdesouzalessa** [comment]
@kristinashu thanks for the context here :).  Do you know when the Pulse avatar placeholder is scheduled to happen? It is because I wanted to use the same placeholder in the Fellowship Directory as well. If it won't happen soon, I would rather create a quick placeholder for the Fellowship site for now and then, once we have Pulse ready, we can use that one.

Since profiles will show up side by side, I would prefer to have some placeholders there instead of leaving them solid grey. I would like to give Fellows equal opportunity of grabbing attention on this page, either they post pictures or not.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/22157921/36704410-1910355a-1b15-11e8-8d0f-c08fc4cf5c08.png">

**Comment by kristinashu** [comment]
Could what you design for Fellows also work for Pulse, or is there a reason to make them different?

If you are up for designing one please do so!

**Comment by taisdesouzalessa** [comment]
No reason to make them different, in my opinion. Since I am not the designer for Pulse, I didn't want to interfere with that...haha. I was focused on the Fellowship site, which is my current are of attention. Let's do just one then, as you suggested, it makes more sense. @alanmoo when do you need this task done? I may be able to work on it on Friday (March 2nd). Does that work?

**Comment by alanmoo** [comment]
That's fine; @mmmavis let's put in a grey box for now though so it takes up space.

**Comment by mmmavis** [comment]
Done! Fix has been merged into the main fellowships work branch `fellowships`  https://foundation-mofostaging--pr-996.herokuapp.com/fellowships/directory/
