### ISSUE TITLE
[Fellowship Mini Site] Interim Directory

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1185]
We will soon have a fully functional directory, with proper filtering. For now, we have an interim solution. 

**Problem**: this interim build over emphasizes the legacy split between fellowship programs. It will invite many new eyes and orient them around an old model rather than the future model.

**Solution**: instead of relying on wordsmithing the interim solution further, we propose that we simplify and remove focus area sections and links as detailed below. 

**Goal**: Ship the interim solution soon. After, proceed to build proper filtering. 

## sign-off

Let's discuss, clarify, refine. Let's not proceed without signoff by: 
 - [x] @rtufail
 - [x] @community-impact
 - [x] @taisdesouzalessa
 - [x] @mmmavis 

cc @jessevondoom @annmarie123 @KevZawacki @alanmoo  

## the details

 - [ ] Revise `/directory`. 
   - [ ] Remove subsections
   - [ ] Remove focus area links at the top
   - [ ] ~Display all fellows in one group. Sort alphabetically `[First Name] [Last Name]` if possible, by profile ID if not possible.~
   - [ ] Display all active fellows in one group. Sort alphabetically `[First Name] [Last Name]`. "Active" is determined as any fellow with "year" set to the current year or later. (This may change later but is how we can structure the data for now) _(Added by Alan 3/15)_
   - [ ] Include a single `See Fellows from Previous Years` button

----
 - [ ] Add `/directory/archive`
   - [ ] remove `/directory/media` and other subpages
   - [ ] add `/directory/archive`
   - [ ] title of the page: `Fellows from Previous Years`
   - [ ] Breadcrumb `Directory > Fellows from Previous Years`
   - [ ] list all fellows in a single view grouped by year (no focus area sections) 
   - [ ] sort each year section alphabetically `[First Name] [Last Name]` if possible, by profile ID if not

----
 - [ ] Review profile card
   -  [ ] (if not difficult) Change label at the top. Reduced to `Fellow 2017`. Move focus area (program_type) to the list of issues below. For example: `Science, Open Innovation`.
   - [ ] For Fellows `In Residence` add the word `Fellow`. For example: `Fellow in Residence, Web Literacy, Digital Inclusion`

**Comment by RizwanTufail** [comment]
Makes sense. Thanks!

**Comment by mmmavis** [comment]
Thanks for the clarification! @xmatthewx 

One question regarding the fellows we show on `/directory`... are we showing 2017 fellows or 2018 fellows?

**Comment by xmatthewx** [comment]
Great question. Long term, we'll want to show `active` fellows. We don't have the concept of active built in yet. So for now, I'd guess that pulling both is probably best.

**Comment by alanmoo** [comment]
Alphabetically by first name?

**Comment by rtufail** [comment]
last name, I would suggest

**Comment by taisdesouzalessa** [comment]
As discussed in the meeting (March 13th):
- we are sorting by first name, last name (alphabetically) - reason: make scannability easier since we don't have a filter for now. 
IMPORTANT: if this is a blocker, Rizwan told it is okay to not organize alphabetically. I (Taís) would recommend that we do it if possible because we don't have filters and it would be easier on users. However, I share Rizwan's opinion if this is a complicated thing to do.
- Changing "Past Fellows" label and using "Fellows from Previous Years" instead
- For Fellows "In Residence" we are using the full label "Fellows in Residence" (it looks better, now that it is shown beside the Internet health issues). Example:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/22157921/37367174-e9071bba-26bf-11e8-91ca-cb9596a06b4f.png">

What we need from @community-impact, @rtufail and team:
- which Fellows will be displayed in (1) "Main Directory Page" and which Fellows from 2017 will be displayed in (2) "Fellows from Previous Years"
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/22157921/37367565-fba580e4-26c0-11e8-80b9-d46249ba4f6c.png">
 
- Blurb of copy for the "Main Directory Page" - goal: give users the context that those are current fellows (2017-2018)
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/22157921/37367656-4aa63cec-26c1-11e8-9a7c-aa8ca2e4a444.png">

Please feel free to add/edit this entry if I forgot anything :). Thanks!

**Comment by community-impact** [comment]
Thank you. The fellows that should be moved to "previous years" are:

Camille
Terah
Phillip
Kaitlin
Matt

**Comment by taisdesouzalessa** [comment]
Here are the comps:
[Directory](https://invis.io/ZJ9YTAGEA#/276734820_v2-FellowshipsUI_-_Fellows_Directory)
[Directory > Fellows from Previous Years](https://invis.io/ZJ9YTAGEA#/276734822_v2-FellowshipsUI_-_Fellows_Directory_Specific_Program_Page)

@xmatthewx @rtufail @community-impact please let me know if those are good to go. If you need revisions, please add here and I'll work on them.

Next step: after approval, create an implementation ticket to @mmmavis

**Comment by community-impact** [comment]
Yes, this looks good to go

**Comment by alanmoo** [comment]
I updated a single item in the requirements list based on the conversation in #1189. If that needs any more changes, we're going to have to discuss it in a separate ticket.

**Comment by taisdesouzalessa** [comment]
Task completed. Closing this issue. Feel free to reopen it if you disagree.
