### ISSUE TITLE
Identify active fellows in directory

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1189]
In a call earlier today the topic of identifying the years of a fellow came up. Given that we already have a field in our database for "year", should we simply create another entry called "Current" (or "Active", or whatever someone feels strongly about) so that we have an easy way that's already built out in code to identify active fellows? Then when they're no longer active, that can be changed to a specific year value. If we had an "active" boolean, we'd have to go in and make a change at the end anyway, so this avoids adding extra fields to the model.

@taisdesouzalessa will post a quick comp to clarify the visual result of this possible change.

To close this ticket, we need a decision, probably from @rtufail.  Yes/what label or no.
cc @community-impact @mmmavis @xmatthewx.

**Comment by taisdesouzalessa** [comment]
Here are screenshots of the comps. I personally prefer "current" because I think it is clearer than "active". However, I feel we could come up with an even better and clearer label :). Please post any suggestions here!

With "Current":
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/22157921/37369754-42b15962-26c7-11e8-8db3-521d2291ba8d.png">

With "Active":
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/22157921/37369773-50e315a2-26c7-11e8-847c-fa5d2bda2bf6.png">

**Comment by rtufail** [comment]
Hmmm. I prefer to see Fellow (2017-2018), or Fellow 2017 in front of a person's name, rather than Fellow Current or Fellow Active. 

I think this is still a good idea if we can think of active or current as a flag in our system that is not visible to the site visitor.

**Comment by alanmoo** [comment]
Adding that flag needs a more involved engineering solution to be thought out so we're going to have to accept that all fellows from a certain year/years show up as active for now.

**Comment by rtufail** [comment]
OK. So to reconfirm we will stick with the Fellows 2017 convention. Correct?

**Comment by xmatthewx** [comment]
Question: are there any 2018 fellows today who were _not_ active in 2017? If not... 

 - **Interim solution**: we could use 2017-2018 for all fellows we want on the `/directory` view. We could use 2017 for any who started but are not still active in the `/directory/archive` view.
 - **Long term solution**: we add an active/inactive flag in backend and enable a list of years as year/number rather than as a string for maximum accuracy and flexibility.

**Comment by rtufail** [comment]
Unfortunately, yes. We have 1 Fellow-in-Residence (Renee DiResta) who started mid-Jan, and 4 other fellows who’re starting on Apr 1 (including Peter, Thomas, Julia, Meghan)

**Comment by xmatthewx** [comment]
I think we need to move away from the idea of active / inactive. I think that matters internally, but doesn't mean much to an external audience. Once a fellow, always a fellow. I can't think of an audience group and use case where this matters:

 - As a prospective fellow, I want to see awesome people from recent years, so that I know whether to apply.
 - As a prospective supporter... [same as above]
 - As a current funder, I want a report on fellows in the format I've requested, so that I can fill my own records and reports. 
 - As a news reporter, I want to find fellows with certain expertise regardless of their tenure, so that I can talk to a qualified person for my story. 

I think we should use a fellow's end date to define their year, much like a college grad is a member of class of 2052 regardless of the tenure, time off, and month of graduation.

**Comment by taisdesouzalessa** [comment]
I agree with Matthew's approach here. To me, it makes more sense, considering the users' lenses.

**Comment by alanmoo** [comment]
Yes, and it works with the code we have in place already.

**Comment by annmarie123** [comment]
All current fellows profiles have been changed to the year 2018
