### ISSUE TITLE
Upcoming page - needs update

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1210]
### Issue
Our current [Upcoming page](https://foundation.mozilla.org/programs/upcoming/) has only 2017 events. This page currently doesn't have a ton of traffic (524 page views since Jan 2018) but it would be good to update it with 2018 events so the audience knows what to look forward to during this year.

Some ideas: we have the Global Sprint coming up, the applications for Fellowships are open, the Internet Health Report will be launching.

@xmatthewx - assigning you here for triage. I can help with this issue too, I was wondering who could help us to come up with a list of 2018 things and I could update the events in Mezzanine if necessary...or we can ask staff to do so.

**Comment by xmatthewx** [comment]
I see two options (but I leave this to @jessevondoom and @Sydette to decide.)
 - remove this page from the site now
 - update the page since we need to gather content for the future participate page

I think we should remove it. It adds little value. The goal was to give a snapshot of the upcoming year, but I don't think we have enough known-things to justify the page.

**Comment by kristinashu** [comment]
This has been updated.
