### ISSUE TITLE
Update Fellowship feature on homepage

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1211]
Now that we have launched the new fellowship pages, we might want to refresh the language used on the homepage feature that links there. 

@community-impact - how does the current copy read to you? Does it need an update? Note the photo below is for a different feature, not fellowships. 

cc @kristinashu @taisdesouzalessa

![image](https://user-images.githubusercontent.com/53411/37120772-5346d0ce-2229-11e8-8778-b2053f3d2b6d.png)

**Comment by community-impact** [comment]
Since we're not doing the media focus next year, I think we should take
that out, and to be more consistent with the fellowship home, how about we
use something like:
Mozilla Fellowships provide resources, tools, community and amplification
to those building a more ​humane​ ​digital​ ​world. Mozilla Fellowships are
a transformative experience for emerging leaders concerned with making the
internet a safer, more accessible resource for everyone.

**Comment by kristinashu** [comment]
@community-impact do you want to keep the same title (Fellowships that Empower Leaders) and link text (Be a fellow)?

The updated body copy would look like this:

<img width="1133" alt="screen shot 2018-03-22 at 2 49 10 pm" src="https://user-images.githubusercontent.com/1068783/37800497-34c34a52-2de0-11e8-9ba0-e01db14f2d01.png">

**Comment by community-impact** [comment]
I think the heading still works.

For the link, how about "Learn more and apply" (?)

**Comment by kristinashu** [comment]
Perfect! Copy has been updated https://foundation.mozilla.org/
