### ISSUE TITLE
[Fellowship Mini Site] Make deadline for Application significantly more prominent

### ISSUE THREAD

**Issue by annmarie123** [mozilla/foundation.mozilla.org#1228]
In order to better promote the fellows application can we:

- have the banner from the bottom of the main page also put on the top of the "Apply to be a Fellows" page? - Or just have the Apply button + deadline at the top of the page if easier.
- Make the deadline more prominent instead of small grayscale type at the bottom of the page of the apply page.
-Make a note that we are accepting applications for Mozilla Fellows currently more prominent on the front page (mentioning it + linking to it in the copy) - I can work on the copy for that and provide specifics of where to add it in comments below.

**Comment by taisdesouzalessa** [comment]
Hey team!
I applied the feedback on the site, together with other issue we discussed: the addition of links that will link to a FAQ page that will be built in the CMS by the Fellowship team. I have 2 options:

### Option 1
I would recommend we keep only 1 button on the "Apply to be a Fellow" page. The initial reason we built this intermediate page (instead of taxing users straight to Fluxx) was to give some context to them before jumping to a Fluxx form. I feel that, in terms of storytelling that context is important.

I did a diagram that shows that if an user is in a hurry to apply (illustrated in pink in the flow), it is not too much work for them to scroll and find the yellow button on the page. 
By keeping the storytelling as is we also cater for users that need more context and convincing (illustrated in blue in the flow)
![user-journey-feelowhips-apply](https://user-images.githubusercontent.com/22157921/38062155-44c0062c-32a7-11e8-913f-b7e84dc22f45.jpg)

Here are the mockups for this option:
I highlight the changes I made so you can easily see what's different:
[Home Page (highlighted with the changes - red dotted box)](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/288066697_DEADLINE_FAQ-V3-FellowshipsUI_-_Overview)
[Apply to Be a Fellow Page (highlighted with the changes - red dotted box)
](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/288066698_DEADLINE_FAQ-V3-FellowshipsUI_-_Apply-Applications)

This is how the pages should look like (no highlights):
[Home Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/288066699_DEADLINE_FAQ-V3-FellowshipsUI_-_Without_Highlight_-_Overview_Copy)
[Apply to Be a Fellow Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/288066700_DEADLINE_FAQ-V3-FellowshipsUI_-_Without_Highlight_-_Apply-Applications__Copy)

**This is totally open for debate as you may have different opinions than me (that's why I also have an option 2 here).**

### Option 2
If you really feel strong about having a double "Apply" CTA on the "Apply to Be a Fellow" Page, here is the comp:
[Apply to Be a Fellow Page](https://mozilla.invisionapp.com/share/BAGJFYP3CN5#/288083292_DEADLINE_FAQ-V3-FellowshipsUI_-_Without_Highlight_-_Apply-Applications__Copy_2)

@xmatthewx @annmarie123 please let us know your thoughts about those before we proceed with implementation.

**Comment by xmatthewx** [comment]
If I'm reading this all correctly, we have the changes to implement. I mixed in a few opinions of my own. 

## 1) update fellowship overview page
 
 - [ ] add new date+button. (I love the style) 
 - [ ] place this higher on the page
      - Tais suggests it goes below 4 paragraphs with icons.
      - I suggest we place the call out much higher, after the 2nd paragraph. People need to know the deadline is soon. The page is a mountain of text. So, above "More than ever, we need a movement..."
      - @annmarie123 can make this decision and inform @mmmavis  <img width="500" alt="image" src="https://user-images.githubusercontent.com/53411/38103516-81a992e4-3354-11e8-86fa-817038cf9ddb.png">

## 2) update the apply page
 
 - [ ] update style on due date next to button at bottom <img width="400" alt="image" src="https://user-images.githubusercontent.com/53411/38104002-f2da5d9e-3355-11e8-9f56-208f30e32ae1.png">
 - [ ] after the first paragraph, add a new element with date. it should look exactly like component on the homepage. But don't include the button. <img width="400" alt="image" src="https://user-images.githubusercontent.com/53411/38104134-494f19ee-3356-11e8-8c89-463f22fff230.png">

**Comment by taisdesouzalessa** [comment]
I think we didn't assign this ticket to an engineer to implement. Maybe Mavis can take care of it? What do you think @alanmoo and @xmatthewx? Should I create an implementation ticket?

**Comment by alanmoo** [comment]
Yeah. I believe Mavis is back tomorrow, so she can take care of it.

**Comment by mmmavis** [comment]
Cool! I can work on this once we have decided what final design option we wanna go with.

**Comment by taisdesouzalessa** [comment]
@mmmavis I think we are following Matthew's list there. I can open an implementation ticket, doe sthat work?

**Comment by taisdesouzalessa** [comment]
Implementation ticket here:  #1396. Closing this one.
