### ISSUE TITLE
Wagtail QA: Secondary Nav

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1327]
From @kristinashu  in #1325: 

### Secondary nav
Currently https://foundation.mozilla.org/wagtail/about/
- space between banner and secondary nav items is too large
- add gradient divider bar
<img width="1091" alt="screen shot 2018-04-12 at 12 24 53 pm" src="https://user-images.githubusercontent.com/1068783/38699394-bbca2d96-3e4c-11e8-94aa-83cf5ae58ba6.png">

It should at least look like https://foundation.mozilla.org/fellowships/

<img width="1091" alt="screen shot 2018-04-12 at 12 25 36 pm" src="https://user-images.githubusercontent.com/1068783/38699385-b52ccbe2-3e4c-11e8-8a4d-10621fe22397.png">

Bonus if it looks like this (black underline like main nav, instead of yellow bar)

<img width="1128" alt="screen shot 2018-04-12 at 12 28 10 pm" src="https://user-images.githubusercontent.com/1068783/38699482-01b5867a-3e4d-11e8-8a6e-6f4e5560bf17.png">

**Comment by Pomax** [comment]
We can't put the `hr` quite where the current site wants it, because that would require putting it inside the cms-managed content section of the page, which we unfortunately have zero control over (it's fully wagtail-managed).

I've written a PR that puts it as close to the cms-content as possible, hopefully that's in line with the design enough?

![image](https://user-images.githubusercontent.com/177243/38705178-8f84a6e2-3e5d-11e8-9f09-580efa1afa9c.png)

The nav `<a>` text feels a little too big though, should we address that in a separate issue?

**Comment by kristinashu** [comment]
Awesome! Yeah subnav text could be 1px font size small than the main nav but that can be done separately and later.
