### ISSUE TITLE
[QA Wagtail] Icon and text padding

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1341]
Layout of icons for the new Internet Health primary page (in Draft mode) doesn't look right. When an icon is set to 100x100px then the text should move over to the left so it is closer to the icon.

Preview looks like:
<img width="1193" alt="screen shot 2018-04-13 at 10 59 12 am" src="https://user-images.githubusercontent.com/1068783/38750438-c9465d88-3f09-11e8-80b6-32b70f7f6510.png">

Should look more like:
<img width="1194" alt="screen shot 2018-04-13 at 10 59 19 am" src="https://user-images.githubusercontent.com/1068783/38750441-caf30438-3f09-11e8-9fa1-94c88b9225dd.png">

**Comment by kristinashu** [comment]
@Pomax when I select 100x100 there is too much of a gap between the icon and the text and if I select 200x200 then the text overlaps (at narrower browser widths). 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1068783/38899496-e555b5f0-424c-11e8-9948-e207b3bc0d4d.png">

There should be a consistent gap between the icon and the text. A 200x200 icon at large browser width looks good.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1068783/38899601-37b87652-424d-11e8-97b3-324b54da88d9.png">

**Comment by kristinashu** [comment]
Follow up, selecting "Use original dimensions" seems to fix these web lit icons. But we should still figure out padding for "Constrain to Xpx x Xpx" cases.

**Comment by Pomax** [comment]
The reason this happens is because of how we "quickly implemented a column layout" for the image+text block, which simply sets fixed columns rather than a layout that respects content and dynamically sizes accordingly.

@gvn would you have suggestions around how we can bootstrap this better? We're currently using the following markup + css: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/image_text_block.html

**Comment by gvn** [comment]
We should try to use percentage widths for images (usually 100% so they fit their containing column exactly) and not fixed pixel values.

**Comment by kristinashu** [comment]
Closing this ticket and will open new ones once #1438 is done.
