### ISSUE TITLE
Redirects on About Us subpages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1372]
Based on Jesse's [endpoints doc](https://docs.google.com/document/d/1zhOwOET0yH3xQC83tcKmlwGT9s2lLv05wdUqRJsm5MI/edit?usp=sharing), subnav menu items that we don't have copy for yet should redirect. 

#### Redirects should be:
- /about/impact (https://advocacy.mozilla.org/)
- /about/strategy (https://mzl.la/foundation-strategy)
- /about/careers (https://careers.mozilla.org/)

#### Note that order in nav should be:
- /about
- /about/impact
- /about/leadership
- /about/trademarks
- /about/public-records
- /about/strategy
- /about/support
- /about/careers

cc @alanmoo for triage

**Comment by kristinashu** [comment]
Maybe related to other redirect tickets: https://github.com/mozilla/foundation.mozilla.org/issues/937 https://github.com/mozilla/foundation.mozilla.org/issues/1216

**Comment by kristinashu** [comment]
@alanmoo is this possible now?

**Comment by alanmoo** [comment]
Not without some code still- Wagtail redirects do work, but if the page exists (a 200 http response), the redirect won't happen. So we need a way for the pages to be added to the menu, but for the redirect to still happen and I have a feeling that may need to happen with some hard coding embedded into our URLs.py file.

**Comment by alanmoo** [comment]
To be clear, here's what I tried: 
1. Create new child pages under`About` called `impact`, etc. and make sure "show page in navigation" box is checked. 
2. Add a wagtail redirect for those routes
3. Observe that as long as the page exists (even in draft mode), the redirect doesn't work. But if the page doesn't exist, we can't get it to show up in the nav without hacking something in.

**Comment by kristinashu** [comment]
I don't quite get it but don't have permissions anyways so can you add these links and redirects?

**Comment by alanmoo** [comment]
Talked to @Pomax now that he's back, this is his first priority.

Summary of approach for posterity: We're probably going to need to do this kind of thing again in the future, so let's not hard code anything in. Secondly, let's not fight Wagtail. The most likely solution involves creating some type of pages for the desired links so they show up in the navigation, but adjusting something (be it a new "redirect" template or Wagtail's routing) so that those pages can redirect as needed. Pomax is going to ask the Wagtail folks what they'd suggest and formulate a plan.

**Comment by Pomax** [comment]
As per the abovementioned issue, the notion of a redirecting page is fine, but rather than a meta refresh, the server itself can be made to force the redirect by overriding the `def serve(self, request)` function, and making it return a django HTTPResponeRedirect object.

**Comment by Pomax** [comment]
Is there a way for us to host the content that is on https://drive.google.com/file/d/1Bl-h9d1IrhBXOskacm8eYkPteNMdxlN2/view right now as a real page? There is something kind of questionable in sending people to a google doc when they're on a mozilla website property, looking for core Mozilla information. At the very least, can we host this PDF file and just link directly to that instead of routing it through track-tastic google services?

**Comment by kristinashu** [comment]
Linking to a PDF in drive is definitely not ideal. This is from the main site https://www.mozilla.org/en-US/foundation/ They link to the shortened URL https://mzl.la/foundation-strategy which then goes to drive. My only concern with hosting it somewhere else is if that strategy PDF gets updated, then we won't know.

**Comment by kristinashu** [comment]
Ordering is certainly something we will need in the future as we add sub-pages to Participate and Initiatives. But I'm ok with alphabetical on the About pages, for now.

**Comment by Pomax** [comment]
It turns out there is a page ordering system already built into wagtail! So that solves that problem.

![image](https://user-images.githubusercontent.com/177243/40088691-eab6dd78-585c-11e8-9537-f4e68b753077.png)

**Comment by kristinashu** [comment]
Yay Wagtail!

**Comment by Pomax** [comment]
PR filed. We should probably document that orderability in the "how to wagtail" pages.
