### ISSUE TITLE
[QA Opportunity Pages] video player size

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1376]
Videos loose aspect radio at narrower widths. Video plays properly but there is extra black space above and bellow it. It sizes well in Mezzanine but not in Wagtail. 

### Wagtail:
https://foundation.mozilla.org/wagtail/opportunity/leadership-training/
<img width="1023" alt="screen shot 2018-04-17 at 9 25 06 am" src="https://user-images.githubusercontent.com/1068783/38883340-76430968-4221-11e8-911d-f422448aee9f.png">
<img width="453" alt="screen shot 2018-04-17 at 9 25 23 am" src="https://user-images.githubusercontent.com/1068783/38883341-7656cb6a-4221-11e8-933c-62debbf114f5.png">

### Mezzanine: 
https://foundation.mozilla.org/opportunity/training/
<img width="341" alt="screen shot 2018-04-17 at 9 26 01 am" src="https://user-images.githubusercontent.com/1068783/38883342-766b2862-4221-11e8-9e17-118f4078bee9.png">

**Comment by Pomax** [comment]
I suspect this is because of the youtube embed currently having a fixed height.  We could try to rewrite that to use the CSS aspect ratio trick (https://stackoverflow.com/questions/1495407/maintain-the-aspect-ratio-of-a-div-with-css and others) but that might have issues with the iframe tag itself needing explicit width/height values (if not, it defaults to 100% width, 200px heigh if I recall correctly).

pinging @gvn to see if he might have good ideas here.

**Comment by mmmavis** [comment]
Bootstrap has some helper classes we can use: https://getbootstrap.com/docs/4.0/utilities/embed/

**Comment by kristinashu** [comment]
Looks great on staging! I think we can close.
