### ISSUE TITLE
Optimize About page styles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1384]
A few things jump out to me on the About page (desktop) with room for improvement. 

 - Subnav size seems very large, larger than primary nav. Proposed: 1rem seems more appropriate. 
 - Alignment of body column feels awkward. Centered against a left aligned header. Proposed: Align to the left (maintain optimal width for readability. don't change based on mock up below.) Consider: a right aligned pull quote to break the grid.
 - Logo and nav stack awkwardly on narrow screens. Proposed: Logo and donate button should remain vertically aligned. Nav should fall below with a bit of margin between it and the logo. [to be filed as a separate ticket]

I leave it to @kristinashu to triage and make final decisions. Or, delete this ticket if it irrelevant or stuff is tracked elsewhere.

## Current implememtation

![image](https://user-images.githubusercontent.com/53411/38887483-f8a353f2-4246-11e8-894c-fceb1298894e.png)

## Alignment test

`this is a test, a demo. it is not pixel perfect for implememtation. `

![image](https://user-images.githubusercontent.com/53411/38888343-50c22a16-4249-11e8-9ccd-48f25b85435f.png)

**Comment by kristinashu** [comment]
- agree, ticket is already open for the sub nav https://github.com/mozilla/foundation.mozilla.org/issues/1354
 - designers discussed the grid earlier and decided to run with this grid https://github.com/mozilla/foundation.mozilla.org/issues/1192
 - agree, nav is awkward at medium widths - I will QA this with Scott since he is revamping the nav right now!
