### ISSUE TITLE
[QA Wagtail Pages] Add image caption type style

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1395]
Wagtail using body copy styling for it's image captions which makes it hard to differentiate what is paragraph text and what is a caption:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1068783/38895384-c73b22ce-4244-11e8-8851-91ae56c4c3d2.png">

Please style captions the way the are on Mezanine (using the class .h6-gray):

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1068783/38895272-71aa3a52-4244-11e8-9757-2619cf6189ba.png">

**Comment by Pomax** [comment]
Looking at that page link, it turns out that the `h6-gray` class doesn't actually exist, there's no rule for that that's kicked in, although the rule for `h6, .h6-heading, .breadcrumb-item.active` has. As this is a figcaption, not an h6, we should probably add a new rule for `.cms figcaption` (or add a `figcaption-gray` class?)

**Comment by gvn** [comment]
`h6-gray` is deprecated I believe.

**Comment by kristinashu** [comment]
`h6-gray` is no called `.h6-heading`

**Comment by kristinashu** [comment]
Closing this ticket and will open new ones once #1438 is done.
