### ISSUE TITLE
[QA Wagtail] Add Heading styles to Image + Text component

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1402]
In Mezzanine we can have an Icon next to a Heading: https://foundation.mozilla.org/opportunity/miti/

<img width="914" alt="screen shot 2018-04-17 at 3 29 02 pm" src="https://user-images.githubusercontent.com/1068783/38902169-4058bf22-4254-11e8-9792-2fa866d37858.png">

In Wagtail, we can only have an Icon next to Paragraph body text. This doesn't work when we need the text to stand out more.

<img width="1125" alt="screen shot 2018-04-17 at 3 28 46 pm" src="https://user-images.githubusercontent.com/1068783/38902167-3da27444-4254-11e8-9ae3-2d8b1ce0f9d9.png">

**Comment by taisdesouzalessa** [comment]
I was wondering if we could add the text styles as we have in paragraph so this component is more flexible?
<img width="517" alt="image" src="https://user-images.githubusercontent.com/22157921/38904057-f6511380-425c-11e8-83be-b37d26a43108.png">

**Comment by Pomax** [comment]
We cannot add anything to the rich text editor around styling: the rich text editor is for "plain text" rather than data, so a heading will always be styled the exact same, a paragraph will always be styled the exact same, etc.

Now that we're constrained more by Wagtail in terms of what we can style, we probably need to pay more attention to how wagtail segments content/data/etc as described in their [zen of wagtail](http://docs.wagtail.io/en/v2.0/getting_started/the_zen_of_wagtail.html), if there is data that needs different styling, then as far as wagtail goes that's probably "a different kind of data", and should use its own component/snippet/etc to capture what it is.

With that said, can we determine what sets this image+heading apart of other content? If so, we can figure out a component for it, to be used on this page and others.

**Comment by kristinashu** [comment]
Putting this on designers until we have done a full audit of what components we need the most.
