### ISSUE TITLE
[QA Wagtail] Issues when trying to deleting images on Wagtail

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1411]
### Issue 
When trying to delete copies of determined image, sometimes I get an error message like the one below:

![images-wagtail](https://user-images.githubusercontent.com/22157921/38946367-16a7d510-42ee-11e8-8bff-964a1f98bae7.gif)

Weird thing that is says "Mezzanine" on top of the page. Not sure what's going on there.

**Comment by Pomax** [comment]
I cannot seem to reproduce this locally. Can you list the steps you take in a text form that I can try to reproduce? The gif shows you delete image 112, but then get an error on image 109, so this might actually be a different issue that happens to be revealed during these steps, but isn't actually caused by the delete?

**Comment by alanmoo** [comment]
Once we switch to Wagtail for the opportunity/campaign pages we should see the real error here. Let's hold off on this till then.

(Besides, deleting an image in a CMS is usually a risky thing to do because it could be used on pages you're not aware of. I know that's not likely the case here, but it means this will get less pressing over time)

**Comment by kristinashu** [comment]
@taisdesouzalessa can you confirm is this is still an issue in Wagtail?

**Comment by taisdesouzalessa** [comment]
I am ok with Alan's explanation above. We can file another ticket if any issue arise. Closing this ticket.
