### ISSUE TITLE
[QA Opportunity Pages] List of items is too long

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1421]
There is a long list of locations so in Mezzanine we did this:
https://foundation.mozilla.org/wagtail/opportunity/global-sprint/
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/1068783/38963729-36f4c0f0-4328-11e8-9413-cbcbc993aa39.png">

Any suggestions on how we can do something like this in Wagtail?
https://foundation.mozilla.org/opportunity/global-sprint/register/
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/1068783/39005124-20dcc556-43b4-11e8-8f09-8eff2da6cb15.png">

**Comment by kristinashu** [comment]
Actually the wagtail list looks out of date, it's much longer now.

**Comment by Pomax** [comment]
We can set `column-count: 2`, but as richt-text content we don't control anything other than CSS applied based on element selectors (we can't use classes because we don't control the HTML that the rich text editor generates).

That said, we'd have to find something unique to this page for that, because right now it's "just another opportunity page" so if we change the column number, that's going to affect lots of other pages.

The alternative is a component with or without a tag that allows us to create these sections as "listings" for more control over how they're placed on the page. For now, it does not feel like this is bad enough to hold up going live though. @alanmoo?

**Comment by alanmoo** [comment]
Without analyzing it too deeply, my instinct is that this is the kind of thing that needs to be a template- 2 streamfields- one for the single column part at the top, and another streamfield where each block in it is a CSS grid element or something, so that we can add as many as needed using the other existing tools (like multiple paragraphs).

@gvn this feels like a thing you would have thoughts on.

**Comment by gvn** [comment]
So, I'm seeing a 3 column layout. Regardless I see 2 options:

1. Template
2. Create a "column list" component whose nested elements/components are rendered into either an element with a `column-count` CSS attribute set, or a flex layout.

I'd be more inclined to go with option 2 since it would be usable in more places (and since this is fairly simple display logic). We do also need to think about responsiveness, so likely it would need to go to a single column for narrow viewports.

Ideally I don't think we should give the user control over the number of columns.

**Comment by gvn** [comment]
FYI: This is how `column-count` looks (pretty janky):

<img width="637" alt="screen shot 2018-05-08 at 2 54 43 pm" src="https://user-images.githubusercontent.com/206379/39785195-1ffd17a0-52d0-11e8-83a0-da21cc9e81a7.png">

**Comment by kristinashu** [comment]
I don't think this is going to get done. Although it doesn't look great, the long list is functional and so far this is the only instance where it is needed so it isn't worth it to build.
