### ISSUE TITLE
Email Component and UX

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#1436]
@taisdesouzalessa @kristinashu and I chatted about how email appears currently on the site and how we can improve the experience to be more deliberate about our email strategy.

![email component overview](https://user-images.githubusercontent.com/2492510/39062979-45551cba-447e-11e8-9990-a3c746a55e19.jpg)

### **Design**
For the main foundation newsletter, the full-width, gradient treatment is appropriate to convey that it is the foundation wide newsletter for the site.

For opportunity specific email CTA snippets, I think this design should look like the grey style _(see fellowship example)_ where we can customize the language and an optional icon/graphic to reflect an opportunity specific email CTA.

The in between design seems confusing at a glance since it looks very similar to the foundation-wide email CTA. It has different language for the opportunity but I am unsure if it actually is specific for the opportunity. We can also consider to make the foundation-wide email CTA a fixture along with the footer on these other pages too.

_________________
### **Copy**
We want to make the language for these email CTA copy consistent if it leads to the same place and distinctively clear when it does not. This is also related to the email flow and UX.

_________________
### **UX**
- currently, no feedback if I am subscribed if I am already subscribed to another mozilla newsletter
- on my email preferences there seem to be no foundation specific option? where do users currently manage foundation emails?
- how are email themes/opportunities currently split and handled?

**Comment by stephaniemcv** [comment]
Sure! (I recognize that I just wrote a large info dump, and I'm happy to sit down and chat if that would be better.)

The main Mozilla Foundation list is "Mozilla" in the [newsletter preference center](https://www.mozilla.org/en-US/newsletter/existing/1821c5b1-0cac-4bcf-94dc-a5b617e25e41). Linked is my master subscription that shows all email programs (active and inactive). Smaller or inactive lists are only displayed on the preference center if you are currently subscribed in order to keep the amount of options in check.

Internet Health Report subscription signs you up for the Mozilla and the Internet Health Report Group to allow for granular control.

Mozilla Information Trust Initiative (MITI) while on our site is mostly managed by a MoCo team. I don't believe they've done any email sends recently.

Inactive lists that have been merged into the main Mozilla list - Mozilla Learning Network, Mozilla Leadership Network, Webmaker, MakerParty, Mozilla Festival.

Mozilla Festival is a weird one, because it is inactive in the Salesforce system. The active list is currently housed in TiTo to allow Mozfest better control over emails tied to events. 

There are other small Foundation email lists that have not yet been migrated into the Salesforce system, such as I believe Open Leadership is using TinyLetter.

There was a ux discussion around the double opt-in that might be helpful: #503

**Comment by kristinashu** [comment]
Thank you thank you! This is super helpful.

**Comment by Pomax** [comment]
@kristinashu is there still work to be carried out in relation to this?

**Comment by kristinashu** [comment]
I'm going to close this, although it was helpful to re-read it!

This work is being done it some in these related tickets:
- update the footer to include an email signup https://github.com/mozilla/foundation.mozilla.org/issues/2834
- adding newsletter signup to nav https://github.com/mozilla/foundation.mozilla.org/issues/2757
- remove unique email signup component from wagtail https://github.com/mozilla/foundation.mozilla.org/issues/2899
- Welcome email series work https://github.com/MozillaFoundation/Design/issues/331
