### ISSUE TITLE
Ensure foundation pages have OG image and data by default

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1455]
It seems like the default OG tags were lost in the switch to Wagtail. If a page doesn't have any tags set, it should use the tags of its parent (though it should use its own title like before). In addition, the homepage should be settable via the Wagtail admin.

**Comment by ScottDowne** [comment]
Titles should be working as expected, however, images are the only thing I am aware of that didn't get defaulted, and I wasted a day and a half trying to get that and ultimately gave up trying to get it through review.

I wouldn't mind a list of the tags that are defaulted improperly (title) other than image which can be easily fixed, probably just oversight, but images on the other hand is probably going to require me understanding more about how django stores the images? I think?

The long story on images was trying to understand the data django or wagtail or the meta data plugin spit back, because it's not a string, and trying to replicate it on the other end (in the .py file) ended up creating an image in the database and images dir each time a page was edited. It's probably doable, though.

In all honesty it shouldn't be this hard.

**Comment by Pomax** [comment]
I've closed the associated PR for now, if we can get a list of things that should be inherited we can see about forming a new PR to get this to work with the current code.
