### ISSUE TITLE
Global Sprint 2018 Featured Projects

### ISSUE THREAD

**Issue by acabunoc** [mozilla/foundation.mozilla.org#1506]
The website is only fetching the most recent 48 entries

On the site (48 projects):
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

In Pulse (58 projects):
https://www.mozillapulse.org/search?keyword=mozsprint%202018

It *should* fetch all the entries with the tags `mozsprint` and `2018`

**Comment by acabunoc** [comment]
If I edit 'Max number of results:', I still get the same result

**Comment by alanmoo** [comment]
This is by design from a performance standpoint. The Pulse project component in Wagtail tops out at 48 items; We're not trying to replicate Pulse inside the Foundation site. I'd recommend updating the page itself to be clearer that this is a portion of projects. You could try adding a button to the bottom of the list if you want, or you could reduce the list by only showing "featured" Pulse entries (right now that's a total of 3 matching projects).

**Comment by acabunoc** [comment]
People are freaking out over not being featured anymore & this was not explained when we decided to use the CMS. Can you make an exception for this page?

**Comment by alanmoo** [comment]
Are "featured" projects simply all Global Sprint Projects?

**Comment by acabunoc** [comment]
yes!

**Comment by acabunoc** [comment]
all the projects on Pulse that is. We don't approve projects that aren't 'featured'.

**Comment by alanmoo** [comment]
Ok. Looks like the problem is that the Pulse API returns pages of 48 by default, yet the component doesn't handle pagination.

Let's make the React component take the "Maximum" and pass that in to the API call for now, as a query parameter of "page_size". That way in the admin, you can set a maximum higher than the number of featured projects. This will slow the page down as the number of featured projects grows, but it's the simplest fix for now.

(For implementation, let's make sure we still default to 48 projects if "0" is set as the maximum)

**Comment by acabunoc** [comment]
Thanks @gvn!

The Sprint starts in ~ 6 hours. Any word when this will be live?

**Comment by alanmoo** [comment]
It's live
