### ISSUE TITLE
[Wagtail Component] Figure Grid Component Update

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#1515]
### Figure Grid

**Example** 
https://foundation.mozilla.org/about/leadership/ 
https://foundation.mozilla.org/opportunity/global-sprint/ 
logo grid used ONLY when 2 or more logos

**Recommendations**

- [x] If url is added then but no text then image is clickable
- [ ] Should replace the basic paragraph text with a full Paragraph component styling (h2-h6, p and links)? 

**CMS Fields:**

- [x] Upload images
- [ ] Paragraph component styling (h2-h6, p and links) ← should we add this?
- [x] URL (optional)

**Comment by gvn** [comment]
> Should replace the basic paragraph text with a full Paragraph component styling (h2-h6, p and links)?

If we do this then links will have to be added manually to applicable text in the paragraph instead of in their own field. Also we'd still need a link field for the image. This means that people would have to put the link in twice if they want both the image and the subtext linked to the same place.

I'd recommend we keep the subtext unstyled if possible for simplicity.

@taisdesouzalessa @kristinashu  what do you think?

**Comment by kristinashu** [comment]
I'm happy to keep it simple for now and only add it in the future if we really need it.

**Comment by taisdesouzalessa** [comment]
It makes sense to me as well!

**Comment by gvn** [comment]
Cool, I think this is done then...
