### ISSUE TITLE
Add an option to Pulse component admin for a 'view more' button

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1546]
The site admin includes a Pulse component so authors can include pull projects from Pulse to their page. Authors can set a limit to display 1 or more projects. 

Note: this should not block the implementation of our new project component admin. This issue should be design only until after that component has shipped. 

 - [ ] design a 'view more' button that appears on the page below the list of projects.  

 - [ ] add a toggle on the component admin 

admin copy: 
 - title: Include a view more button
 - help text: "This button will link visitors to pulse so they can explore more things with your tag or search" 

Constraint: pulse can't load all the selections from the component. It can load a tag OR a search OR an issue OR a help category. It cannot mix this. 

Question: should this be a separate component?
 - pro: we can make it's function more clear
 - con: authors will need to add two components and repeat similar settings

**Comment by taisdesouzalessa** [comment]
@xmatthewx I just want to make sure I understood your comment:

> pulse can't load all the selections from the component. It can load a tag OR a search OR an issue OR a help category. It cannot mix this.

Supposing we have the following scenario: staff chooses the tag "mozsprint" and in "advanced filters" chooses "digital inclusion" and "code". Considering we have the "view more" button. In the front end, will the "view more" take users to Pulse, where they will only see issues with the tag “mozprint” (the other 2 options won’t apply)?

**Comment by xmatthewx** [comment]
Yes, that's right. The view more button can just go to a single, primary attribute. Might be better is the button is separate component without advanced filtering.

**Comment by taisdesouzalessa** [comment]
## **Question**
Can Pulse load 2 or more tags OR 2 or more search terms?

## **Suggestions**
Since the button is related to this Pulse component, I find it could be confusing for staff if it was a separate component, like that:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/22157921/40455016-ea2a4f36-5e9f-11e8-9f36-acc6324627f8.png">

I like your suggestion of using it outside advanced filtering. What if we did something like that (option 1):
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/22157921/40455080-2f8f3ef6-5ea0-11e8-9905-b7ca89f63ce2.png">

Or like this (we repeat the checkbox in both fields so it is clear that they are used with one or the other field).Option 2:
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/22157921/40455126-61bb37d6-5ea0-11e8-92c9-960b3a5d71f8.png">

In the front end view, we should use the existing pattern we are using in our "Trending Projects" section of the [Foundation site](https://foundation.mozilla.org/). So it would be like this:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/22157921/40455191-ba373360-5ea0-11e8-8be1-1a6d548febc0.png">

I added those images to RedPen for feedback:
- [CMS view - option 1](https://redpen.io/zq9c7b83cb42d9bb20)
- [CMS view - option 2](https://redpen.io/po9719472ffc452ff2)
- [Front end view](https://redpen.io/er8d334d926f5eca42)

**Comment by taisdesouzalessa** [comment]
I was not aware of this requirement: 

> Authors might want a button with no project cards above depending on the needs of their content. (author would customize label instead of using default view more)

If this is a possible scenario, I think it makes sense to make it a different component then. 

To make things less confusing for staff (and audience of the site), I recommend we use default label "More from our network" (with option to change if desired). I find this label more generic and broad. I think "view more" can set the expectation of viewing more of the same type of projects, which is not true in this case, given the system restrictions. I also added a URL (with no option to edit) so staff knows the link of the button:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/22157921/40516278-e7aaf290-5f64-11e8-98b4-9bf239f9251b.png">

If staff adds a tag or a search term (I made them singular to be clear the system just accepts one), it would be nice if the URL updated to the new URL after the tag or search term is added so they know exactly the link that will be seen. Example `https://www.mozillapulse.org/tags/mozsprint`

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/22157921/40516424-77c75706-5f65-11e8-9d8c-01c871e29f8b.png">

Here is the Pulse link element in the dashboard:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/22157921/40516435-84eb0bee-5f65-11e8-927f-90eee3fbbb5f.png">

**Comment by xmatthewx** [comment]
@taisdesouzalessa and I discussed this again. The reasoning here seems solid:
 - button link to pulse should be a separate component, not part of the component that pulls projects (link can't handle all the filtering and people might want only button, not projects displayed.)
 - we can come back to this after we ship the project component.

**Comment by taisdesouzalessa** [comment]
For reference, this is the implementation ticket of the project component:  #1639.

**Comment by xmatthewx** [comment]
I think we'll keep this on the back burner, to stay focused on higher impact things. This can be partially solved in the Docs with a good example for authors on how to use the button component and a pulse search or tag URL.

**Comment by kristinashu** [comment]
@xmatthewx Ann-Marie has added in a regular blue ghost button after each pulse component https://foundation.mozilla.org/en/awards/directory/

Will that do?

**Comment by xmatthewx** [comment]
What Ann-Marie did is great, but many authors wouldn't how to create a search URL on pulse or that it would even be possible to link to that. I think we'll see more use cases and should directly support it. Does that seem reasonable?

That said, feel free to clarify or rescope this ticket based on Ann-Marie's use as a prototype.

**Comment by kristinashu** [comment]
@xmatthewx could you please close this ticket and open a new one with clarified steps/requirements (this one is tough to follow)?
