### ISSUE TITLE
Add fundraising modal after petition signing

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1589]
Goal: CMS authors have the ability to decide if a modal asking for donations should appear after users sign a petition.

Requirements:
* The copy of the modal (including CTA button) can be changed on a per instance basis using the CMS.
* When users click the CTA, a new tab is opened to the donate site
    * The link to the donate site passes along the campaign ID and information that identifies which modal version the user came from (for A/B testing purposes), as well as the user's email subscription status if they came from an email (#1588) or signed up during the petition.
* When the user comes back to the campaign page, the modal will be closed with the "share petition" links visible where the petition originally was located.

Suggestions:
Based on the first requirement, my instinct is that the modal content should be its own snippet model, so that CMS authors can simply attach it to a campaign so it happens, or not attach it.

Design:
https://redpen.io/xf5d9f47242418277e
https://redpen.io/sc98112fcc645c8449

Placeholder content:
(headline:) Thanks for signing! While you're here, we need your help.

Mozilla is a nonprofit organization fighting for a healthy internet, where privacy is included by design and you have more control over your personal information. We depend on contributions from people like you to carry out this work. Can you donate today?

(Button:) Yes, I'll chip in
No, I'll share instead 

This is synthesized from the conversation in https://github.com/mozilla/donate.mozilla.org/issues/1999

**Comment by alanmoo** [comment]
@kristinashu Please update the above link when you have a final design

**Comment by kristinashu** [comment]
Here are the final designs and I've updated the design links above.

Styling:
- heading: .h3-heading but center aligned
- body: .body-large but center aligned
- button: .btn-normal
- No, I'll share instead: Nunito Bold 16px #909090 (similar to btn text but sentence case and Medium Gray)
- white overlay: 0.9 alpha
- black border: 2px
- black shadow: 4px

![lightbox 2x](https://user-images.githubusercontent.com/1068783/41744328-531a3528-7558-11e8-9d5c-0c7d9317d61b.jpg)

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1068783/41744387-7c6ff00c-7558-11e8-98ca-9fbf9705c384.png">

**Comment by ScottDowne** [comment]
Two thoughts on this.

1. I'm not sure about the value for this (we can still do it as I don't think it hurts anything other than having to write a bit more code)
"When the user comes back to the campaign page, the modal will be closed with the "share petition" links visible where the petition originally was located."
I see this as come back to the original tab after donating, and not some storage shenanigans, correct?
I just don't think enough people are going to return, and I think we can explore better ways to drive share without lowering donations and signatures.
Example brainstorm hypothesis for share: Possibly people that come to us from an email are more likely to donate after signing, but social campaigns that start with twitter, people are probably more likely to share, and what's interesting about that is they might share, and THEN sign the petition. Think of building much like we build a mailing list.

2. I like what you said Alan around making the donate modal a snippet. I also think the snippet would work if being added to the page, kinda beside the petition snippet. Another approach and only adding just in case it wasn't considered, and not because I think it's better or something. Would it make any sense if the donate snippet is added to the petition snippet and not the page? Can a snippet contain a snippet?

Those are my thoughts on this.

**Comment by kristinashu** [comment]
This was another layout I was playing with but thought it would be harder to implement. So after a user signs the petition, they see the share prompt where the form was and but then a modal slides up from the bottom. More on this in https://github.com/mozilla/foundation.mozilla.org/issues/1613

![red-pen-a6e3bafa-16af-4d92-f5ef-f04a6201e3f8](https://user-images.githubusercontent.com/1068783/41986253-77a509e0-79ea-11e8-8b41-94a1e78ce973.jpg)

**Comment by kristinashu** [comment]
Becca has also explore an option with the share buttons below the form. But I worry a little about distracting users from actually signing the petition.

![red-pen-e6cc03e9-3b36-4e7e-abf6-2a2eea433bde](https://user-images.githubusercontent.com/1068783/41986489-252a0836-79eb-11e8-9c83-d6999da3c0fa.jpg)

**Comment by kristinashu** [comment]
One other advantage of the classic lightbox modal is that it is more flexible for swapping in other content like an newsletter signup or promo a different petition, event, article... or even adding additional modals in the future.

**Comment by Pomax** [comment]
Styling is still in progress:

![image](https://user-images.githubusercontent.com/177243/42901910-b632a7e2-8a81-11e8-94a6-3b51d9fae47e.png)

**Comment by Pomax** [comment]
We get two size choices from bootstrap, medium:

![image](https://user-images.githubusercontent.com/177243/42903027-55c29486-8a85-11e8-96fb-e47f37e79a20.png)


And large:

![image](https://user-images.githubusercontent.com/177243/42902986-3bfbc0ae-8a85-11e8-82cd-e3107c1f0e60.png)

It feels like "large" is the better option? @kristinashu

**Comment by Pomax** [comment]
Current styling:

![image](https://user-images.githubusercontent.com/177243/42903281-3231af38-8a86-11e8-9862-fbaa27243897.png)

@kristinashu the body text doesn't look like it's matching the comp typeface, which family, size, and colour settings should be used for that?

**Comment by kristinashu** [comment]
Sorry, I'm late to the party. Are you still wondering about the body text? It should be the same as .body-large in the [Style Guide](https://foundation.mozilla.org/style-guide/) except center aligned.
