### ISSUE TITLE
Campaign graphic: Data privacy in India

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1661]
### Design brief
https://docs.google.com/document/d/1-kq_1jQgBdUae_Ptp02rRzQ3nwGfMgyL-gHKww-qNLg/edit 

### Social media platforms
Start with graphic for Twitter and Facebook (1024px X 512px). Once approved, then landing page, email, and WhatsApp.

### Copy
Start with
> Your data your choice
You deserve a say in how your data is used. Take action now [link: privacyfirst.in]

Once approved, then maybe do others in the doc.

### Look
Doesn't have to look like this but could be something like https://foundation.mozilla.org/campaigns/release-the-bill/

### Deadline
In flux since we don't know when the bill with drop.

**Comment by taisdesouzalessa** [comment]
### Ticket update

### Issue
Rachita mentioned in e-mail that we wont be launching a campaign immediately, rather, we'll want to focus on explainer graphics which will basically consist of the good and bad things about the bill when it's released. 

### Design Request
to make a template which we can populate with 2-4 lines as soon as the bill comes out (so that the community can share them).

<img width="316" alt="image" src="https://user-images.githubusercontent.com/22157921/42524762-464dd2aa-8426-11e8-9974-3c23e28cc5f1.png">

### Dimensions
Since it is a graphic to share, the assumption is that the size is Twitter size (1024px X 512px). Asked Rachita via e-mail to confirm.

### Additional Info
Requested Rachita to update the design brief.

**Comment by taisdesouzalessa** [comment]
Here is the graphic in the Twitter context:
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/22157921/42604573-5ad91024-8528-11e8-98df-73a8136600c1.png">

Here is the graphic on RedPen: https://redpen.io/cfa4dc48a63c782e85

**Comment by taisdesouzalessa** [comment]
One thing that came up from the design crit today is the meaning of colors and symbols that can vary from culture to culture. Since the audience is English speaking Indian internet users, it's good to double check with Rachita if the colors and checkmark and "x" make sense to our audience.

**Comment by taisdesouzalessa** [comment]
After feedback form Rachita, here is V2:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/22157921/42786595-b6c27fc4-890b-11e8-9dd8-e3829bd9ebac.png">

RedPen: https://redpen.io/wvcc34ea3f523805fd

**Comment by taisdesouzalessa** [comment]
UPDATE: removed "the" from the top of "good" and "bad" as per design feedback. It looks cleaner now!

**Comment by taisdesouzalessa** [comment]
Design is ready but we didn't receive any content for this graphic. I will leave this ticket open as a reminder.

**Comment by alanmoo** [comment]
Is this still relevant @kristinashu?
