### ISSUE TITLE
Web Literacy Core Curriculum interactive as well as on the old website

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/foundation.mozilla.org#1690]
Hi MoFo Dev Team,

The Web Literacy Core Curriculum is a great, useful and meaningful resource for who is working for web literacy programs, and previously the old [Web Literacy Curriculum is a interactive diagram](https://learning.mofostaging.net/en-US/web-literacy/). So, I would like to have in the [newest page](https://foundation.mozilla.org/opportunity/web-literacy/) the curriculum interactive as well as on the old website because it facilitates visualization and demonstration.

Hope it's a great idea for work in the future. :)

Cheers!

**Comment by Pomax** [comment]
@alanmoo is this something we have cycles for? (we don't allow free-form JS on CMS-managed pages, so I can see this taking quite a bit of time to figure out)

**Comment by alanmoo** [comment]
Unfortunately no, we don't at this point in time.

cc @anilkanji for awareness.

**Comment by gideonthomas** [comment]
Hi @barrosgeraldo, thank you for filing this and sharing your feedback. 

As we continue to evolve and focus on new threats and opportunities arising towards the open internet, the need to sunset legacy products becomes necessary. Unfortunately the interactive web literacy map falls under this scope.

With that said, we continue being active supporters of web literacy and hence want to preserve strategic content (as opposed to interfaces and interactivity) from our previous program. This is why we included a static version of the web literacy map in the [new page](https://foundation.mozilla.org/opportunity/web-literacy/) you linked. If you do find any content missing from that page, please do let us know.

Closing this issue since there isn't anything actionable for design/dev.
