### ISSUE TITLE
Donate Petition Modal followups

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#1697]
1. - [x] Finish #1694
2. - [x] Make the main CTA button have a visible focus state (and be focused by default)
3. - [x] Update fake data generation to create at least one donate snippet and attach it to various campaigns

**Comment by Pomax** [comment]
for (2) we probably need some design input from @taisdesouzalessa and/or @kristinashu, because right now the focus indicator looks pretty different from the flat design the site otherwise has:

![screenshot 587](https://user-images.githubusercontent.com/177243/43424645-ec9a942a-9404-11e8-91b3-b6b9bdb90486.png)

![image](https://user-images.githubusercontent.com/177243/43424631-e5ab7576-9404-11e8-8d55-9677c1da190d.png)

**Comment by taisdesouzalessa** [comment]
I am just curious on why we are making the button focused by default. I am guessing that it is easier for users to select the button "Yes, I'll Chip In" (they just have to hit "Enter" in the keyboard) and also for accessibility reasons? Although if a person is navigating using tab, wouldn't it be better to give them a choice to choose "Yes, I'll chip in" or "No, I'll share instead" instead of pre-selecting for them? I would love to hear what you think of that @alanmoo and @Pomax. 

About the styling, this seems to be our default focus on the site. In one hand, it is very different from the flat style we have on the site but in the other hand it it makes super clear that the button is focused. I'll bring this discussion with the other designers so we can change the overall style of `:focus` in the whole site. I would rather change it everywhere than just on this instance:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/22157921/43477375-dccc5f96-94af-11e8-92c4-44237669d000.png">

Tagging @kristinashu here so she is aware of this discussion :).

**Comment by alanmoo** [comment]
>I am just curious on why we are making the button focused by default. I am guessing that it is easier for users to select the button "Yes, I'll Chip In" (they just have to hit "Enter" in the keyboard) and also for accessibility reasons?

This was my thinking. Make it as little work as possible to guide anyone to donating. This doesn't feel like the type of situation to let them choose- it's pretty obvious what we want them to do. We wouldn't change "Yes, donate" and "No, don't donate" to be the same buttons anyway, so why make it a non-obvious choice in actions?

**Comment by alanmoo** [comment]
We're already asking them to give us money. We've crossed the "pushy" line as far as I'm concerned.

@WillatMozFdn As the primary stakeholder, does it make sense to you that the "Donate now" button has keyboard focus as soon as it appears/is that a desired functionality? This way someone can simply hit "return" to open the donate page. I don't feel too strongly either way, I just figured it was low hanging fruit, technically speaking, which could improve conversion/make the page more accessible.
