### ISSUE TITLE
Move Awards page to /initiatives/

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#1760]
The Awards team has crafted a [page](https://foundation.mozilla.org/opportunity/awards/) on wagtail. It's currently nested under `/opportunity/`, but should probably have a permanent home under `/initiatives/`. 

@alanmoo - can that be moved by you with a click? Does it require copy-paste and a redirect? 

cc @jenntbeard

**Comment by alanmoo** [comment]
Moved!

**Comment by jenntbeard** [comment]
Awards at Mozilla are designed to support diverse approaches to addressing the most pressing threats to Internet Health. Awards celebrate a variety of targeted solutions, not a one-size-fits-all silver bullet. They spotlight the technologies, art, and other work being done by leaders across the globe in order to amplify these promising approaches and to help make the internet healthier for all.

**Comment by xmatthewx** [comment]
I opened a new ticket for this content.

**Comment by jenntbeard** [comment]
Cool, thank you!
