### ISSUE TITLE
Buyers Guide: images for social

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#1918]
Based on Nat's banner design in we need an image for sharing on Facebook and Twitter. 

Might need to resize some of these for screens at mozfest, postcards, blog posts...

[Copy doc.](https://docs.google.com/document/d/1hRYn2EFAJxGjikeQqsXeeiaPOdJy37dzwi10PJTl_EA/edit#heading=h.j8n12cvme0nu)

#### Versions could include:
- same as banner #1870 
- same as banner but with logo lockup over top https://github.com/MozillaFoundation/Design/issues/286
- mozfest specific https://github.com/MozillaFoundation/Design/issues/281
- mozfest raffle specific
- mozfest raffle winner
- something using the creep-o-meter
- show comps (home page or product page)
- animated gif
- ...

**Comment by caltrider** [comment]
Based on last year, we'll also need some banner/images for blog posts on both the Mozilla blog and Medium. A banner and a couple or three product/creep-o-meter images should work for that. Some media use images we could share with media as part of press releases would probably be good too. Kevin Z can probably advise on that.  That's all I can think of adding at the moment.  
@kristinashu

**Comment by beccaklam** [comment]
## 1. Social
**Platforms:** Twitter, Instagram, Facebook (??)
**Size:** 1:1 ratio works for all platforms, 1080 by 1080px has served as well in the past, otherwise 2:1 ratio works well enough for Twitter and Facebook
**Content:** ??

## 2. Screens at MozFest
**Platforms:** Screens at MozFest
**Size:** ?? @natalieworth can you drop in dimensions here?
**Content:** Advertise raffle and winners

## 3. Banner Ads
**Platforms:** MozFest site and direct ad buys (future)
**Size:** ??
**Content:** ??

**Comment by beccaklam** [comment]
Banner ad specs for desktop ad on MozFest site @caltrider 
Standard leaderboard (728x90) In-situ here (ad will be in the red box):
![banner-ad](https://user-images.githubusercontent.com/20977376/47097007-6fa85000-d1fe-11e8-8d7a-337e6006d2be.jpg)
Still need to figure out mobile sizing

**Comment by beccaklam** [comment]
Mobile banner ad placement:
![mobile-bannerad](https://user-images.githubusercontent.com/20977376/47105712-bacc5e00-d212-11e8-9835-72c62cf642a8.jpg)

**Comment by kristinashu** [comment]
MozFest is done! Opened a new ticket for general launch promo https://github.com/mozilla/foundation.mozilla.org/issues/2090
