### ISSUE TITLE
Buyers Guide QA: hide url for updates 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2025]
The title should be linkable and the URL should not be visible. 

Staging
<img width="926" alt="screen shot 2018-10-23 at 2 22 46 pm" src="https://user-images.githubusercontent.com/1068783/47392001-23fb1800-d6d0-11e8-9516-02f82b609076.png">

**Comment by Pomax** [comment]
I think I'm missing some details around what the expected behaviour is supposed to be for which element(s) -- Is the idea that the product's title will link to its buyersguide URL, or to the product's original URL on the manufacturer's website? 

If the first, that should be straight-forward, but I'd recommend against the second, instead making it link to its buyersguide URL, and then having a separate obvious field on the product's page that people can click, where they can reasonably expect to be taken off our site, and to some third part product page.
