### ISSUE TITLE
Buyers Guide: make it clear to users where the product link in updates will take them

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2028]
In the "update" section of the product page we're currently linking to the source of the update (news item, product changelog, whatever explains how the product changed), by linking there from the update's title, but as a website that brings transparency to creepy products it might be a good idea to explicitly show people that URL so that they know where they're going to be sent to if they click on it.

**Comment by kristinashu** [comment]
Sorry @Pomax are you ok if I close this ticket? This linking pattern is fairly standard practice on our sites, although we are trying to use the external link icon more and more and the icon will be incorporated into our brand standards (currently wip). But since we are not linking to anything harmful and have limit resources for working on this project I just don't think we'll get around to this.

**Comment by Pomax** [comment]
yep
