### ISSUE TITLE
Associate creepiness vote with likelyhood vote

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2088]
It would be great to be able to answer questions like "does perceived creepiness have an impact on how likely someone is to buy a product". Let's find a way to link the two votes together so we can make that type of analysis.

**Comment by Pomax** [comment]
what is the hypothesis you would want to test with that data? (because without a hypothesis, raw data is just raw data)

**Comment by alanmoo** [comment]
@xmatthewx may have better insights to this than me, I believe this was originally his idea.

**Comment by xmatthewx** [comment]
hypothesis: 1) perceived creepiness would negatively impact likelihood to buy for many products, but 2) there may be other factors that disrupt an otherwise linear relationship. for example, a category of product might have a threshold of allowable creepiness. or the impact might taper off for high priced products.

**Comment by kristinashu** [comment]
Am I correct in assuming this is not a feature request but a way for us, internally, to look at the data?

**Comment by alanmoo** [comment]
Yup

**Comment by Pomax** [comment]
Hm, I'm worried about us using our data to try to answer those questions: we don't have the kind of data that is necessary to say real things here. We can find some correlations, and we can certainly scatter-plot the correlations between creepiness and likelihood-to-buy for products, but that's effectively all we can do.

So we can sort of do 1, as long as we understand we can't see "impact", we're only seeing correlation (there is no way to tell whether that's creepiness affecting likelihood, or whether likelihood influences people's decision on how to mark creepiness, for example). Testing 2, though, is definitely beyond the scope of what our data lets us check in a statistically valid way. We can look at a creepiness/likelihood plot to see if clusters emerge, and then see what products in those clusters share, but that really still just gives us correlation data specifically for _our_ list of product, and might yield completely different clustering for a subset of our data (and equally, change completely even if we add one or two new products of which we currently known no creepiness/likelihood values). 

So I guess another question is: what are the stats to be used for? Because using them for a neat blog post is very different from using them to start making claims on the website, or even send out emails that "our data shows that ..." =)

**Comment by kristinashu** [comment]
Sorry but I don't know what to do with this ticket! @alanmoo @xmatthewx could you please write some clear next steps or close it?

**Comment by alanmoo** [comment]
At the root of this is a request to tie the votes together, so we can slice the results differently. That being said, I don't see us having the bandwidth for this right now, and I think we should simply punt till we look at the guide again and discuss ways to improve it for (presumably) the next holiday season.
