### ISSUE TITLE
 Update HTTP to HTTPS

### ISSUE THREAD

**Issue by missuniverse** [mozilla/foundation.mozilla.org#2218]
Changed links to HTTPS when supported.
Pull request:
#2219 

Please review the pull request.

**Comment by Pomax** [comment]
Thank you for the PR, but I would like to know why you filed it. Most of the changes in your PR are to text/comments rather than active code, and so aren't a problem that requires fixing. The only active code change is to the by-convention inactive domain "example.com" so whether that points to http or https (or even ftp or mailto, etc) doesn't make a difference.

**Comment by missuniverse** [comment]
@Pomax Think of it more as an enhancement then anything else. The more we use https, even in comments, the better.

**Comment by Pomax** [comment]
fair, I mostly wanted to see if you were a bot or a real human. Had you been a bot, there definitely wouldn't have been a response as intelligent as yours =)

Merged, thanks for the fix!
