### ISSUE TITLE
Add link to Participation Guidelines in footer

### ISSUE THREAD

**Issue by hannahkane** [mozilla/foundation.mozilla.org#235]
- [x] We'll need an icon 
 - [ ] Link should read "Participation Guidelines," should go between the Facebook and the License items, and the target should be https://www.mozilla.org/en-US/about/governance/policies/participation/

**Comment by kristinashu** [comment]
We have a cute smiley face `Code of Conduct` icon in https://mozilla.github.io/mofo-bootstrap/demo/ we can use.

**Comment by jayyyin** [comment]
@hannahkane is this issue still open?, also should the site be linked as is?

**Comment by kristinashu** [comment]
Yes, this still needs to be done. Here is how it should look:

![footer](https://user-images.githubusercontent.com/1068783/33733895-11901134-db40-11e7-8ae4-f2c9ced6861e.png)

- Here is an svg of the icon: [ code-of-conduct.svg.zip](https://github.com/mozilla/foundation.mozilla.org/files/1540309/code-of-conduct.svg.zip)
- Text: Participation Guidelines
- Link: https://www.mozilla.org/en-US/about/governance/policies/participation/
- Goes between the Facebook and the License
- Same styling and hover as other footer items

@gvn does that sound right to you? Have any additional guidance?

**Comment by gvn** [comment]
@kristinashu Is this a link that should go in all our footers on our various sites? If so, we should try to add it upstream in mofo-bootstrap first.

**Comment by kristinashu** [comment]
Yes, that's right. Thanks @gvn!

**Comment by gvn** [comment]
Would you mind filing a ticket there?

**Comment by jayyyin** [comment]
@kristinashu @gvn So, where should the change be added? also are you referring to the icon? and is there an issue or link I can follow to possibly help with the bootstrap?

**Comment by jayyyin** [comment]
@kristinashu @gvn I've opened an issue on the mofo-bootstrap, and I'm currently wondering how to proceed from there https://github.com/mozilla/mofo-bootstrap/issues/122

**Comment by gideonthomas** [comment]
@jayyyin, sorry for the delay!

Thank you for filing the issue in mofo-bootstrap. I think for this specific issue, it might need to be fixed in this repo. You are welcome to fix the issue in mofo-bootstrap as well, but it is its own issue.

For this specific issue, it looks like we already have code for this (and the image is already in mofo-bootstrap) so we just need to update the actual text. If you uncomment the lines here: https://github.com/mozilla/foundation.mozilla.org/blob/master/source/pug/templates/master.pug#L81-L82 and replace the text "Code of Conduct" with "Participation Guidelines" and also replace the href with what is provided above, that should suffice to fix this issue.

I have commented in the mofo-bootstrap issue on how we might want to fix that one so feel free to look at that as well. Let us know if you have any questions @jayyyin.

**Comment by jayyyin** [comment]
@gideonthomas should the (what looks like) the CSS class tag change? it says Code-of-Conduct still.
