### ISSUE TITLE
Update voting section of PNI site

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#2405]
Based on user testing and feedback, we are updating the PNI site vote section to try and reduce user errors/ frustrations. Currently the vote section doesn't provide error feedback if the user only gets through one vote section. 

[Redpen with instructions is here.](https://redpen.io/p/oq8a929059c9e4976b)

Updates:

- [ ] Add error 'hint' state to 'How likely are you to buy it' if the user tries to click 'Vote' button after only completing the 'how creepy is this product'
- [ ] Add hover state to 'How likely are you to buy it'
- [ ] Add clicked state to 'How likely are you to buy it'

P2 if there is time/ if possible:
- [ ] Add a hint (when user scrolls down the page) to the 'How creepy is this product' (as in the gif example below)

![02_creep-o-meter-hint](https://user-images.githubusercontent.com/14876567/50717140-2d8eed80-103a-11e9-849e-a5b21210a006.gif)

cc @beccaklam @kristinashu @gideonthomas

**Comment by mmmavis** [comment]
@natalieworth 

I have a few questions:

> Add error 'hint' state to 'How likely are you to buy it' if the user tries to click 'Vote' button after only completing the 'how creepy is this product

I'm wondering how we determine if users have answered the `How creepy do you think this is?` question? We could check if the creep-o-meter has been moved but this wouldn't cover the case when users just wanna stay neutral (and hence not moving the slider so it stays at center)

> Add hover and click state `#3BB7EF` to 'How likely are you to buy it' buttons

- If the capsule buttons are currently on "error hint" state (highlighted in `#C0ECFF`), what happens if user decides to hover over them? Do we clear the error hint highlight `#C0ECFF` and make the hovered button highlighted in darker blue `#3BB7EF`? (So one side is highlighted and the other is in white?)
- What happens if user moves away from that section without picking a choice? Do the capsule button glow in error hint highlight `#C0ECFF` again?

**Comment by mmmavis** [comment]
After chatting with designers we have decided to change the specs a bit.

New specs

- [ ] Add hover and click state to capsule button `#3bb7ef`
- [ ] `How likely are you to buy it?` capsule buttons wiggle if user tries to submit the form without answering that question
