### ISSUE TITLE
Enable "draft" Buyer's Guide products

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2434]
As the team prepares to launch updates to the guide, we need a way to add products that aren't live yet.

I'm not tied to a specific solution, but some ideas that might be useful

* Boolean "is live" or "publish date" could be used
* It's probably useful for unpublished products to be visible to logged in users for previews.

**Comment by alanmoo** [comment]
@caltrider Any other thoughts?

**Comment by caltrider** [comment]
I'm most familiar with something like Medium does with a "publish" feature. So that you could input all the info and have it available to review/double check/preview, and then publish when we're ready to roll out the launch. That being said, since we won't be promoting the guide before the V-Day launch, I don't imagine we'll have too much traffic to worry about if we add things and make updates to get things right before a launch promotion.

**Comment by caltrider** [comment]
I do love deliciously obvious!

**Comment by Pomax** [comment]
@kristinashu right now I've added some dummy CSS to effect "making it obvious that some products are draft" but I don't actually know how much attention should be drawn to them, or what the "least intrusive, super obvious" way would be. Would you have any advice? =)

**Comment by kristinashu** [comment]
Looks good! I think your red text is enough, doesn't even need the extra red border.

**Comment by Pomax** [comment]
excellent, I shall take out the border CSS
