### ISSUE TITLE
Evaluate which wrapper to assign `.cms` class to

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2454]
We don't seem to be consistent about which wrapper(s) in CMS page template we assign `.cms` class to. This means that the CSS rules we set for `.cms` won't cover all CMS generated content for some sections.

Let's first evaluate if we need to keep the `.cms` class. And if so, which wrappers should have that class.

---

From Pomax in https://github.com/mozilla/foundation.mozilla.org/pull/2452#issuecomment-454977695

> Also note that the `.cms` class is for all CMS streamfield content. Not for any template code outside of that.

**Comment by youriwims** [comment]
I think for the sake of organization and consistency, we should definitely utilize this class. It's worth looking into to see what exactly needs this class and start revising the code to better reflect cms-entered content. @Pomax, what do you think?

**Comment by Pomax** [comment]
I think one problem with the `.cms` class is that it's not the right name. It gets generated for all Wagtail Streamfield content, so we probably want to rename it so that it's clear that it does _not_ apply to "all CMS content", but only to "content associated with Streamfield components".

It's a good class to keep, but definitely needs a rename.

**Comment by mmmavis** [comment]
Yea I think renaming it to something more specific would help a lot. I wonder if we can come up with a way so we don't have to manually add that class name every time we add a new `Streamfield` component?

**Comment by mmmavis** [comment]
Closing. We are good with using `.cms`.
