### ISSUE TITLE
OL7 'Mentors and Experts' Page takes a long time to load

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#2459]
Both myself and @acabunoc are experiencing pretty long (over 10 second) load times for when trying to load the Mentors and Experts page for Open Leaders 7. There's a pretty long delay it seems if it's loading the page.

URL: https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/round-7/mentors/

The rest of the site is working fine for us.

**Comment by gideonthomas** [comment]
@cadecairos you have started working on image optimizations for pulse right? Do you know if a. it's related to this ticket, and b. if it will be done soon?

If this needs to be done sooner, let's get someone to spend a little time just manually lowering the size of the images used for OL7. @cadecairos to advise.

**Comment by cadecairos** [comment]
There have not been any major developments on the image optimization front for pulse. Right now I'd suggest wither optimizing this page so not all the images load at once, and to go into those profiles and optimize the images, as many are well over 1MB.

**Comment by gideonthomas** [comment]
@kristinashu would a designer be able to take this on? If not, I can optimize them on the backend myself, should be fairly straightforward.

**Comment by kristinashu** [comment]
@gideonthomas would be great if you could find a way automate it.

**Comment by gideonthomas** [comment]
@kristinashu I believe that's the long term plan that devops is working on and will take a while to implement based on the comment above.

I'll optimize them in the admin interface for now so that we aren't blocking on automated optimization.

**Comment by gideonthomas** [comment]
@xmatthewx to advise; here's the situation:

I have lowered the image sizes of about 25 profiles from an average of 1.5mb each to 150kb each. In spite of this, the page size is ~15mb in images alone so it is going to be slow. I can further reduce all image sizes but it's a lot of work to do it for 100 images (it's straightforward but super tedious) -- which is the biggest culprit here.

We're loading over a 100 profile images on this page. So even if I'm able to get the image sizes for all images down to 100kb, that is still 100 images x 100kb each = 10mb page size -- which is still quite large (and consequently slow). We have decent caching measures in place so that won't help either. I suggest linking directly to pulse once we have the profile search in place if we want a faster load time.

**Comment by gideonthomas** [comment]
Closing in favor of the optimization automation ticket.
