### ISSUE TITLE
Increase max number of highlights on Initiatives Featured Programs and Projects section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2561]
I've added a 4th highlight to [initiatives](https://foundation.mozilla.org/en/initiatives/) `Featured Programs and Projects` section but it isn't showing up on the page. Is there a max of 3 features for this section? If so, please increase it to 9.

Screen cap of cms:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1068783/52086707-7dd76d80-255c-11e9-9390-9afdf21253e6.png">

Screen cap of prod:
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/1068783/52086733-90ea3d80-255c-11e9-91c9-e6ca0804e9d7.png">

**Comment by Pomax** [comment]
Yeah, the template limits it to 3 (see [here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/static/initiatives_page.html#L72-L82)) but I can't remember why we did that rather than just trusting people who have the rights to modify the initiatives page to know what they're doing.

@alanmoo objects to removing that count limit and just rendering `.all()`?

**Comment by alanmoo** [comment]
My only guess is "if there's 5 it looks weird", but yeah, I'm fine letting that minor breakage happen if it's our own doing. (Though ideally those might be flex'd items or something based on a design recommendation, it's not necessary to address right now.)

**Comment by alanmoo** [comment]
It seems like the 3 was, in part, a way to enforce it looking good at all screen sizes. Currently, we hide the third item on "medium width" devices, so that it doesn't end up looking like this: 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/1682681/52244377-5ad5f200-28ab-11e9-8ab8-9573dd07a594.png">

If we unlock this to allow an arbitrary number, there's always going to be a case where there's a widowed item or two at some screen size. Is this ok @kristinashu?

**Comment by kristinashu** [comment]
Yeah, I think that's ok if there are gaps sometimes.

**Comment by Pomax** [comment]
roger - I shall land this PR, then, and if it turns out to be a problem we can address it in a new issue?
