### ISSUE TITLE
Remove .person-card-featured .more-details SCSS rule set

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2640]
It doesn't seem like we have any `.more-details` elements in `.person-card-featured`. If that's really the case let's remove its SCSS.

**Comment by ayushi1998** [comment]
Hey
I am interested to solve my first issue on github.
May I know if this also a project open for @Outreachy upcoming internship in Summer?

**Comment by mmmavis** [comment]
Hi @ayushi1998 thanks for offering help! This is not an Outreachy project this year but you still are welcomed to take on this ticket. Just let us know :)

/cc @Pomax to provide support while I'm away 😃

**Comment by Pomax** [comment]
:+1:

**Comment by HSR05** [comment]
Is this still open? I'd like to work on this. Can you guide me @Pomax

**Comment by Pomax** [comment]
@HSR05 certainly. The issue is about the `.more-details` rule, nested under `.person-card-featured` in the `source/js/components/people/people.scss` file - this was used by `source/js/components/people/person.jsx` but while the `person-card-featured` class is still in use, the `more-details` class doesn't appear to be. So the work would be to

1. confirm there the particular class isn't being used anymore and then,
2. if that is really the case, remove it from the .scss file

**Comment by HSR05** [comment]
@Pomax Thanks for the guidance. I'd start working on it and update you ASAP.
Cheers 👍

**Comment by HSR05** [comment]
@Pomax  I created a PR for this. Please review and advise. Cheers 👍
