### ISSUE TITLE
Turn on streamfield table block

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2660]
Let's not land this quite yet, but open a PR so the designers can play with it and see if it meets our needs (or comes close enough) as is.

Add it to campaign and opportunity page streamfield blocks (assuming it's a streamfield component)

http://docs.wagtail.io/en/v2.1/reference/contrib/table_block.html

**Comment by alanmoo** [comment]
Tag @beccaklam for design review when it's open

**Comment by Pomax** [comment]
Soooooo this block is neat, but also highly problematic because there is no clear way to dynamically set the number of rows and columns. They have to be prespecified at the streamfield block level so you can have a "3x3 block" or a "12x280 block", but not "a block and then you get to say how many rows and columsn you need", which is super weird.

**Comment by Pomax** [comment]
PR was closed, as it turns out that airtable embeds work perfectly fine, and are infinitely more expressive than the table component could ever be.
