### ISSUE TITLE
Accordion Component for Wagtail

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#2695]
For both the Fellowship Pages and the Misinfo Campaign, it would be nice to have an accordion component similar (pretty much the same) to what the Buyer's Guide 'How To Use This Guide' uses to define their criteria: https://foundation.mozilla.org/en/privacynotincluded/about/

This is the Fellowship pages' mockup: https://redpen.io/hm31c4dca8f8ac879c
This is the (very rough) mock up from the Misinfo campaign: https://redpen.io/yoc6d15d5d2a2efc12

**List of requirements:**
- [ ] Accordion capability
- [ ] Able to set headers (h4) for different sections (should the need arise, see Fellowship pages where the accordions are divided by fellows)
- [ ] Open and close buttons like the buyer's guide ('+' for open 'x' for close)

**Comment by Pomax** [comment]
Unfortunately, the buyers guide is not part of wagtail, and exists as a parallel app that uses all-custom code to make it look the way it does, with the accordion functionality being custom tailored to the guide and almost impossible to port in a way that would work within the wagtail system or organizing page data =(

While we can probably come up with a way to make an accordion component that feels the same, we'd have to do that work from scratch rather than borrow from the buyers guide, and it'd probably take a fair amount of time to get done.

**Comment by youriwims** [comment]
@Pomax where could I start with this?

**Comment by kristinashu** [comment]
I think this would be a valuable component to have that we could use is a few places. The [Fellowships FAQ page](https://foundation.mozilla.org/en/fellowships/faq/) is crazy long and not very usable right now.

**Comment by Pomax** [comment]
If we turn this into a component, we'd realistically have to split up that content into regular content, and "paragraphs with folding turned on based on headings" or something, Would that be acceptable @kristinashu ?

**Comment by kristinashu** [comment]
Hmm not too sure what you mean... do you mean that each accordion would be a separate component? Or do mean any heading within the accordion component would automatically become an accordion?

**Comment by Pomax** [comment]
Components only control "their own content" so we can't create a component that indiscriminately turns all headings with text into foldable content, but we can create a special kind of "paragraph" component that adds folding to all of its own content. So instead of the current Fellowship FAQ page with a single long paragraph component, you'd get something that looks more like:

- normal "paragraph" content for the lead-in (e.g. the first title and lead-in paragraph of text)
- "foldable content paragraph" content, where each h2 or h3 can fold away content between it and the next h2 or h3, or the end of the content block)
- normal "paragraph" content for the lead-out (if there is any)

**Comment by kristinashu** [comment]
Oh yes, that sounds fine!

**Comment by Pomax** [comment]
Cool, in that case @youriwims have at it =)

**Comment by cadecairos** [comment]
Closing this issue due to its age, if this is work that we still want to do, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
