### ISSUE TITLE
Remove old Participate page model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2828]
It's been replaced by Participate2 and that's now being mocked in fake data generation. Let's get rid of the old one entirely.

**Comment by abhinavsagar** [comment]
Can i work on this?

**Comment by alanmoo** [comment]
Sure, feel free to open a PR and we'll take a look at it (just keep in mind this team mainly works daytime hours in North America)

**Comment by abhinavsagar** [comment]
Ok I am working on this. I will open a PR as fast as I can.

**Comment by Pomax** [comment]
Speed is less important than doing it right - make sure to read through https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#how-to-prepare-and-deploy-your-backward-incompatible-migrations because removing models is _not_ a simple matter of "deleting the code" and generating a new migration file =)

**Comment by youriwims** [comment]
Removing this model is blocked by removing its usage in `/network-api/networkapi/wagtailpages/translation.py`. We're working on establishing a process to fully remove translation bindings in order to remove the model's import in `translation.py` thereby making it okay to completely remove the model in `/network-api/networkapi/wagtailpages/models.py`. [This is also an issue](https://github.com/mozilla/foundation.mozilla.org/pull/2904#pullrequestreview-221278351) with `PeoplePage` (Reference #2904 , #2898).

**Comment by youriwims** [comment]
Removing this model is blocked by removing its usage in `/network-api/networkapi/wagtailpages/translation.py`. We're working on establishing a process to fully remove translation bindings in order to remove the model's import in `translation.py` thereby making it okay to completely remove the model in `/network-api/networkapi/wagtailpages/models.py`. [This is also an issue](https://github.com/mozilla/foundation.mozilla.org/pull/2904#pullrequestreview-221278351) with `PeoplePage` (Reference #2904 , #2898).
cc: @Pomax @cadecairos @patjouk
