### ISSUE TITLE
 🌡 In-page CTA for alternate newsletters

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2874]
The plan for the Mozfest announcement page (launching April 15)  is to use a BanneredCampaignPage at foundation.mozilla.org/Mozfest. However, this page leverages a petition component and we need to instead offer a newsletter signup. (This would be for the `mozilla-festival` newsletter instead of the default `mozilla-foundation`.)

### Things we need to decide in this ticket:

* Intended use
* Design for this component
* A technical plan for its implementation

### Questions

* Should we build this as a streamfield component, so that we can use it (infrequently) on other pages, or hard-code it into a template (like the petition currently is)?
* If we go down the streamfield route, can we have a streamfield component that injects a snippet? We already have this functioning as a snippet for (discontinued) use on opportunity pages. It feels like migration complications would be mitigated with this approach.
* What is our approach for a template to use this in? If streamfield, do we add a streamfield to the right column of BanneredCampaignPages? If not streamfield, do we add this as an option to that page type after petitions, and expect authors to be reasonable and only use petition OR signup?

@kristinashu @sabrinang for design/use approach to answers.

@mmmavis @Pomax for template/componentization thoughts.

**Comment by kristinashu** [comment]
@sabrinang can you please confirm if these assumptions are right? For April and May the pages will look like this (like misinfo but with email instead of petition):

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1068783/54841240-17351d00-4c8c-11e9-81eb-4ae5301568e7.png">

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1068783/54841255-23b97580-4c8c-11e9-9ddd-139d1f40de5d.png">

From June onward the mozfest will have it's own microsite. Will any of the pages have an email signup on the right hand side, or only in the footer?

**Comment by sabrinang** [comment]
@kristinashu 

Yes, the April-May save the date version looks like the mockup.

Yes, for June onward it will have the new footer redesign so that email signup area would be for the Mozilla Festival newsletter.

I also assume from June-October there won’t be in page sign up component when the CTAs are:
- _Call for Proposals_ because the form had an email field in the form so applicants were notified from that specific email
- _Buy Ticket_ because that was done via ti.to and I believe they joined an email list there (i believe it was the same for signing up to be a volunteer too)

It might be good to consider when they are completing those CTAs, to have the option to sign up for the newsletter too? (I'm unsure if they previously had it)

Yes, after the event is over it would be great to surface the signup component

**Comment by kristinashu** [comment]
Ok thanks Sabrina! Yes, I had just added a comment to your redpen about adding a checkbox for people to also signup for the general email list.

@alanmoo so since the signup will need to be on the main foundation site for a couple months and then eventually also on the microsite (with custom header and footer), does that help influence the streamfield vs template decision??

**Comment by alanmoo** [comment]
> @alanmoo so since the signup will need to be on the main foundation site for a couple months and then eventually also on the microsite (with custom header and footer), does that help influence the streamfield vs template decision??

Not quite. Will the signup always be used in the right column? Will there ever be anything else in that column?

**Comment by kristinashu** [comment]
Yes, when the email signup is present it will always be in the right column (and the footer). No, there will not be anything else in that column. Reminder tho that the email signup won't always be present.

**Comment by alanmoo** [comment]
So what I'm hearing is that we should add the signup component to the BanneredCampaignPage as an optional snippet, in addition to the petition field. That way the creator of those pages can decide which needs to be used without having to create multiple templates. They have the freedom to use both, but we're relying on "don't make it look stupid" principles. (Unless, of course, there's a straightforward way to force a CTA choice that's one or the other, but not both.)

@Pomax Does this sound reasonable?

**Comment by kristinashu** [comment]
This all sounds good.

As discussed at stand and in slack, designers are hoping we could also add a checkbox to sign people up to the general mozilla mailing list when checked. _Note copy isn't final._

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1068783/54960254-1bc23580-4f19-11e9-991a-f1f689323865.png">

I'm running this past @stephaniemcv to get her thoughts. She has also flagged that once the signup form is set, we **need to test to verify a confirm trigger is sent upon a signup.**

**Comment by kristinashu** [comment]
Steph has flagged that she would prefer the MozFest sign up to automatically sign people up to both the mozfest list and the general list to "demote Mozfest to an interest rather than a subscription like we do with the Internet Health Report since both programs don't deliver content year round. It would help to minimize data silos and contribute to general list growth."

Let's see if mozfest team is comfortable with and discus how we should proceed tomorrow.

**Comment by Pomax** [comment]
This feels like overstepping trust a little - there's a big difference between getting mozfest emails, and _all the mozilla emails_ =P

**Comment by kristinashu** [comment]
I agree, we would have to be very clear in the wording as to what they are signing up for. And perhaps the MozFest welcome email could make it easy for them to unsubscribe from the general email.

**Comment by stephaniemcv** [comment]
Yes to being explicit. IHR's sign up is 

"Keep me updated
Receive email about this project and Mozilla."

The user flow is that as soon as you click on the confirmation email to double opt to a subscription you are taken to the preference center, where you can subscribe and unsubscribe to all the things.

**Comment by kristinashu** [comment]
Thank you @stephaniemcv! I really like that copy. 

@sabrinang could you please mock this up and then @alanmoo can open the necessary dev tickets.

**Comment by sabrinang** [comment]
I updated the redpen heading with the body copy. I used `Receive email about Mozilla Festival and Mozilla` in v4 instead since I don't think people refer to the festival as a project? https://redpen.io/npc9df3b0c504bc3b2
<img width="399" alt="Screen Shot 2019-03-26 at 11 23 23 AM" src="https://user-images.githubusercontent.com/2492510/55023284-b07c7000-4fb9-11e9-916c-6ea863e4907e.png">

[v3 for reference](https://redpen.io/npc9df3b0c504bc3b2/3) if you prefer the exact copy
<img width="389" alt="Screen Shot 2019-03-26 at 11 23 11 AM" src="https://user-images.githubusercontent.com/2492510/55023275-ad817f80-4fb9-11e9-8886-fb2c4bcf72a4.png">

**Comment by kristinashu** [comment]
Nice! No need to have the exact same copy so let's go with `Receive email about Mozilla Festival and Mozilla`

@alanmoo design is done.
