### ISSUE TITLE
Update opportunity snippet and embed on BanneredCampaignPage

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#2908]
In order to allow people to sign up for Mozfest emails, we need to update the signup snippet and enable use on the BanneredCampaignPage, below the petition form (though neither will be used at the same time)

![image](https://user-images.githubusercontent.com/1682681/55106652-df701000-50a5-11e9-82ed-68a94ad19f8a.png)

---

**🗒  Design -> Dev Handoff Checklist**

- [x] Design has been finalized
- [x] Link to original design ticket - #2874
- [ ] Link to Redpen
- [ ] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included
- [x] Assets are included
- [ ] Hover state for elements are designed
- [ ] Other states for elements are designed (e.g., error state for form)

**Comment by alanmoo** [comment]
@stephaniemcv As I understand, we should be signing people up for the `mozilla-foundation` newsletter with an "interest" in the festival. It's not entirely clear how this translates to what we submit to Basket. Do we need to check with Pmac?

**Comment by alanmoo** [comment]
@mmmavis I believe the new button styling is part of the work you've been doing, correct?

**Comment by stephaniemcv** [comment]
Yes we should check with Pmac, as I'm not sure on if you're just submitting two slugs mozilla-foundation and mozilla-festival or something else.

**Comment by alanmoo** [comment]
Paging @pmac

**Comment by pmac** [comment]
Basket doesn't really know anything other than what newsletters should be set to True, so if you need for 2 newsletters to be checked then it's probably best to just send `newsletters=mozilla-foundation,mozilla-festival`. They just need to be comma separated.

That said, one alternative is a concept called "newsletter groups" that we can setup on basket. It acts like a newsletter in that it's a single slug, but it can subscribe multiple newsletters at once which are administered centrally via basket. If you'd like one of those so that you can just send "mozilla-festival" and have it also include "mozilla-foundation" I can set that up, and then if it needed to change in future we could do it via the basket admin instead of a code change on your end.

**Comment by alanmoo** [comment]
I think we can handle the comma separated list, but @stephaniemcv does that handle things the way you want?

**Comment by Pomax** [comment]
Reading through our signup component, it looks like all it currently does is send a request to `https://www.mozilla.org/en-US/newsletter/`, so I assume we actually want that switched over to the same SQS post we're using for posting petition-signage-data?

**Comment by pmac** [comment]
Oh, and it would be better if it hit basket directly instead of www.m.o as well if it's going to stay HTTP. We can switch to the queue though if you'd prefer.

**Comment by Pomax** [comment]
The other code we have in place posts data to SQS rather than directly to basket, so ideally we tap back into that but without a "campaign id", "first name", and "last name", but if that gets problematic I may need to ask for some help from either you or @cadecairos to add in a new routing code to post data directly to basket.

**Comment by stephaniemcv** [comment]
@alanmoo Yes, as long as the two newsletter are set to True then it handles things for me.

**Comment by alanmoo** [comment]
@Pomax It seems like this is done, is that correct?
