### ISSUE TITLE
Primary page banner spacing and alignment

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#2935]
Alignment and spacing on primary pages looks a little odd when there is a subnav because the eye has to bounce around so much, so quickly. 

Example from prod:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1068783/55360642-e02fea00-5489-11e9-8fb4-5ef6635f451d.png">

Our sketch comps seems to have more white space above and below the intro title and content, let's come up with exact spacing measures devs should use (both desktop and mobile).

Example from sketch: https://redpen.io/hse1d16b06a0b0cd37
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/1068783/55361092-ff7b4700-548a-11e9-8127-6ed8aba6d41a.png">

We could also explore some alternative alignment/spacing/layout options for the card/heading/subnav.

cc @sabrinang @natalieworth @beccaklam

**Comment by sabrinang** [comment]
This alignment issue also came up in a discussion and I noticed at different breakpoints the grey shadow line would appear to separate the card:
![image](https://user-images.githubusercontent.com/2492510/55919088-75795f80-5ba9-11e9-865a-87467de2fa11.png)

<img width="400" alt="mobile" src="https://user-images.githubusercontent.com/2492510/55919098-7f02c780-5ba9-11e9-9946-f16c4660f484.png">

We should probably be consistent if a line appears but another case to consider alignment when a subnav isn't present

**Comment by beccaklam** [comment]
@kristinashu 
Made some quick designs shifting the card/heading/subnav, you can see them here: https://redpen.io/ev624880673d167424 and I'll paste some quick screen shots. Basically moved things so that all the text aligns but the cut off is still slightly off center to follow a similar style as to what we currently have. It feels more visually interesting than just being centered but the user's gaze no longer has to jump around with the text now being aligned.

## Desktop:
![image](https://user-images.githubusercontent.com/20977376/56060304-74286e00-5d34-11e9-8b11-003f2d845e59.png)

## Tablet:
<img width="770" alt="Screen Shot 2019-04-12 at 3 06 18 PM" src="https://user-images.githubusercontent.com/20977376/56060340-8bfff200-5d34-11e9-8979-6e584582b1ce.png">

**Comment by kristinashu** [comment]
That does look good but what about when the body content is full-width. Example: Pulse component https://foundation.mozilla.org/en/fellowships/meet-our-fellows/ and petition https://redpen.io/yu8e8b248a70cccd4b

**Comment by beccaklam** [comment]
True. Will work on next week!

**Comment by beccaklam** [comment]
Readjusted the design to complement both the full width and narrow width views: https://redpen.io/p/eu7e43fa328483dfb7 @kristinashu

**Comment by kristinashu** [comment]
Looks great! I've just pinged @mmmavis in redpen to see if this would be possible for devs to do?

**Comment by mmmavis** [comment]
@kristinashu thanks for the ping. I don't normally check my redpen notifications 😂 

Feel free to assign me the dev ticket when it's ready. I've got some working code locally already.

**Comment by kristinashu** [comment]
Ok awesome! 

@beccaklam if you're happy with everything then please open up an implementation ticket when you can!

**Comment by beccaklam** [comment]
Closing this and opened implementation ticket here: #3022
