### ISSUE TITLE
retire mofo-bootstrap?

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2972]
Do we even still use it? If we do, what parts of it do we still use?

**Comment by mmmavis** [comment]
I know we still rely on some colour and type overrides but we'll have to do an audit to come up with a complete list.

**Comment by mmmavis** [comment]
Both Foundation site and Pulse still rely on `mofo-bootstrap`... with extra SCSS overrides added to the individual repo as our brand style guide has evolved and not all `mofo-bootstrap` rules were relevant. 

During the Pulse UI refresh last year, we had to manually copy the style overrides from Foundation site repo to Pulse to make sure Pulse aligns with the updated style guide. Since then, for any further updates made to style guide, we have to make the change reflected on both Foundation and Pulse codebase. This is def adds maintenance burden. Although I'm not a fan of maintaining another repo, I think the cleaner way to go might be **updating `mofo-bootstrap` with the new style guide and just let Foundation and Pulse use it**. Thoughts? Ohter suggestions?

/cc @Pomax

**Comment by mmmavis** [comment]
We still use `bootstrap` but we import it as a dependency directly to the project (instead of importing `mofo-bootstrap`).

The work is already done. For details see this [epic](https://github.com/mozilla/foundation.mozilla.org/issues/4542).

Closing this ticket.
