### ISSUE TITLE
Consider Open Sans

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/foundation.mozilla.org#302]
Feedback from the brand team: Mozilla will continue using Open Sans as our official sans with the new brand.

**Comment by hannahkane** [comment]
pending brand update happening Aug 25 :)

@sabrinang @taisdesouzalessa @kristinashu - feel free to offer your opinions if you have them :)

**Comment by gvn** [comment]
So we should replace Nunito Sans with Open Sans?

**Comment by kristinashu** [comment]
Oh the age old question... Brand is saying to use Open Sans but I suspect it's just because they don't know what else to use. I'd hate to update to Open and then they introduce a new font and we have to update again. I think Nunito looks similar enough (but of course nicer) to Open Sans that most people won't notice. Sooo I'm happy to keep it for a while longer but up to @sabrinang and @taisdesouzalessa!

**Comment by taisdesouzalessa** [comment]
Yeah...I am with you @kristinashu because I think Brand is still figuring things out. I wouldn't change it until it gets stable. For now, it seems we are using Zilla for body copy in the "mozilla.org" site? Menus, buttons and links are Open Sans though.
<img width="526" alt="image" src="https://user-images.githubusercontent.com/22157921/31785192-42013364-b4b9-11e7-82bb-85877696e2f9.png">

I would keep Nunito, because it pairs well with Zilla. @sabrinang curious about your thoughts here since you did the font pairing :).

**Comment by kristinashu** [comment]
Let's stick with what we have!
