### ISSUE TITLE
Dark theme .btn-secondary text colour 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3052]
Follow-up for PR https://github.com/mozilla/foundation.mozilla.org/pull/3026

Style guide on prod: https://foundation.mozilla.org/en/style-guide/

@sabrinang @natalieworth 
Currently dark theme `.btn-secondary` 's text **on hover** is set to `black`. Not sure if I interpreted design wrong in the first place - is text colour supposed to be transparent instead (so we can achieve the 'cutoff' effect)?

**Comment by sabrinang** [comment]
Some thoughts on dark theme buttons:

I think the text on dark theme should always be black text to maintain the same contrast ratio to be legible on light blue/white and it will be more predictable and consistent even on other dark background applications.

Similarly for normal buttons, I also see it always being white text to maintain the same contrast on dark blue/black for various light background applications as well. 

The button background being transparent is okay to showcase the colour since the type is consistent but I think for type application since button labels are 16px I think we would bump into more contrast ratio issues but we should test more colours and also think about normal styles as well if we do.

Examples of white text/black text only:
![image](https://user-images.githubusercontent.com/2492510/56604265-6f767c00-65b6-11e9-9be3-ff2e1ef85bde.png)

**Comment by mmmavis** [comment]
@natalieworth what do you think? Are we good with having white/black text instead of "transparent" text?

**Comment by natalieworth** [comment]
@mmmavis @sabrinang Sure, I'm good with that to maintain contrast!

**Comment by mmmavis** [comment]
Oops, I accidentally deleted my previous comment!

> Sure, I'm good with that to maintain contrast! 

@natalieworth awesome! Also as far as I know currently there isn't an easy way to achieve the "transparent" (cutout style) text. So sticking with white/black text will make implementation a lot simpler as well. 😎

**Comment by mmmavis** [comment]
🎉 

Nothing to fix or update here. Closing
