### ISSUE TITLE
Blog: design landing page for /blog or /[tag]

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3165]
Benchmark and mockup:
- /blog landing page
- tag landing page

**Comment by kristinashu** [comment]
@beccaklam can please get some feedback on these https://redpen.io/p/bha12cf7387de4f7e7?

**Comment by kristinashu** [comment]
@alanmoo here are comps for the overview pages. Let me know if you have any thoughts/concerns. 
- I haven't mocked up tablet or mobile since the cards should resize the same as our existing cards.
- Blog will not appear in the main nav until we have more posts (people will only discover /blog if they type it in) 

### Overview
![](https://s3.amazonaws.com/redpen-prod/red-pen-f9907975-3d42-4650-d6f5-40bed074e08c.jpg)

### Tag
![](https://s3.amazonaws.com/redpen-prod/red-pen-a3c5d475-ffd5-4fdb-f184-fba23a93e44c.jpg)

**Comment by alanmoo** [comment]
1. What's the "see more" button do? Lazy load more?
2. Related, am I correct in assuming that the "See all blog posts" button points to `/blog`?
3. My instinct is to make the "blog" page a generic page type that shows the preview of all its children pages, so that we can use it for other page types like an Advocacy campaigns index. Where does the blue text under each entry come from, and how can we reconcile that and author/date with a more generic page type? (The latter half may be a convo for me to have with another dev.)
4. Following the above, my assumption is that the image for each post will be pulled from the "promote" tab of that post. Is that correct? What happens if there's no image? Does it show the same thing that _should_ show with related posts (Mozilla logo on black, centered)?

**Comment by kristinashu** [comment]
> 1. What's the "see more" button do? Lazy load more?

Yes, it loads another 9 posts below. Example https://thewirecutter.com/blog/.

> 2. Related, am I correct in assuming that the "See all blog posts" button points to `/blog`?

Yes.

> 3. My instinct is to make the "blog" page a generic page type that shows the preview of all its children pages, so that we can use it for other page types like an Advocacy campaigns index. Where does the blue text under each entry come from, and how can we reconcile that and author/date with a more generic page type? (The latter half may be a convo for me to have with another dev.)

I like the idea of making it work for other pages types but yes, it would be ideal to be able to customize the cards depending on the page type. 

> 4. Following the above, my assumption is that the image for each post will be pulled from the "promote" tab of that post. Is that correct? What happens if there's no image? Does it show the same thing that _should_ show with related posts (Mozilla logo on black, centered)?

Yes, it should be the same as cards from the related posts.

> 5. For the tag page, I'm guessing we'll use a url like `/blog?tag=misinformation`. With that, it might make more sense to keep the page heading/paragraph, and show "Tag: Misinformation" under it, so we're still relying on the same page type, and then this continues to work with other content types (like Advocacy campaigns) if we want. Thoughts?

Is this what you mean?
![blog copy 2@2x](https://user-images.githubusercontent.com/1068783/60683581-55c2a200-9e4d-11e9-87c2-6dcedada5ef2.jpg)

**Comment by alanmoo** [comment]
Exactly. Any concerns with going for that approach?

Regarding the different types, I believe we could embed a check in the page where, if the card is a blog, we show some extra information.  

It looks like the blue text is a tag, but what happens when a post has multiple tags? (Consider that authors/site editors can add as many tags as they want).

**Comment by kristinashu** [comment]
> Exactly. Any concerns with going for that approach?

No concerns, works for me.

> It looks like the blue text is a tag, but what happens when a post has multiple tags? (Consider that authors/site editors can add as many tags as they want).

Could it just pull the first tag? I think having one 'category' like tag is more useful and valuable to users than a long list of random tags.

**Comment by kristinashu** [comment]
Opened implementation tickets!
