### ISSUE TITLE
MozFest: Pulse Profile listing is too small

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3237]
**Describe the bug**
The photos and spacing is too small and cramped for all pulse profile components. Can we make it bigger?

**To Reproduce**
Here's a page where we use it: https://mozillafestival.mofoprod.net/en/team/wranglers/

**Expected behavior**
Ideally something like what's on the foundation site like https://foundation.mozilla.org/en/fellowships/meet-our-fellows/

cc @kristinashu to triage

**Comment by sabrinang** [comment]
related to https://github.com/mozilla/foundation.mozilla.org/issues/3120

**Comment by kristinashu** [comment]
Yeah we should update this for all our pulse profile component across both foundation site and mozfest.

Here's a comp using the Fellowships directory but the card is based on Sabrina's wireframe.

It would have this layout on desktop if the page is set to "Narrow" and it would also look like this for tablet view.

@mmmavis do you have any concerns with this mockup? @sabrinang since this is a site update it will need an R+ from you. 

https://redpen.io/ge7f4beac4f1723042

![meet-our-fellows@2x](https://user-images.githubusercontent.com/1068783/58359627-3c373f00-7e39-11e9-9d9b-4eef43129fd2.jpg)

**Comment by mmmavis** [comment]
I'm a little confused here. Let's chat on Monday?

Also, if we are making changes to the profile cards we should do https://github.com/mozilla/foundation.mozilla.org/issues/3059 first to fix existing small bugs & to make implementation less complicated.

**Comment by alanmoo** [comment]
I think the challenge that we're running into here has nothing to do with the layout of the cards themselves, and more with the widths of containers vs viewport.

On the Mozfest site, these cards look very narrow because the *template* they're in is 8 columns wide on large screens (`col-lg-8`).

The way the profile listing component is built, it displays two cards horizontally until the *viewport* is below a certain size.

If the component can be used in templates of varying widths, this is an inevitable problem due to current limitations of CSS. It's highly unmaintainable to render the cards at different widths based on their container size. The most reasonable solution is probably to have a "wide" template for Mozfest pages, or at least a "wide content" section of the existing template.

**Comment by gideonthomas** [comment]
Let me know what the verdict is otherwise I will need to change them to image text component (and I really don't want to coz it's a lot of work and unmaintainable)

**Comment by kristinashu** [comment]
Since Alan is doing the quick fix, I've opened a new separate ticket for the longer term solution https://github.com/mozilla/foundation.mozilla.org/issues/3276

**Comment by kristinashu** [comment]
Nvm, Alan's PR is the fix for mozfest site. That new ticket will be for generally improving the card at tablet width.
