### ISSUE TITLE
Update 'Trending Projects' section

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#3252]
***Blocked until Pulse is [updated](url)/ and [design updates to the homepage](https://github.com/mozilla/foundation.mozilla.org/issues/3142) are completed.***

Update 'Trending Now' area on the foundation site to reflect the styling of Pulse.

Current design of 'Trending Now' section on foundation.mozilla.org
<img width="1135" alt="Screen Shot 2019-05-27 at 9 11 28 PM" src="https://user-images.githubusercontent.com/14876567/58450517-06f25180-80c4-11e9-97f8-8c5ebb6b9351.png">

Pulse design:
<img width="1181" alt="Screen Shot 2019-05-27 at 9 13 34 PM" src="https://user-images.githubusercontent.com/14876567/58450571-50db3780-80c4-11e9-97a7-7b7399e32c02.png">

cc @kristinashu I made a ticket for this, but are we going to be changing this section based on the homepage context tic?

**Comment by kristinashu** [comment]
No, the homepage context tic won't affect this since I'm hoping the homepage will pull directly from OG info on a foundation site sub-page (rather than the Pulse component). But the Pulse Project component is used on other pages like https://foundation.mozilla.org/en/advocacy/ so it will still need to be updated. It seems like the only difference is the font style so this ticket could just be about update the heading from h5 to h4 and making sure it works on foundation site (at all screen widths).

**Comment by cadecairos** [comment]
@kristinashu this looks stalled so Iceboxed it. is it still ongoing work?

**Comment by kristinashu** [comment]
Ah let's close this! I think this component will get used less and less now that we have the blog component.
