### ISSUE TITLE
navigation menu disapears on 404 pages

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#3357]
**Describe the bug**
The main menu bar (about, initiative, etc) is not visible on the 404 page. 

**To Reproduce**
Go to https://foundation.mozilla.org/en/sdasd/

**Expected behavior**
I would expect the menu bar to be there too.

**Screenshots**
On review apps:
<img width="1152" alt="Screenshot 2019-07-01 at 10 35 10" src="https://user-images.githubusercontent.com/481052/60422267-ee59e780-9beb-11e9-9f95-d3ec49f9e534.png">
On prod:
<img width="1182" alt="Screenshot 2019-07-01 at 10 38 11" src="https://user-images.githubusercontent.com/481052/60422452-59a3b980-9bec-11e9-80b6-d16113c2fdf9.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Firefox
 - Version: 67.0.4

**Additional context**
I saw this on a review app but it's also visible on prod.

**Comment by Stark-Pramod** [comment]
@patjouk May I give it a try?

**Comment by patjouk** [comment]
Depends on how comfortable you are with Django because I won't have the time to help you on it.

**Comment by Stark-Pramod** [comment]
@patjouk Ok, no problem.

**Comment by alanmoo** [comment]
According to a Slack conversation, Pomax says we can't autogenerate it because the 404 page doesn't get a "page context".

If we can't get a "site context" either (that is, the root page of a site), we may have to hardcode these, but I'd say the first step is to confirm that we don't have access to the top level pages from a 404.

**Comment by cadecairos** [comment]
This 404 page isn't a CMS page and thus doesnt have the chance to get a dynamic nav, Usability wise there's always the back button or the homepage button. 

If this is work that we still want to do in the future, please refile this with up to date information so that it can be put in the correct milestone with up to date estimates.
