### ISSUE TITLE
Add related campaign cards to campaigns template

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3362]
Related ticket: 
- Add cards to blog posts #3162 
- Add tagging to more page types #3173

We want to create dynamic related content cards that will be built into the template campaign pages.

The related content cards will be added by a user defining the tags they want to pull from and related cards themselves will pull image and heading information from OG tags.

# Designs: follow styles from blog template

![related-content@2x](https://user-images.githubusercontent.com/20977376/57811459-47eb7d00-7738-11e9-8cef-1de48f993bfc.jpg)

**Comment by Pomax** [comment]
Do we envision us wanting to do related content cross-content-type? E.g. a campaign with tag "X" showing related content that is a blog post that also uses tag "X"? Or do we want related content to be "the same type" so that campaigns only show related campaigns, blog posts only show related blog posts, etc?

**Comment by kristinashu** [comment]
Closing in lieu of https://github.com/mozilla/foundation.mozilla.org/issues/4011
