### ISSUE TITLE
Rename glyph's classname to something more specific

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#3426]
Consider renaming glyph's classname to something more specific.

---

https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/glyphs.scss

We started this file when Foundation site codebase was small and when we only had a few glyphs. However as our site evolves these predefined glyphs along with their preserved class names (e.g., `twitter`, `email`, etc) and SCSS rules start to make frontend code harder to maintain.

- We often have to make up a not-so-straightforward classname just to escape an element from being automatically attached with a glyph 😦 .
- Or we have to write more custom SCSS override to hide glyph that is automatically added via the special class name (e.g., `twitter`) 😨 .

I'll update this ticket with references in the codebase once I find them.

/cc @youriwims feel free to share your frustration / code examples here as well

**Comment by youriwims** [comment]
Yessss, this would be awesome! 🙌 Currently, some elements in the profile-edit forms are getting glyphs added to them because of the `.linkedin` classname added via https://github.com/mozilla/network-pulse/pull/1115/files#diff-3844b3fc785c213b24d3f9cdd6964f07L56 (also, twitter & github).

Because of this, I had to do an override [here](https://github.com/mozilla/network-pulse/pull/1115/files#diff-eb08e6acea0eb427689738844d24f92bR1) just to rectify that 👿.

**Comment by gideonthomas** [comment]
@mmmavis think you'll be able to get this done in the current sprint?

**Comment by mmmavis** [comment]
@youriwims and I have met and decided to change the current glyph class from "platform" to "platform-glyph". e.g., `twitter` to `twitter-glyph`

**Comment by mmmavis** [comment]
Need to update Pulse as well before we can close this ticket.

**Comment by mmmavis** [comment]
Done!
