### ISSUE TITLE
Replace all /en links

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/foundation.mozilla.org#3475]
Find all /en links in the repo and remove the locale part of the link

**Comment by Patil2099** [comment]
Can I work on this issue? @gideonthomas

**Comment by gideonthomas** [comment]
@alanmoo ^

**Comment by alanmoo** [comment]
@Patil2099 You're welcome to open a PR, but this is getting added to our upcoming sprint starting on Tuesday. If you haven't opened a PR by then, someone on the core team will likely start to work on it.

**Comment by Patil2099** [comment]
suppose there is a link abc.com/en/sometext/locale so I have to remove the locale string?to make it like this?
abc.com/en/sometext
@alanmoo

**Comment by alanmoo** [comment]
`/en` is the locale. `foundation.mozilla.org/en/sometext/foo` becomes `foundation.mozilla.org/sometext/foo`. But only for links within the site; There are other cases like tests where things should remain as-is. It's a bit of a judgement call based on the instance.

**Comment by Patil2099** [comment]
Okay, I will try to do it till monday and make a PR.
@alanmoo

**Comment by Patil2099** [comment]
One more thing do I have to make changes to .js file also or just the HTML ? and what about the places where there is en-US?
@alanmoo

**Comment by Pomax** [comment]
AWesome work @Patil2099, @mmmavis is going to have a look at the PR and let you know if we're good to land or if there's anything left to fix before we merge it!

**Comment by Pomax** [comment]
After investigating the original underlying error, it turns out that rather than removing /en/ we need to replace each instance with the user's current locale, based on their Django sessions, which is a fairly complicated bit of work.

As we don't currently have the capacity to walk contributors through the process to make that happen, we'll have to close this PR and do this work in-house instead.

Thank you so much for being willing to help out, and apologies that this turned out far more complicated than initially thought =(

**Comment by Pomax** [comment]
blocked by https://github.com/mozilla/foundation.mozilla.org/pull/3501

**Comment by Pomax** [comment]
Reopening this issue: due to prod push problems, the PR associated with this issue had to be backed out of master.

The associated PR's branch still exists as https://github.com/mozilla/foundation.mozilla.org/tree/issue-3475-en-links but relied on code that is also getting backed out, and so will quite likely require additional work.

**Comment by mmmavis** [comment]
@Pomax the above link doesn't work for me 😬

**Comment by mmmavis** [comment]
Also - should I revert my PR #3545 ?

**Comment by mmmavis** [comment]
@Pomax can you suggest what we should do to close this ticket?
