### ISSUE TITLE
Add "review date" to PNI product model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#3572]
So that we can filter by products reviewed in different months/years in the guide, we should add a field to the model allowing us to indicate review month and year. I don't have a particular opinion on format (string vs an actual date), so I'll leave it to the implementer to decide.

**Comment by xmatthewx** [comment]
> string vs an actual date

The date should be a date, not a string, to enable sorting and filtering later. 

And, we should allow author to select the date, rather than automate it. This allows us to fix a typo on a review from last year, without suggesting to readers that we've reconfirmed all the technical details this year.

**Comment by mmmavis** [comment]
Is this `review date` going to be a required or optional field?

**Comment by alanmoo** [comment]
My instinct is to make it required, and add a default of November 2018. Then we'll have to manually change the Valentine's items but that's not too many.

**Comment by mmmavis** [comment]
All `year`, `month`, and `day` are required arguments for Python's `date` object type, so I'm making `November 1, 2019` as the default. If we really wanna have just `year` and `month` we could use tuple instead of `date` but I think it's less straightforward and will increase complexity in the future when we implement features like sorting and filtering.

**Comment by alanmoo** [comment]
Good, though how about November 2018 instead so that products that exist get that date? Then another migration so new ones get the current date?

**Comment by mmmavis** [comment]
@alanmoo 

> Good, though how about November 2018 instead so that products that exist get that date? Then another migration so new ones get the current date?

Does this require landing the PR to prod first (with default review date `November 1, 2019`) & file a follow-up PR to change the default to current date? If so, I'll file a separate ticket.

**Comment by Pomax** [comment]
No, you just need two migrations: one that sets a default date, so when it runs, all existing records get updated, and then a second migration where it swaps the field to "now". We did the same thing in network-pulse-api here: https://github.com/mozilla/network-pulse-api/commit/37b9f0d1cde8f8262ff54a1cba0b0ef62b41b928
