### ISSUE TITLE
Add dropdown styles to style guide

### ISSUE THREAD

**Issue by youriwims** [mozilla/foundation.mozilla.org#3645]
Since we're using the dropdown in the language switcher (#2681, #3613) and now in localized petitions and signups (#3628), this would be a great time to unify styles and add to the style guide :)

cc @kristinashu @mmmavis @sabrinang

**Comment by youriwims** [comment]
@kristinashu has there been any more thought/conversation on this?

**Comment by kristinashu** [comment]
First we will need to audit the site to see where all the drop downs are. Then style wise we would follow what Sabrina did for the footer but _might_ need to different height options and will need a regular and a dark version. 

Unfortunately designers don't have the capacity to do this right now but you could start by auditing the site (just screen caps of all the possible places a drop down shows up).

**Comment by youriwims** [comment]
As far as I can tell, these are the only dropdowns currently on foundation.mozilla.org. This makes it a total of 3 including the one that will be added to signup snippets.

<img width="473" alt="Screen Shot 2019-09-18 at 5 28 51 PM" src="https://user-images.githubusercontent.com/36484608/65187597-46a9c400-da3a-11e9-8ba5-f5b893fb14a8.png">
<img width="381" alt="Screen Shot 2019-09-18 at 5 30 37 PM" src="https://user-images.githubusercontent.com/36484608/65187598-47425a80-da3a-11e9-8809-3615409df16f.png">

**Comment by kristinashu** [comment]
Thank you @youriwims! Yay I think @sabrinang has some time to work on this!

So guidelines are that the design is settled we just need to make it official in Abstract so that Youri can then add it to the style guide.

We are going to use the style from the footer dropdown (sticking to the default open styling) and are focusing on foundation site only.

I think we need 4 things:
- shorter dropdown (like in the footer, nav, [newsletter snippet](https://foundation.mozilla.org/en/newsletter/))
- taller dropdown (like the petition snippet) 
- and then the regular colors (white background) plus darkmode (black background) colors

**Comment by sabrinang** [comment]
I created field symbols for dropdown styles and updated the Style Guide.sketch file via Abstract:

<img width="835" alt="Screen Shot 2019-09-20 at 2 50 43 PM" src="https://user-images.githubusercontent.com/2492510/65360890-7d0c4e00-dbb6-11e9-9789-6d4e6109598e.png">

Any name suggestions would be great to work with the system? I added some as suggestions in sketch following the -large and dark-theme conventions but can remove -field if it is repetitive 

@kristinashu design review?

**Comment by kristinashu** [comment]
Perfect, thank you Sabs! R+

Youri, let us know if you need anything else!

**Comment by youriwims** [comment]
Awesome, thanks so much @kristinashu & @sabrinang! btw, I think dropdown sans field works just fine 😉
