### ISSUE TITLE
Implement Fo'Mo Nav onto Privacy Not Included

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3675]
Change Privacy Not Included's Nav (just the navigation bar, not the menu style) to match Fo'Mo.

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket: #3614 
- [x] Link to Redpen: https://redpen.io/rhd7b2c19478a1fa67
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included

![Home@2x](https://user-images.githubusercontent.com/20977376/65270691-add28180-dae9-11e9-959e-2c44639277f0.jpg)

**Comment by alanmoo** [comment]
Consider this in relation to #3677

**Comment by kristinashu** [comment]
Requirements:
- [ ] Nav height should match that of foundation site nav
- [ ] Remove PNI share buttons from nav
- [ ] Add donate button to PNI (it should function the same as on foundation site)
- [ ] Add newsletter sign up button to PNI nav (it should function the same as on foundation site)
- [ ] Mozilla logo and PNI title should remain the same as they are currently on PNI
- [ ] Non-sticky main nav and sticky secondary nav on PNI should remain the same as they are currently on PNI

**Comment by Pomax** [comment]
Bearing [the evaluation of folding PNI into wagtail](https://github.com/mozilla/foundation.mozilla.org/issues/3677) in mind, I'll be seeing if it makes sense to base the PNI template off of the main fo'mo template. If that turns out to be relatively easy, that would be a great first step on the road to making PNI a true Wagtail setup..

**Comment by Pomax** [comment]
Donate-wise, is there a different `utm` argument that should be used for donates from PNI rather than the main foundation site? /cc @alanmoo @WillatMozFdn

**Comment by WillatMozFdn** [comment]
Yes please.  To be consistent with tracking from other properties, the utm parameters for PNI should look something like this:

utm_source=foundation.mozilla.org&utm_medium=referral&utm_campaign=2019PNI&utm_content=[this is optional, use it to track links in specific places within PNI if you want]  

The broad guidance for all this is here: https://docs.google.com/document/d/1Z1UovTq-KpLNJtYBhbKuKKGPczWPpvPsogYRUFrrFPQ/edit ... so you could always roll your own if you need (and I'm not available).

This system is overdue for a full revamp (I'm still working on what was passed down to me) but that can't happen until early 2020 ... both due to time constraints, and the fact that our 2019 reporting will be WAY easier if we don't have to manually meld two different tracking systems.

**Comment by Pomax** [comment]
I meant more the `utm_source`, which is already foundation.mozilla.org, but since PNI is sort of "its own thing" with its own following I was thinking you might have a separate stats gathering going on for `utm_source=privacynotincluded` or the like.

**Comment by WillatMozFdn** [comment]
yeah, there's an argument to be made that PNI (and IHR for that matter) could/should be their own sources, rather than campaigns, but a) in the past they haven't been, and b) I don't want to introduce new wrinkles now that would complicate our 2019 year-end analysis.  Definitely a good conversation for January though!
