### ISSUE TITLE
Featured post on /blog

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#3693]
Add the ability to feature two blog posts at the top of /blog.

Comp:
![blog w featured copy@2x](https://user-images.githubusercontent.com/1068783/65466960-12a51900-de15-11e9-86ec-22d306e39165.jpg)

Style of the thumbnail should be the same as on https://foundation.mozilla.org/
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1068783/65467034-4aac5c00-de15-11e9-9f4e-e780c67abaa0.png">

Which blogs to feature should be selected on the /blog cms page:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1068783/65467236-d0c8a280-de15-11e9-81bb-5821d6cf1851.png">

**Comment by ShivamRawat0l** [comment]
I would like to work on this issue.

**Comment by alanmoo** [comment]
@kristinashu The most straightforward implementation of this would impact all pages that use the "index" template; is that ok?

**Comment by kristinashu** [comment]
@alanmoo which other pages uses the "index" template?

**Comment by alanmoo** [comment]
Looks like it might just be`/campaigns` right now, which we don't actually make much use of. So I suspect this is fine. But I also suspect there will be a point at which we want to use the index template for other things too.

**Comment by kristinashu** [comment]
Ok got it. That sounds good, any page that is just a bunch of cards would benefit from a way to highlight a couple of the most important ones.

**Comment by Pomax** [comment]
After investigating, it turns out that it's really hard to add something that lets you pick (one or more) "child page(s)", which is what we'd want to be able to do here. In order to add a Page Chooser (like for the homepage's featured blogs) the IndexPages would have to know "the" type of all its children, but there is no such thing: those could be blogs, or campaigns, or any other page type that we don't know before hand.

Some options:

1. Set a list of permitted page types that can be featured by an IndexPage. This would allow a Page Chooser in the cms, but you _could_ pick to feature a campaign page on the blog index that way. This feels like a trivial problem ("don't pick a a campaign page when you're trying to feature a blog page") but it's something to bear in mind.
2. Give every page model a `featured` option that can be toggled, and have the index page pick two of its children that have that flag set. This feels far less clean, because there's no simple UI in place for making sure only two child pages have that flag set. It would be quite the chore to make sure that the right number of pages have that option checked off.
3. Rather than explicitly feature posts, we always render "the more recent X children" and render the rest in the normal paginated fashion. Depending on what the motivation for featuring is, this option might very well not even be an option at all.

**Comment by mmmavis** [comment]
> 4. We make the IndexPage an abstract concept, with concrete BlogIndexPage, CampaignIndexPage, etc. subclasses. Then we'd be able to fairly cleanly add Page Choosing to each IndexPage "flavour", but this would certainly be the most work to get right, and would require swapping the new page model for the old page model in the CMS (so that rather than an IndexPage, the blog index would be a BlogIndexPage). In its defense, this would probably be the cleanest and most future-proof approach.

I would vote for option 4 for better UX and cleaner implementation.

**Comment by kristinashu** [comment]
Yes, sounds like option 4 is the way to go. I think it's worth noting that I don't foresee us using Index pages anywhere other than /blog.

**Comment by xmatthewx** [comment]
@kristinashu - just to clarify, this would be useful for blog category index pages too, true? Like mozfest or  [/blog/category/advocacy/](https://foundation.mozilla.org/en/blog/category/advocacy/)

Option 4 sounds like the better option. I'm curious how big a lift iingt would be (know we just need this for the blog index template). A single sprint engineering-wise? One engineer or two?

Option 2 isn't ideal, but it sounds much easier to build. It offers less control since Jen/Kevin would mark a post as featured, and the template would just grab the most recent featured, with no chance for Jen/Kevin to order them. But, I do wonder if most of the time that would match what they would pick anyhow. (Regarding the concern about having the right number, it seems like we could plan to display two, but have a fallback when there's only 1 or zero.)

**Comment by kristinashu** [comment]
> @kristinashu - just to clarify, this would be useful for blog category index pages too, true? Like mozfest or /blog/category/advocacy/

Ah yes that's right, we would use it on /blog/category/[name] as well.

**Comment by Pomax** [comment]
realistically, 8 should be the upper limit for single issues. 13 should be a signal to file separate tickets, too.

**Comment by kristinashu** [comment]
> realistically, 8 should be the upper limit for single issues. 13 should be a signal to file separate tickets, too.

Ok, I've added "(consider opening separate tickets)" after 13 in [our sprint planning doc](https://docs.google.com/document/d/14cAFcl05VmyW1ZnA0Dj6MYY-FU6IjpDzPPcAdjUeuTs/edit#heading=h.r6rmivtnonoj).

@Pomax did you add the `3` estimate to this ticket? If so then @mmmavis do you agree? If if so then I think we should go ahead with Option 4!

**Comment by mmmavis** [comment]
@kristinashu I think Alan estimated this ticket to be `3` but he did it months ago. 

This looks like a multi-step ticket to me. If I'm the person doing it, it would be closer to a `13` ticket since I don't have much experience with Django and will have to dedicate time reading docs & trials and errors 😂 .

**Comment by Pomax** [comment]
I did not - option 4 is absolutely in between an 8 and 13 though.

**Comment by kristinashu** [comment]
Ah ok got it! Could one of you please open up the necessary ticket(s) and then close this one?

**Comment by Pomax** [comment]
I'll split this up into specific implementation issues first thing tomorrow.

**Comment by Pomax** [comment]
I've filed implementation issues https://github.com/mozilla/foundation.mozilla.org/issues/4232, https://github.com/mozilla/foundation.mozilla.org/issues/4233, and https://github.com/mozilla/foundation.mozilla.org/issues/4234

**Comment by kristinashu** [comment]
I believe @Pomax has done all the prep work for this and now the page is ready for the front-end work needed to be able to show featured posts at the top of /blog.

I'm going to re-open this ticket for that work but please a new ticket or multiple tickets if needed.

**Comment by cadecairos** [comment]
@kristinashu now that the Abstract model work landed, can we close and refile this issue with the specifics for implementing the featured posts?

**Comment by kristinashu** [comment]
Yup. It will be the same as the first comment in this issue, is that enough?

**Comment by kristinashu** [comment]
Opened here https://github.com/mozilla/foundation.mozilla.org/issues/4624
