### ISSUE TITLE
PNI Product Page Improvements

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#3904]
Based on [user testing](https://docs.google.com/spreadsheets/d/1QAUZ4KHlygLbz4oLGt1zXoFtyPPEHfdXkfrE3ISwyq8/edit?usp=sharing) conducted at MozFest, @taisdesouzalessa  and I have distilled our [findings](https://docs.google.com/spreadsheets/d/1Si6MnJWz3PZFIKp_pchkATkv50xpNlB_s0VSjcb8ZD0/edit?usp=sharing) into the following issues need attention on PNI's product pages:

### 1. Clarify "Minimum Security Standards" section
_(Note: "Minimum Security Standards" is hereafter known as "MSS")_

- [x] Clarify relationship between MSS badge and the star rating
- [x] Ask content to provide help text for reach category (e.g. one sentence explaining what "Manages vulnerabilities" means)
- [x] Brainstorm ways to further highlight the MSS badge/stars?

### 2. Our research is too low on the page and users want that information
- [x] Rethink position of the creep-o-meter. Can it be sticky at the bottom of the page? Side of the page?

_(Note: changing creep-o-meter position may negate the following ...)_
- [ ] Can we reduce height of the product image?
- [ ] Can we shorten the product blurbs?

### 3. Users are not hitting the submit button on the creep-o-meter
- [ ] Retest in usertesting.com to see if bug is reproducible and not just a result of the busy environment of MozFest
- [ ] Should submission be automatic after user has clicked all necessary buttons?

### 4. Change email interstitial copy and opacity
- [x] Users are stopping at PNI's email interstitial and not clicking through to see results. We're hoping that changing the copy (to allude to the results on the next page) and lowering the opacity of the interstitial background will help fix this problem. [Copy from Jen](https://docs.google.com/document/d/1MhA6TSJ-Gg8FW6q5y5hhTJ_UsfnV0T6ablZwhkwG0Vg/edit#)

### 4. Add labels to Recommended products
- [x] A senior emailed Jen and kindly asked for labels to be added to the Recommended products images as _"Seniors (and others ?) may not always connect with a picture as being this or that or A,  B,  C or D."_

cc: @taisdesouzalessa @kristinashu

**Comment by beccaklam** [comment]
Becca Ricks has provided some context for the MSS categories: 

> Encryption
> Is your data secured with encryption?
> 
> Security updates
> Does it get regular software/firmware updates?
> 
> Strong password
> Do you have to create a strong password (for remote access)?
> 
> Manages vulnerabilities
> Is there a system in place for managing security vulnerabilities?
> 
> Privacy policy
> Does it have a privacy policy?
>

**Comment by beccaklam** [comment]
First draft of email interstitial work: https://redpen.io/p/yh131112029e4f1b2e

**Comment by beccaklam** [comment]
Okay! So I spent _way_ too much time in Invision playing with this but I have prototypes for review! These prototypes include:
- the redesigned product page itself (for a static version, see this [redpen](https://redpen.io/p/yh131112029e4f1b2e))
- new creep-o-meter placement options (including how it would animate in, though that still needs some work I think)
- new email signup interstitial flow

I hope the prototype is intuitive enough for you to use ... If not, just click the page if you're not sure where things are actionable and a blue box(es) should flash. @taisdesouzalessa @kristinashu 

## Product Page Updates!

**Mobile**
[Option 1](https://mozilla.invisionapp.com/share/8VUZ1UPHBX7#/394747232_-M-_Product_Page_2_Copy_8)
[Option 2](https://mozilla.invisionapp.com/share/8VUZ1UPHBX7#/394635762_-M-_Product_Page_2_Copy_9)
[Option 3](https://mozilla.invisionapp.com/share/8VUZ1UPHBX7#/394744683_-M-_Product_Page_2_Copy_10)

**Desktop**
[Option 1](https://mozilla.invisionapp.com/share/ZSUZ1VS9X83#/394623712_Desktop_Product_Page_2_Copy_9)
[Option 2](https://mozilla.invisionapp.com/share/ZSUZ1VS9X83#/394624919_Desktop_Product_Page_2_Copy_11)
[Option 3](https://mozilla.invisionapp.com/share/ZSUZ1VS9X83#/394632412_Desktop_Product_Page_2_Copy_14)

**Comment by caltrider** [comment]
Because the creepometer is such an important part of how the guide is presented to the world and how the media and companies cover the guide, I feel like the desktop option #1 is by far the best. I'm not sure about the mobile options as they all seem to hide it more than I would like to see it hidden.

As for moving the "what could happen" section up...I'm not sure I love it after all. I think I like the bookends of product info at the top, research in the middle, and summary at the end. 

My thoughts @beccaklam

**Comment by beccaklam** [comment]
Thanks for your thoughts @caltrider! The desktop options correspond to the mobile ones. So Option 1 Mobile is what Option 1 Desktop would look like since we can't have the creep-o-meter sticky next to the content on such a small screen.

**Comment by taisdesouzalessa** [comment]
@beccaklam first of all, amazing job on including the user testing insights on these proposals. So great to see those prototypes :). I love the solutions you proposed.

My favorite is the Option 2, I think it is a good balance between having the creepometer constantly present in the page + the focus needed for such a content-heavy page. I find that in Option 1 the creepometer competes with the main content of the page.

Now if you want the creepometer expanded in the page I feel option 3 may be a good solution. Because if the user misses the button they will see it at the main page and the voting system seems to be in the right spot (when users would be ready to vote after taking a look at the info we are presenting to them). Very aligned to our research insights.

**Comment by caltrider** [comment]
> My favorite is the Option 2, I think it is a good balance between having the creepometer constantly present in the page + the focus needed for such a content-heavy page. I find that in Option 1 the creepometer competes with the main content of the page.

Fair point here @taisdesouzalessa . I will say that having people interact with the creepometer is a more important goal for us than having people read all the content. Keeping the creepometer front and center feels like a priority for us on these pages.

**Comment by kristinashu** [comment]
Sweet prototypes! I love the round button on Option 2 desktop. It stands out just the right amount and looks playful and I want to click it to see what will happen. You could even animate through all the faces once and then end and stay on the question mark.

But I also like how Option 3 desktop because it keeps the creep-o-meter on the page, but lower down. And I really like the Option 3 mobile version of this because the scroll down feels much less committal. 

I hate to say it do you think they could be Frankenstein-ed together or would that be terrible?!

**Comment by kristinashu** [comment]
Oh and for the interstitial, I find the transparent overlay makes things really hard to read and too busy looking, any other ideas? 

We're talking about showing the email sign up later and less often https://github.com/mozilla/foundation.mozilla.org/issues/3943. Is that enough?

**Comment by beccaklam** [comment]
[Draft 2 designs](https://docs.google.com/document/d/1x6cNJMMG32ZeMmLn2Y93ibCcYBDecvDqoGo0-e5iuIo/edit?usp=sharing)
[Meeting with Jen Feedback](https://docs.google.com/document/d/1mwPebGK1IhPoEdlmmvNtL5eAJCzhYk1WPu8smSZBBig/edit?usp=sharing)

**Comment by kristinashu** [comment]
Designs are look sweet and user testing is about to start! Once testing is done we will review the results https://github.com/mozilla/foundation.mozilla.org/issues/4013 and decide what to do. I've separated this into three design tickets for next sprint: 

PNI product page: finalize creep-o-meter #4015
PNI product page: finalize MMS section #4016
PNI product page: misc updates #4017

Rebecca, could you please double check them and then I think this one is good to close!

**Comment by beccaklam** [comment]
Those tickets look good to me! Closing this, thanks @kristinashu !
