### ISSUE TITLE
PNI home: clarify creepiness

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4037]
Based on updates in #3904 and user testing results in #4013. Let's decide if we should go ahead and emphasize the creep-o-meter or add sections.

**Comment by kristinashu** [comment]
@beccaklam to explore designs more but this is lower priority.

**Comment by beccaklam** [comment]
Sections from previous exploration:
![Homepage@2x](https://user-images.githubusercontent.com/20977376/71294260-fcd8be80-2345-11ea-8c42-5afa3fad7f04.jpg)

**Comment by beccaklam** [comment]
I'm thinking we could combine sections with some added animations to the face. So every time the face changes we could:
a) Instead of having the text changed immediately, have it type in and out like [this](https://codepen.io/Zhouzi/pen/JoRazP)
b) Have the face "flash", perhaps by an enlargement/spring animation like [this](https://codepen.io/shaun/pen/vERGEN) 
   - [Alternative spring animation](https://codepen.io/valhead/pen/yXYYdm)
   - [Alternative spring animation 2](https://codepen.io/valhead/pen/Lbzywb)

**Comment by kristinashu** [comment]
Will look at this as part of - PNI: homepage sketches #5153
