### ISSUE TITLE
TypeError: '<' not supported between instances of 'datetime.datetime' and 'NoneType'

### ISSUE THREAD

**Issue by patjouk** [mozilla/foundation.mozilla.org#4046]
https://sentry.prod.mozaws.net/operations/foundation-site-prod/issues/6835288/

```
TypeError: '<' not supported between instances of 'datetime.datetime' and 'NoneType'
(3 additional frame(s) were not displayed)
...
  File "contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "wagtail/core/views.py", line 24, in serve
    return page.serve(request, *args, **kwargs)
  File "wagtail/core/models.py", line 721, in serve
    self.get_context(request, *args, **kwargs)
  File "networkapi/wagtailpages/models.py", line 902, in get_context
    context['related_posts'] = get_content_related_by_tag(self)
  File "networkapi/wagtailpages/utils.py", line 163, in get_content_related_by_tag
    reverse=True
```

**Comment by Pomax** [comment]
Debug code landed so that instead of a server error 500, we get the error sent to Sentry while the page itself renders, just without running the sort call.

One thought is that this might be from finding a related post that's still in draft, without ever having been published. In that case, there might not be a `first_published_at` / `last_published_at` value for the sorting lambda to hook into.

**Comment by Pomax** [comment]
This error has not shown up for a week, so this feels like it got fixed and if it does happen again, sentry will tell us.
