### ISSUE TITLE
Discuss adding GIFs to Wagtail

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4089]
Staff often request and reference cool iterative sites they would like us to make. We of course can't build a unique site every time they ask but GIFs are great way to create the illusion that a site is "special" and more exciting then just a static page. 

@alanmoo could we add functionality to wagtail to allow us to upload GIFs? What are the concerns in adding this? And are there restrictions we could add to mitigate these concerns? 

A few examples that have come up recently:
- https://glitch.com/culture/introducing-glimmer-call-for-writers/
- Lotta and Kevin asked for something like this http://www.florencegame.com/
- IHR team originally wanted a crazy iterative clickable piece for this article https://foundation.mozilla.org/en/blog/5-key-decisions-every-smart-device. We obviously couldn't do that so they suggested some GIFs (example: blinking lights in the illustration) but in the end they got neither. Although it still looks good, GIFs would make it a little more exciting.
- Kaili and Becca linked to this article the other day https://www.bloomberg.com/news/features/2019-12-11/silicon-valley-got-millions-to-let-siri-and-alexa-listen-in
- Our contract writer shared this as a way to help explain instructions https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-privacy-tips.html

cc @beccaklam @natalieworth @taisdesouzalessa

**Comment by alanmoo** [comment]
Other than the performance concern, here's some food for thought on motion in web pages: https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/

**Comment by alanmoo** [comment]
So, there are three main concerns for this from a technical standpoint:

1.) Performance. We want to make sure people aren't hitting pages that are many MB in size.
2.) We need to build this with accessibility in mind, both from a "reduced motion" standpoint and ensuring that people using screen readers can still understand the content.
3.) ROI. What metrics are we trying to improve with this? Because increased page size and motion alongside text have a decent possibility of actually increasing our bounce rate.
