### ISSUE TITLE
[Bug on PNI staging] Some images are not showing

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4104]
**Describe the bug**
Some images on PNI staging aren't showing.

**To Reproduce**
1. Go to https://foundation.mofostaging.net/en/privacynotincluded/ and browse around

**Expected behavior**
All images should show.

**Screenshots**
<img src="https://user-images.githubusercontent.com/2896608/71862685-8959df80-30af-11ea-9ae8-1acd9f5eb40d.png" width=500>

**Additional context**
Review apps and production site don't have this issue.

**Comment by mmmavis** [comment]
Screencap from Slack convo with @cadecairos 

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2896608/71862921-2ae13100-30b0-11ea-9643-75c068998f33.png">

**Comment by patjouk** [comment]
Looks like something changed and the images on prod are not uploaded to `foundationsite/buyersguide` anymore, but just in the home dir. The issue is that the auto mapping feature for staging is only activated for that directory. I'll check tomorrow what's happening but it's probably a change in the cloudinary python lib (can be reproduced on staging).

**Comment by patjouk** [comment]
Transfer done: images are back on staging 🎉

**Comment by mmmavis** [comment]
Awesome! Thanks @patjouk :D
