### ISSUE TITLE
[Component] Option to set height and hide scrollbar for iFrame 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4115]
**Request**
- Add option to set the height of the embedded iFrame window
- ~~Add checkbox to give option to show/hide scroll bar~~ Crossed out because we shouldn't and can't do it (see thread below)

![image](https://user-images.githubusercontent.com/2492510/72028481-825dd900-3237-11ea-9aaf-bd4b566fd1c9.png)

**Example:** Currently the fixed height makes it hard to read/scan the content inside and the scroll bar makes it look busy and obvious it's separate from the other elements on the page (it would look more integrated and cleaner without)

![image](https://user-images.githubusercontent.com/2492510/72028543-cd77ec00-3237-11ea-9620-ba77b1421673.png)

**Comment by mmmavis** [comment]
> Add checkbox to give option to show/hide scroll bar

By hiding the scrollbar did you mean hiding the bar from UI while keeping the scrolling functionality? Or disable scrolling at all?

**Comment by Pomax** [comment]
@sabrinang @mmmavis is this issue still active?

**Comment by kristinashu** [comment]
Two more use cases for iFrames are:
- TypeForm for story collection https://github.com/MozillaFoundation/Design/issues/512
- MozFest ticket sales ([deck](https://docs.google.com/presentation/d/17mT-90dhKfZAN2NTE4c81TaFXFn1rcxagZsNrT7BwJY/edit#slide=id.g7f16bed56a_0_8)) cc @marcwalsh 

@mmmavis I think what Sabrina means is that if we can control the height of the iFrame then hopefully there won't be a need for the scroll bar since everything will be visible. But we should keep the scroll bar as backup in case not all content is visible on all devices and screen sizes/widths.

**Comment by marcwalsh** [comment]
@kristinashu - I've opened https://github.com/MozillaFoundation/mofo-devops-private/issues/332 to get the ticketing domain added to the list of allowed websites.

**Comment by xmatthewx** [comment]
@mmmavis - I think the question (I might be mistaken) is whether we can have the iframe inherent the height of the contents so that the auto scroll is never triggered in the iframe, and users can just scroll the page.

**Comment by mmmavis** [comment]
We can make it so that on the initial load, `<iframe>` content is shown at its full height (so scrollbar won't be presented). However, if user interacts with something in the iframe and changes the "length" of the embedded content, iframe won't be able to dynamically adjust its height to match the newly updated content. For example, if the new embeded content becomes 300px shorter, we will end up having 300px white space on our page. Or if the new content is 200px longer, a scrollbar will appear in the iframe.

**Comment by marcwalsh** [comment]
@xmatthewx @mmmavis - There is a _**very**_ rough example of the ticketing iFrame on [MozFest Staging](https://mozillafestival.mofostaging.net/en/tickets-test-nutickets/) in case this helps at all.

**Comment by Pomax** [comment]
We can certainly add a height to the iframe component, but there is no way to prevent that scrollbar: iframe content is completely inaccessible to the page it's used on, due to the browser security model, so there is no way for us to turn off the scrollbar inside the iframe if the height we pick is less than the actual height of the iframe's page content.

**Comment by kristinashu** [comment]
@Pomax @mmmavis @sabrinang does this sound correct?

Since Wagtail can not automatically scale the iFrame height, the best option is for staff to be able to manually type in the height of the iFrame.

It won't be perfect because the iFrame content will change depending on devices and screen sizes but it is better than the fixed height it is set at right now.

For the scroll bar, if the iFrame height was tall enough for the content then the scroll bar will not appear. But if the content is longer than the iFrame than it will appear. If so, then this is ok.

**Comment by mmmavis** [comment]
@kristinashu I can work on this ticket this sprint if the work is still required. I've updated the ticket description (crossing out "making scrollbar optional" because we shouldn't do it and can't do it either due to the reasons above).

**Comment by kristinashu** [comment]
It would still be great to have this! cc @benhohner in case he has any new ideas for tackling this.

**Comment by benhohner** [comment]
@kristinashu, not too much I can add to this convo. 

There's no way to set the height or scroll bar of an iframe on an external domain unless you also own the external domain. The best option I can think of is to add a width and height field to the iframe embed component in Wagtail and let people manually finagle it until the embed fits. Creating a large button and linking off to the external site is also always an option, though it's debatable whether it's better or worse for UX.

Some sites will provide a JavaScript embed that auto-resizes the iframe or allows a widget to be loaded without an iframe, but that requires trusting an unknown site, requiring you to inherit all the security vulnerabilities of the unknown site.
