### ISSUE TITLE
[Thimble] redirecting traffic from Thimble 

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4138]
### **Context:**
Since December 16th we have been receiving a considerable amount of traffic to our site via "https://foundation.mozilla.org/en/artifacts/thimble/"
<img width="507" alt="image" src="https://user-images.githubusercontent.com/22157921/72548066-cad25380-3842-11ea-8a0f-42ab2904a462.png">
The peak was achieved on Dec 17, 2019 with 13,335 pageviews and the most recent data we have (Jan 15, 2020) shows 1,778 pageviews.

Majority of traffic seems to be coming from India, some from United States:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/22157921/72549091-ec343f00-3844-11ea-9bd3-a20512cd0330.png">

During Jan, 2020 we had 18K sessions in "https://foundation.mozilla.org/en/artifacts/thimble/" and 16K dropoffs (88.8% dropoffs).
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/22157921/72548363-5d72f280-3843-11ea-9286-8c38208601e2.png">

### **Opportunity:**
Is there anything we could do to redirect this traffic to our other initiatives since we don't have Thimble anymore? Is there any other areas that you think this audience would be interested in?
If so, what are they and how we could modify the current "https://foundation.mozilla.org/en/artifacts/thimble/" page to accommodate the new strategy?

### **Brainstorm Doc:**
https://docs.google.com/document/d/1BeqcElSoPRctQqg6PeIRafk6r8txnAe6aJLnx4EaCdA/edit?usp=sharing

@kristinashu @alanmoo @anilkanji @gideonthomas @patjouk

**Comment by anilkanji** [comment]
Is it worth me reaching out to Brett to get his take on potential wording/opportunities we could present to users?

**Comment by kristinashu** [comment]
Maybe we could say something about our new strategy and what we are working on now? So link them to [our Trustworthy AI page](https://foundation.mozilla.org/en/internet-health/trustworthy-artificial-intelligence/) and [our blog](foundation.mozilla.org/blog)?

Links should be generic enough so we don't need to keep updating the links and should be internal fo'mo links.

**Comment by taisdesouzalessa** [comment]
@anilkanji if you reach out to Brett, please ask him to add this thoughts in the [Brainstorm Doc](https://docs.google.com/document/d/1BeqcElSoPRctQqg6PeIRafk6r8txnAe6aJLnx4EaCdA/edit?usp=sharing).

@kristinashu I'll add your comment here in the doc as well!

**Comment by taisdesouzalessa** [comment]
Talked to @gideonthomas and we decided to wait on this project until we have more data to take an informed decision. More info about that in the Brainstorm Doc, under the title "update".

**Comment by xmatthewx** [comment]
Good instinct @taisdesouzalessa! It would be great to let these visitors know about our broader work. 90% might not care. That's fine. But, some percentage of those people would certainly like to learn about our fellowships, advocacy, mozfest, etc.

I think we have more to learn by testing something live, than doing more research (you've given us plenty of insight). There's basically zero risk if we keep the work minimal. 

I propose that 
 - we do something similar to what we have at the bottom of the page, but put it at the top  
 - we add it with just via the CMS since it doesn't need to look perfect and it'll take very little time 
 - we link to /initiatives
 - we watch and see what happens

<img width="754" alt="image" src="https://user-images.githubusercontent.com/53411/72937537-53fff380-3d37-11ea-89c8-fcd873365c5c.png">

"This project was part of a broader movement for a healthy internet. See more."

I believe we could also a/b test different phrases and link destinations with no engineering.

**Comment by xmatthewx** [comment]
- Also, the overview page would benefit from a link to /initiatives and to /newsletter. 
 - Also also, the second sentence on the Thimble page could be changed to  "projects ~could be~ were migrated"

**Comment by gideonthomas** [comment]
let me clarify Tais' comment and add some context (from our brief chat) -- We don't need to do research. We already have data in SFMC for this. We just need a little bit of Steph's time to generate the report. If the conversions for sign up were high for our Thimble/X-Ray Goggles campaign -- then we probably should put more effort into this. But my instinct is that conversions were minimum to none. 

In general I don't think we should spend any time pursuing acquisition here. We could do what you suggest and add that tiny CTA at the bottom of the page and see what happens (Tais and I discussed this and she smartly suggested pointing them to the OLx program since it's still in the  web lit realm and is a more specific touchpoint), but even that is unnecessary. Any effort beyond that is overkill for now.

Re: "90% might not care", knowing the audience fairly well, I would say 99% won't. However, the SFMC report will either validate that or alternatively suggest that we should pursue an acquisition strategy. Hence why I say let's focus on other things until we know that we should even bother thinking about this issue.

There's a more pressing issue that Tais filed here: https://github.com/mozilla/foundation.mozilla.org/issues/4157. That might be worth putting some effort into instead.

**Comment by gideonthomas** [comment]
@xmatthewx to provide copy and @taisdesouzalessa can update the page to be similar to what @xmatthewx has in his screenshot above.

One caveat -- please let's not "A/B test test different phrases and link destinations". Seems like overkill at the moment until we have some data from Steph.

**Comment by taisdesouzalessa** [comment]
@xmatthewx I think it would be better to add the copy you want after the second paragraph, so after the sentence: "Thimble had active users in scores of countries." This is because when users reach this page, the most important info for them is what happened to Thimble. Then we can do a copy explaining why they should take a look at our initiatives page. It makes more sense from the user flow perspective.

Would you send me with the copy? 

Also, we will have to keep mini footer since it is automatically added to the page and it seems we have no control over that unless we get engineer help.

**Comment by xmatthewx** [comment]
Cool. And I have great news to share... in Jan, people who entered the site via the Thimble page [tapped donate 170 times](https://analytics.google.com/analytics/web/#/report/content-event-events/a87658599w138395144p142716704/_u.date00=20200101&_u.date01=20200131&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.landingPagePath&_r.drilldown=analytics.eventAction:Donate%20Button%20Tap/) and [submitted signup 372 times](https://analytics.google.com/analytics/web/#/report/content-event-events/a87658599w138395144p142716704/_u.date00=20200101&_u.date01=20200131&_r.drilldown=analytics.eventAction:Form%20Submit%20Tap&explorer-table.secSegmentId=analytics.landingPagePath&explorer-table.plotKeys=%5B%5D/). Your work could help us activate even more visitors. 

Copy: "This project was part of a broader movement for a healthy internet. See more [/initiatives]."

I'd put it below the 1st paragraph so we don't lose people inclined to bounce. People who are curious about thimble can ignore it and scroll down. You might also reduce the height on that graphic quite a bit; a slim banner so it doesn't push down the content so far.

**Comment by taisdesouzalessa** [comment]
This changed has landed: https://foundation.mozilla.org/en/artifacts/thimble/

Note: I find weird to have the same message on the bottom, plus the language on the bottom doesn't fit (it says "this IS part...") - any chance we can hide this mini footer on those pages? If we can, then I will add the same message on the other pages (some are very short pages and it makes it really weird to have similar messages so close to each other).

**Comment by taisdesouzalessa** [comment]
Also changed the page: https://foundation.mozilla.org/en/artifacts/x-ray-goggles/

**Created a Data Studio Dashboard to track any changes we may see in traffic**: https://datastudio.google.com/reporting/5be0d92e-12e7-47d1-b061-4296187143b7

**Comment by gideonthomas** [comment]
thanks Tais!
