### ISSUE TITLE
[Header/body newsletter list conflicts] Implementation ticket: updated body copy

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4141]
Implementation ticket for #3926

### Copy:
**Option 3**
Join our **Open Leadership** email list to always know what’s going on with our programs and events. Join our **Mozilla News** list to stay up-to-date in the fight for a better internet for all. 
**[Mockup here](https://mozilla.invisionapp.com/share/8TUW2XEGAF3#/401283412_body_-_Copy_3)**

Taís will implement new copy in the CMS.

**Comment by kristinashu** [comment]
Thank you for opening this @taisdesouzalessa! 

In the copy doc it sounded like we thought Option 3 would be best since it is the most adaptable for all the initiatives. Should we just use that? 

Also, this copy can be updated by you in the CMS so we don't need devs. Since it's easy for us to update, I would recommend make the changes and then adjusting it Steph has any concerns.

**Comment by taisdesouzalessa** [comment]
Cool, I'll update the tickets and work on updating the copy in the CMS on Monday then.

**Comment by kristinashu** [comment]
Thank you but you don't have to do it in this sprint, just saying that we won't need a dev to do it!

**Comment by taisdesouzalessa** [comment]
This is done. Live site here: https://foundation.mozilla.org/en/initiatives/open-leadership-events/
