### ISSUE TITLE
With Great Tech Comes Great Responsibility site

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#4159]
**Context:**
We are making this great document more accessible to our users by transforming the PDF into an HTML source. @alanmoo initiated the project and transferred the content to Wagtail and I did the design/structure refinement. 

**Site link here:** 
https://foundation.mozilla.org/en/initiatives/great-tech-great-responsibility/
Password protected, I'll share the password with you, Becca 

@alanmoo and @beccaklam could you please do a design and engineering QA?
Some things I noticed:
1. links open in the same tab instead of a new one. Should we make them open in a new tab? I think it would be better so people can go back to our site in an easier way. Not sure if this is our standard default though, please advise here, Alan
2. Lots of footnotes. The majority of them seem redundant to me because the links in the body goes to the articles...but let me know what you both think.

cc: @anilkanji @kristinashu

**Comment by alanmoo** [comment]
Footnotes def seem unnecessary. And we can't do anything about the external links within a reasonable timeframe.

**Comment by taisdesouzalessa** [comment]
Cleaned up all redundant footnotes.

**Comment by beccaklam** [comment]
@taisdesouzalessa Looks great. A few things:
- I would suggest using the narrowed page content formatting since these are text-heavy pages
- The H2 on the "Overview" pages seems to fight with the H1 a bit, can make the hierarchy a bit more clear?
- The beginning of the "Timeline" pages looks a bit strange with that first quote "There's nothing new under the sun [...]" there because of how it breaks up the spacing. Could we put the quote first before "The history of the tech worker ..."? Or just take it out?

**Comment by taisdesouzalessa** [comment]
Design review done! Closing this ticket.
