### ISSUE TITLE
IA: Initial draft based on data

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4177]
Based on planning in https://github.com/mozilla/foundation.mozilla.org/issues/4090 and [our deck](https://docs.google.com/presentation/d/11CK6yYXx8iCSsTG3Lc89-2k4Eiuy21zMoJIrmG7vjfY/edit#slide=id.g25275a8168_0_260).

Create an IA proposal using the analytics and recommendations in https://github.com/mozilla/foundation.mozilla.org/issues/4113. Please adapt the IA as results of the stakeholder interviews https://github.com/mozilla/foundation.mozilla.org/issues/4156 and the audience interviews https://github.com/mozilla/foundation.mozilla.org/issues/4114.

**Comment by beccaklam** [comment]
Here are four _slightly_ different proposed IA drafts: https://redpen.io/p/wd83cac5211b178ff0
The files are also merged into our Foundation Site file on Abstract.

I think we need to change our page titles for sure. I've put in basic placeholders for now that get at the function of the page (e.g. Work, About, Mission, etc) but we'll need to finesse these.

Aside from that from looking at benchmarks it seems like Foundation websites all follow a similar structure:

1. Who We Are (About Us page)
2. What We Do (The key issues they focus on)
3. How We Work (The programs they support)
4. Where We Work (not applicable to us)
5. Sometimes a site will have a section that talks specifically about their Funding or Grants/Investments

Aside from renaming "Internet Health" to something like "Our Mission", which is more clear, we should consider how to weave that content into "How We Work", currently our Initiatives page. I also think since we have two branches of work (staff run and our Grant programs), it would be a good idea to separate the two to help people understand what we do.

**Comment by kristinashu** [comment]
Thank you so much for the drafts! It so helpful for me to see this and it really helps ground all the things we've been talking about. Having this will really help guide our conversations.

Also, thank you for providing the rational behind your recommendations. I enjoyed your summary of the patterns you noticed from benchmarking. Could you please also add it to the benchmarking ticket https://github.com/mozilla/foundation.mozilla.org/issues/4198 as well?

@taisdesouzalessa @beccaklam let's spend some time talking through this next week and then maybe pause on it while the rest of the stakeholder research comes in.

**Comment by taisdesouzalessa** [comment]
Great work on that, Becca! Really liked the summary from the benchmarks as well. 
Looking forward to talk with you both about those next week!

**Comment by kristinashu** [comment]
Follow up work can be done here - IA: revised draft based on data & stakeholder interviews #4244. So this ticket is probably good to close!

**Comment by beccaklam** [comment]
@kristinashu @taisdesouzalessa Going to close the ticket then. If you need to reopen for whatever reason, feel free!
