### ISSUE TITLE
See if PNI Changes Have Made An Improvement

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#4190]
Look into PNI analytics and see if any improvement has shown after implementing changes after MozFest user testing.

**Comment by beccaklam** [comment]
Looking at GA, comparing Jan 06, 2020 - Feb 18, 2020 to the previous period, it look likes average time on page hasn't really changed. The exact metrics say avg. time on page is down 0.06% but if you look at the % it's comparing 00:00:52 to 00:00:52. And if you look at the pages themselves, the time spent on pages vary with some increasing since Jan 06, 2020 and some decreasing:
![Screenshot_2020-02-18 Analytics 360(4)](https://user-images.githubusercontent.com/20977376/74772269-a90f2680-525d-11ea-9a9e-679c7050981d.png)

If you look at events, however, it seems like a higher percentage of users are hitting our "Product" and "Sign up" events:
![Screenshot_2020-02-18 Analytics 360(5)](https://user-images.githubusercontent.com/20977376/74772343-ccd26c80-525d-11ea-832b-81994d990575.png)

It's hard to conclude if the changes have helped or hindered given the lack of quantitative data (there were much less visits to PNI during the Jan 06, 2020 - Feb 18, 2020 period). However, we did user test the new designs and the qualitative research did show an increased understanding of what our Minimum Security rating was. This _may_ relate to the higher percentage of events that we're seeing. This is speculative, however, as the higher percentage could be related to many things, including more invested users visiting our site at this slower time of year.

**Comment by beccaklam** [comment]
@taisdesouzalessa @xmatthewx if you have a second could you check my work here? The context is on Jan 6, 2020 (#4041) we landed a new design for the Minimum Security Standards portion of the PNI product page and we are looking for any clues as to how the design affected users in GA. What I've found is that it's generally hard to compare given the previous period we are comparing to is our high season (nov-dec). Average time spent on page seems to have gone down 0.06 secs but a higher percentage of people seem to be completing more events. This could be because of the design or because of the kind of people now coming to our site. Thoughts?

**Comment by taisdesouzalessa** [comment]
Nice work, Becca! Yeah, I agree with you about the jump on "sign up" and "product" events. I don't think we have enough information to make an informed guess on that. It definitely could be because new visitors are more invested at this time of the year...but it could also be because of the MSS new design...hard to tell. Maybe sitting with the data longer and looking into other numbers would help to figure it out.

In order to really see the impact of the MSS my recommendation is to go to the Product pages level and look at the data there. Since this change affected those pages, it is likely you'll see the effect on those numbers rather than in the site as a whole. I gathered some numbers, which show an increase in time spent on the "products" page.

**Here is the process:**

1. First I looked at the 2 designs. The only difference between then is the MSS box. 

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/22157921/75276969-048c6780-57bc-11ea-80d1-b3aa03f9f8a4.png">

So it is safe to assume that whatever change we made on those pages is affected by the MSS (there could be other external factors but this is the only factor we control).

2. Then I chose the most popular product pages and look at a metric that would be highly affected by a well designed MSS: average time on the page

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/22157921/75277313-9d22e780-57bc-11ea-8ddf-43f7cffd158a.png">

3. I also looked at this metric in all product pages, aggregated. So we can say that people are spending more time on those pages (from 53s to more than 1 min, in average). I think it is safe to say that it was due to the MSS change. 

Maybe you could find other metrics you think make sense to look at at the product level? I tried to look at other things such as bounce rate, which had a slight increase. Not sure if it is related to this change or what. I don't see how that could be, to be honest. 

You could also gather the feedback from the Qualitative research showing the feelings people had after this change. It may help to give some meaning to the numbers we see.

Hope that helps!

**Comment by beccaklam** [comment]
Thanks so much again for looking into this @taisdesouzalessa ! How were you able to isolate for just Product pages? I tried doing that but wasn't able to replicate. 

@kristinashu I think after Tais' analysis this ticket is good to close, but let me know if you think there's more that can be done!

**Comment by taisdesouzalessa** [comment]
@beccaklam - It is in behaviour/site content/all pages - then you use this tool to filter:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/22157921/75700331-c0d7a900-5c66-11ea-9e2d-49b4661437e3.png">

Term used for filtering only products: `en/privacynotincluded/products`

Let me know if it helps!

**Comment by beccaklam** [comment]
Thanks for your guidance and help @taisdesouzalessa :) Checked it out and it looks good. It's great to see that average time spent on page has gone up by 18.32%! Will close this ticket now.

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/58f1b6c6-46c0-4871-8fd2-ac3142e3be1d)
