### ISSUE TITLE
MozFest: design a CTA to go on blog post pages 

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#4256]
On the [/newsletter page](https://www.mozillafestival.org) on the MozFest website, using the Blog Entries block in wagtail adds a 'More From Our Blog' button. 

This button just links to [/blog/category/mozilla-festival/](https://www.mozillafestival.org/blog/category/mozilla-festival/) which isn't available under the Mozilla Festival domain so it 404s.

It should be directing to https://foundation.mozilla.org/blog/category/mozilla-festival/

**Comment by marcwalsh** [comment]
As a wider piece, is it possible to have the Mozilla Festival Blog page available under the festival domain?

Users will currently exit to the foundation site, with only the Mozilla Festival in the body of the page linking back to the festival website. 

Having this would allow users to browse more of our content, and then having our nav available would hopefully lead to more ticket conversions after they read more about the festival through the blog.

**Comment by xmatthewx** [comment]
- We can squash the bug in your first comment 
- We could add a shortcut redirect from mozillafestival.org/blog to the full blog url for convenience
 - We can't move the blog itself. 

It was intentional to have a unified blog – too many people in our audience (and staff for that matter) were confused about where to post and where to find info, and struggled to keep up. We have moved from many blogs, to one primary blog. This increases the opportunity for our sub-audiences to break silos, discover our other work and ways to engage. This works both ways: people who come for advocacy or fellow related things are more likely to discover and become intrigued by mozfest, and vice-versa.

**Comment by marcwalsh** [comment]
@xmatthewx - Thanks, that does makes sense about ensuring the audiences are not siloed, however looking at the page on the Foundation site at the moment, it's difficult for a user to navigate back to the Festival site. The aim of the blog content for us is to convert users from reading the content to (eventually) buying tickets. 

Would it be possible to make a clearer link to return to the festival website, and/or have a way of ensuring there's a clear CTA for ticket sales on the individual blog pages?

For the blog pages themselves also, does the newsletter signup on those pages add subscribers to the Mozilla Festival mailing list as well as the general lists on Salesforce?

**Comment by xmatthewx** [comment]
Good questions. 

> make a clearer link to return to the festival website

Problem: A user visits mozfest site. Taps a blog posts. Reads it, loves it, but doesn't have a clear path back to take action, such as propose a session. 

Potential solutions: 
 - A) Blog post includes a call to action within the content. Either inline link or more attention grabbing button (done within CMS).
 - B) Blog post template includes a generic thing that links back to mozfest (similar to what you see at the top of the main fest blog page at [/category/mozilla-festival](https://foundation.mozilla.org/en/blog/category/mozilla-festival/))
 - C) We let users rely on back button

Option C is not terrible, but less proactive than Option A or B. And, might lose a few people. 

Option B is more automatic. It requires engineering work. And, would have to be a generic way back to the fest. 

Option A is more flexible and can be targeted toward a specific action (since it can be done within CMS). A designer could help create a few examples to give you some recipes to drop in.  

cc @kristinashu for input.

**Comment by xmatthewx** [comment]
> does the newsletter signup on those pages add subscribers to the Mozilla Festival mailing list

That's unlikely. I think the best bet for that would be a nicely designed call out that links to standalone signup page on the mozfest site. We have one on the foundation site for when we need to link to signup from an Ad or social. 

cc @kristinashu

**Comment by kristinashu** [comment]
Option A is what we've been doing so I'd recommend we stick to that.  One general example is at the bottom of this post https://foundation.mozilla.org/en/blog/what-do-you-think-about-artificial-intelligence/
<img width="777" alt="image" src="https://user-images.githubusercontent.com/1068783/75931611-40fa3c00-5e2a-11ea-831a-646e7014a613.png">

and an IHR example is at the bottom of this post https://foundation.mozilla.org/en/blog/5-key-decisions-every-smart-device/
<img width="748" alt="image" src="https://user-images.githubusercontent.com/1068783/75931632-52434880-5e2a-11ea-8cc0-7226194c0b2d.png">

We can link to the MozFest sign up page We can link to this signup page https://www.mozillafestival.org/newsletter/ and/or the homepage.

I've opened a new ticket for devs to fix the link https://github.com/mozilla/foundation.mozilla.org/issues/4295 and we can turn this into a design ticket to design the CTA at the bottom of blog posts.

**Comment by kristinashu** [comment]
@sabrinang will be able to work on this this sprint! Sabs, you could use [this post](https://foundation.mozilla.org/en/blog/power-city-why-amsterdam/) as a use case.

**Comment by sabrinang** [comment]
![mozfest-suggested-cta](https://user-images.githubusercontent.com/2492510/77969142-eecbff80-729d-11ea-8fcd-278e5d7b627d.jpg)

For the blog posts, I suggest using `image text` component in wagtail and using the lockup. You can use the white lockup on black to match the m cta we have and the black background may draw more attention to the reader than black lockup. 

I also separated the last sentence so the links are not so close together.

@marcwalsh Does this work for you? 
@kristinashu R?

**Comment by marcwalsh** [comment]
Thanks @sabrinang - do you think it would be possible to use something like the Amsterdam graphic in some form to have more colour in the CTA? 

I really like that aspect of the Privacy Not Included example.

**Comment by sabrinang** [comment]
@marcwalsh what about something like this:
<img width="1792" alt="Screen Shot 2020-03-31 at 11 26 41 AM" src="https://user-images.githubusercontent.com/2492510/78061788-93a01880-7342-11ea-8c9e-390944f142e7.png">

that uses the colour gradient and buildings of Amsterdam along the bottom?

**Comment by marcwalsh** [comment]
Thanks Sabrina - talked to Sarah about this and we both love it!

**Comment by sabrinang** [comment]
Great thanks for reviewing! The update CTA is published live on the blog post now: https://foundation.mozilla.org/en/blog/power-city-why-amsterdam/

Closing issue.
