### ISSUE TITLE
Language switcher doesn’t work in some cases

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4290]
There’s a specific case in which the language switcher stops working. It works a first time, but then when you land on a different locale again (e.g. you clicked on a hardcoded /en link), you can’t switch back.

Here are the STR:

- Set French as your preferred language for Web content (it would work with any locale we support)
- Open `foundation.mozilla.org/en` or any page in English
- Use the switcher to pick French
- You get redirected to /fr as expected.
- Now open `foundation.mozilla.org/en` again (or any page in English)
- Try to switch to French

→ You are not redirected

**Comment by mmmavis** [comment]
I'm not familiar with the i10n setup so it'll take me some time to figure this out. Since this is a unique case and that I don't have the capacity to work on it this week, I'm going to put this in the next milestone. @Pomax do you know what might be causing this and how complicated it will be to fix it?

**Comment by TheoChevalier** [comment]
Fixed by #6765
