### ISSUE TITLE
Enable sitemap

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4376]
Currently, `sitemap.xml` is exposed (on `/sitemap.xml`) if the site is on `DEBUG` mode.

@xmatthewx other than making sure private/draft pages don't get exposed, what are other requirements we need to fulfill? (e.g., is this for internal or external use? do we want to enable sitemap by default on production or just on staging? ... etc)

/cc @Pomax

**Comment by xmatthewx** [comment]
The main thing is that it would help search engines discover program content that isn't featured on a top level page. And it might help with long tail search traffic to useful resources long after they're featured. 

Hopefully our evolved IA solves for much of this, but if it's easy to turn on, let's go for it.

I can't think of any other requirements beyond private/draft.

**Comment by gideonthomas** [comment]
@xmatthewx if the IA work is going to introduce a bunch of changes to page discovery, should this wait until the IA is updated so that Google doesn't have to re-index stuff (which can take a while)?

**Comment by xmatthewx** [comment]
That's a good question. I could see the case for waiting. My gut says proceed, since we don't know how long it'll take to roll out the IA changes, and google should check periodically. And, google has already indexed most of the top level pages as they are. That said, this isn't urgent, so I also think it's fine to push this forward a few sprints. Sorry for the non answer. I say go for it unless Mavis or someone has a reason to want to put it off.

**Comment by cadecairos** [comment]
Let's verify that password protected/private pages and drafts don't show up in the site map.
