### ISSUE TITLE
[PNI] Implement a Service model for PNI

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4486]
Tasks involved:

- [x] Split up the Product model into a base model and general product, as new model types
- [x] set up a copy-migration to create new "general product" entries for each Product (temporarily duplicates data)
- [x] update the voting and related code to use the new type
- [x] update the CMS admin to use the new type
- [ ] remove the old type (deduplicates data)

And then possibly:

- [ ] rename the new type to the old type? (this might not be necessary)

**Comment by cadecairos** [comment]
Proposal time!

Can we create a class `class VideoCallProduct(Product)` that extends Product. This new class can leverage all the fields we need from the original Project model (and gets all the advantages of the model relations for categories, updates, etc). We could use [model admin excludes](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.exclude) to hide fields we don't want, and have the ModelAdmin class for `VideoCallProduct` set hidden defaults on required hidden fields. The upside of this approach means we wouldn't have to deal with a migration of older products. The downside is that it's messy.

Another approach would be to implement the shared fields of `Product` and `VideoCallProduct` as a base class `ProductBase`. Upsides: This is the cleanest and most future proof option, especially if we consider future product reviews for PNI. Downsides: Potentially troublesome migration, but we're using plain old django, not wagtail so significantly less risk there. This could take more time than we anticipate too.

**Comment by Pomax** [comment]
Follow up:
- [ ] make the "recording alert" an ExtendedYesNoField (yes/no/NA/unknown) rather than BooleanField

**Comment by caltrider** [comment]
Just dumped the Signal product in. It's working pretty good so far. Here's what I found: 

- [ ] For price, there is a $ before all the things. For some products that are Free, or Free with some other paid tiers, that doesn't work great. 
- [ ] For the section of that's the two "Shares Data" and "Shares Data Helptext" above the "how does it handle privacy section", I don't think we need that now as the "How does it share data is in the "how does it handle privacy section" now. 
- [ ] Under "how does it handle privacy" it should read "How does it share data?" rather than just "how does it share" (that might be just the text for the field in the CMS, still was a bit confusing for me)
- [ ] We don't plan to do the "ways to contact the company" for these. If that needs to stay in, I can round up that info but likely won't have it for launch so if possible, would be great to take it out instead
- [ ] Recording alert should have a Not Applicable field alongside Y/N/Unknown as some apps don't let video call recordings happen. 
- [ ] The "What's Required to Sign up?" section...were we going to do that like Natalie had laid out in the redpen i saw with it laid out horizontally across and I could select each one that was relevant -- Email, Phone, Third-Party App?  
- [ ] Will the "Compliant with US medical privacy laws?" section only show up if checked, rather than show up for all and we do a Y/N/Unknown with a line for help text? I think it would be great to always show that to clarify which ones do and don't. 

That's what I've got at the moment.

**Comment by Pomax** [comment]
/cc @mmmavis 

- For the price issue, we could look at whether it's a number or not, and if it is, add $ but if it's not, leave it off?
- Do you mean it should only exist for the general products, rather than also for software, or does it need to be taken out entirely and nothing should have it?
- that's an artifact from how wagtail does things. The model variable is called `how_does_it_share` (without "data") so Wagtail automagically turns it into `How does it share". Not ideal, but not really something that's easily fixed atm.
- We can leave them in but simply not show them for software products by blanking that section of the software product template. Would that be acceptable?
- Done: the "recording alert" field has been updated to the yes/no/na/unknown field now
- That's a template issue, @mmmavis can probably answer that on
- It's certainly _easier_ to simply always show it (less conditional logic makes for easier code) so if that's what you prefer, let's go with that.

**Comment by cadecairos** [comment]
>     * For price, there is a $ before all the things. For some products that are Free, or Free with some other paid tiers, that doesn't work great.

Filed https://github.com/mozilla/foundation.mozilla.org/issues/4514

**Comment by caltrider** [comment]
/cc @mmmavis @Pomax @cadecairos 

- 
-     For the price issue, we could look at whether it's a number or not, and if it is, add $ but if it's not, leave it **off?**  **Will that work for something like this? "Free trial, $5 - $12.50 per month"**
-     Do you mean it should only exist for the general products, rather than also for software, or does it need to be taken out entirely and nothing should have it?  **It should exist for general products. For the video call apps, we do it under the "how does it handle privacy" as the top text box**
-     that's an artifact from how wagtail does things. The model variable is called how_does_it_share (without "data") so Wagtail automagically turns it into `How does it share". Not ideal, but not really something that's easily fixed atm. **no biggie...as long as it shows up on on the page, i'll do my best not to be confused by it when i'm putting stuff in in the cms =)**
-     We can leave them in but simply not show them for software products by blanking that section of the software product template. Would that be acceptable?  **Sounds perfect. They are still on the product page, just not doing that for the apps**
-     Done: the "recording alert" field has been updated to the yes/no/na/unknown field now **Yay!**
-     That's a template issue, @mmmavis can probably answer that on **crossing my fingers we can make it happen**
-     It's certainly easier to simply always show it (less conditional logic makes for easier code) so if that's what you prefer, let's go with that. **Yay, I like always showing it so people know to look for it. thanks!**

**Comment by cadecairos** [comment]
>     * that's an artifact from how wagtail does things. The model variable is called `how_does_it_share` (without "data") so Wagtail automagically turns it into `How does it share". Not ideal, but not really something that's easily fixed atm.

I think we should be able to use **verbose_name** to change the label text in a model's form (https://docs.djangoproject.com/en/3.0/topics/forms/modelforms/#modelform) if we want to try fixing this

**Comment by Pomax** [comment]
Closing this issue in favour of tracking the removal work separately in https://github.com/mozilla/foundation.mozilla.org/issues/4543
