### ISSUE TITLE
BaseRangeProductVote.MultipleObjectsReturned

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4532]
https://sentry.prod.mozaws.net/operations/foundation-mozilla-org/issues/7949797/

```
BaseRangeProductVote.MultipleObjectsReturned: get() returned more than one BaseRangeProductVote -- it returned 2!
(4 additional frame(s) were not displayed)
...
  File "django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "networkapi/buyersguide/management/commands/aggregate_product_votes.py", line 65, in handle
    defaults={'votes': 0, 'average': 50}
  File "django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
```

**Comment by Pomax** [comment]
It turns out that there we hundreds of range and boolean averaging records that got duplicated, and had 0 votes in them. Running the following "fixes" it:

```js
from networkapi.buyersguide.models import BaseRangeProductVote, BaseBooleanProductVote

BaseRangeProductVote.objects.filter(votes=0).delete()
BaseBooleanProductVote.objects.filter(votes=0).delete()
```

but I'm not sure what caused it in the first place: I tested voting on something and then rerunning the `manage aggregate_product_votes` command, but that does not lead to any duplications, and I reran `manage migrate` and that also didn't lead to any duplications, So, other than during the very first migration, which could have duplicated anything, I'm not sure what would have caused this. 

@cadecairos do we want to simply issue that mini-script against staging and then... I guess wait for a few hours? =x
