### ISSUE TITLE
it looks like we have a horizontal scrollbar at medium and smaller breakpoints

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4586]
Chrome:

![image1](https://user-images.githubusercontent.com/177243/80755354-8151ff80-8ae5-11ea-8323-c0ee4a4f67e1.png)

Firefox:

![image](https://user-images.githubusercontent.com/177243/80755363-84e58680-8ae5-11ea-831a-e633362712c8.png)

**Comment by mmmavis** [comment]
Looks like it's something to do with `narrow-screen-menu`. I'm gonna use this as an opporutunity to clean up `primary-nav.scss` code for both Foundation site and PNI. They seem to be sharing quite a bit of code.

**Comment by mmmavis** [comment]
Aside from `narrow-screen-menu`, our`.full-bleed` related rules are the main cause of this. I took a stab at it but ended up spending too much time without any success. Initially, I thought this would be a quick fix that's why I added it to this sprint last Thursday. Re-accessing the ticket now I don't think I have bandwidth for this anymore, I'm gonna remove this ticket from this sprint.
