### ISSUE TITLE
Button visual regressions

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#4629]
We’re having some visual issues with buttons, which I think are due to https://github.com/mozilla/foundation.mozilla.org/commit/6d9ffd442f14f041c0e4c6f5573d4b8d9e064e2c
@mmmavis any chance we could add this line back, or find a different solution?

Creep-o-meter post-vote screen:

![image](https://user-images.githubusercontent.com/1294206/81840987-a6149100-9541-11ea-8197-c1cc4dc4a989.png)

Footer (French), where this used to fit in one line

![image](https://user-images.githubusercontent.com/1294206/81841029-b88eca80-9541-11ea-8bd4-c3618e309102.png)

Footer (Portuguese)

![image](https://user-images.githubusercontent.com/1294206/81841106-d3613f00-9541-11ea-9c9c-03f57d682075.png)

**Comment by mmmavis** [comment]
@TheoChevalier we intentionally want long button text to wrap. I'll talk to designers to see if we want to footer newsletter button as exception.

> Creep-o-meter post-vote screen

I can fix it by expanding the container width.

**Comment by mmmavis** [comment]
@TheoChevalier thanks for filing ticket! We intentionally want long button text to wrap.

> Footer, where this used to fit in one line

I'll talk to designers to see if we want to footer newsletter button as exception.

> Creep-o-meter post-vote screen

What we had **before** had alignment issue as well
![image](https://user-images.githubusercontent.com/2896608/81846201-9166d780-9506-11ea-865d-f1a0511c0384.png)
It's hard to tell but if you look closely, "Facebook" button's right padding is smaller compared to others because this long text doesn't wrap and just continues going in the same line. I might be able to fix this by expanding the container width but I should chat with designers before I do it.

**Comment by mmmavis** [comment]
Had a quick check. We might have to alter how the share button group is currently implemented to make sure buttons are always in the same width. Bumping the estimate up to `3`.

**Comment by Pomax** [comment]
This looks like we should first try a `white-space: nowrap` to see if that solves it? (it looks like it's line-breaking at the whitespace between the icon and label, which we don't want)

**Comment by mmmavis** [comment]
Yea `white-space: nowrap` will help get the newsletter signup button to look what we used to have. PNI share buttons have more issues, some related to how the share button group was implemented, some related to the PNI's design and overrides. I have a WIP PR and will chat with Becca to come up with a solution.

**Comment by mmmavis** [comment]
Talked to @sabrina and we decided to add the `nowrap` rule back to buttons. This change will be on prod tomorrow.

---

@beccaklam Will need your design input to fix the share button issues. Please see this [PR](https://github.com/mozilla/foundation.mozilla.org/pull/4630)
