### ISSUE TITLE
Create ShareProgress Page Wrapper

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#4651]
Design Issue: https://github.com/mozillafoundation/design/issues/517

Create wrapper page HTML <style> to reflect new branded wrapper design.

**Comment by mmmavis** [comment]
**BLOCKED** until Shareprogress solves a certificate issue. We have emailed Shareprogress about this.

This is what I see when I try to preview a page wrapper.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2896608/82592232-7246f600-9b55-11ea-9aec-5416b768e591.png">

**Comment by mmmavis** [comment]
k unblocked again

**Comment by mmmavis** [comment]
Things to figure out first

- [ ] Can we upload images that shareprogress hosts? Or do we have use inline svg?
- [ ] Can we add a CSS file, or do we have to do it in the html head?
- [ ] Can we include external assets? e.g., include images that live on S3
- [ ] Do we wanna use JS to modify default content that's injected by Shareprogress?

**Comment by mmmavis** [comment]
Ummm there's little we can do to customize Shareprogress' page's look. The way they implemented the page is very dated and is not responsive (sizing of each element is hardcoded 🤯... why?!?!?). I've tried my best to alter the look using CSS only approach (but in a hacky way already). I'm opposed to us hacking it more using JS as it can easily break the functionality without us knowing. 

**Some notes**

- We can't control content within the white box as that section is injected by Shareprogress's script. The best we can do is updating styling of "some" elements to "some" extend. (It's case by case because the way Shareprogress structured their code)
- We can add header content and footer content before/after the white box.
- We can replace certain icons

**My WIP wrapper is called `[TEST] Mavis WIP Test`**
**Test page: http://share.mozilla.org/352/207160**

Here are screencaps of before & my WIP wrapper. I'll work with @sabrinang to tweak things further here and there.

![Screenshot_2020-05-22 Mozilla Foundation(1)](https://user-images.githubusercontent.com/2896608/82714313-de535800-9c42-11ea-9e67-d2d59f2b5525.png)

![Screenshot_2020-05-22 Mozilla Foundation(2)](https://user-images.githubusercontent.com/2896608/82714843-59b60900-9c45-11ea-9c7c-d476cdf5cd21.png)

**Comment by mmmavis** [comment]
Design review is happening as comments in https://github.com/MozillaFoundation/Design/issues/517

**Comment by mmmavis** [comment]
Done.

The default wrapper is called `Default MoFo Wrapper` on Shareprogress.
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2896608/83430699-f5d0d480-a3ea-11ea-8d70-a91a98f1e8ea.png">


Repo for the code https://github.com/MozillaFoundation/shareprogress-wrapper
