### ISSUE TITLE
Consider renaming `scaleText` mixin to `setTextSize`

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#4739]
Mostly to make sure it's named in a way that reflects what it does - rather than scaling text (using `transform: scale` or even percentages) it directly sets text size/line height to the values specified.

@mmmavis what do you think?

**Comment by mmmavis** [comment]
Yea we can rename it. This is an old mixin that I adpated and meant to rename but kept forgetting 😂 (But I was thinking about just fixing the letter casing so it's `scale-text` instead)

I'm not sure if we wanna use`transform: scale` for this because mobile/desktop font types aren't always upsized/downsized in scale. I also prefer explicitly putting down font size and line height for mobile and desktop so they correspond with how the design files and brand guide were documented (in fixed `px` values). This also makes it easy to tell what font style we are using without going through math calculation lol. 

I can work with the designers for this ticket when the time comes.
