### ISSUE TITLE
MozFest: Enhance landing page inheritance for easier author experience

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4789]
Same as - Enhance landing page inheritance for easier author experience #2964 - but for MozFest pages.

Child pages should inherit their parents banner image if nothing is specified for that specific page. 

Note the mozfest site has a different fallback image than the main site and if now banner image is selected that it should show the mozfest fallback image.

**Comment by KalobTaulien** [comment]
@kristinashu For clarification, you'd like this to look for a banner image in this order, correct?

1. Look for a banner image on the page itself. If not found then
2. Look for a banner image on the parent page (and continue up the tree until an image is found). If not found then 
3. Fallback to the default banner image

**Comment by Pomax** [comment]
https://github.com/mozilla/foundation.mozilla.org/pull/4878 exists, and is currently blocked because of review apps not actually using the same site/page system that the real mozfest site does. @cadecairos we need to look at what can be done here, because it's blocking testing of code that I'm 99.% certain of works fine =(
