### ISSUE TITLE
Data stewardship landscape analysis: Prep

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4817]
Request from: Kasia, Eeva, and the Insights team

They are publishing three pieces of landscape analysis research. These will be the first publication batch of a bigger series on data stewardship. Their [research roadmap](https://docs.google.com/document/d/1XIB3M09FioYocjbMnV7Nrt2_T8DPaL6oN6w3ioABVaA/edit) and [engagement team requests](https://docs.google.com/document/d/19oOxED2ac-VoJylqEIb-bbmFhXdxTpST0SbvhRfagrY/edit#).

PDFs style should follow [our standard mofo branding Google doc template](https://docs.google.com/document/d/1PTdSrNA7-2LiTmAISEOzWmPEhUZvbDPjaYp2-JFc8T8/edit).

### Steps to complete this Sprint
- [x] Kick-off (scheduled for Monday June 29)
  - Clarify timeline (when the content will be final)
  - Give them our Google doc template and ask them to start formatting their content with that
  - Clarify which graphs are final and ready for design
- [x] Tais to explore options (e.g. AirTable) for the database
- [x] Tais to create a style for the graphs and charts
- [x] Open a ticket for next sprint's deliverables (see below)

### Deliverables (for next Sprint)
- Foundations research (big ~60 page publication) ([draft](https://docs.google.com/document/d/1BBJRmIh0krDSy7djGFQFORuVNgN7k3PMzOC0R0bmTlE/edit#heading=h.mefjv4rjbj5d)) 
- Approx. 6 graphics
- History of data stewardship (medium ~10 page publication) ([outline](https://docs.google.com/document/d/1sDFJ6iUR7afgU9QfW_W7J7-8Uwp7E14BSfIVqgqfJ_U/edit)) (need draft)
- Database analysis (small ~20 page publication) ([draft](https://docs.google.com/document/d/17DXwX-DfzXwawoe3lwriNHHBCbtyH-7PoRCTowyZr3E/edit#heading=h.q57oq65fh8g9))
- Style the database - "Suggested initiatives" tab (maybe we make in AirTable) [draft](https://docs.google.com/spreadsheets/d/1RJXbWCTOKRvAGNdg8jhiBNjvWr_tiDHqfg8RDEYmb08/edit#gid=1669955301) 
- Landing page that links to all these PDFs

### Needs discussion (for next Sprint)
With Anil, Phil, Kristina, Tais, Kasia/Eeva
- Which template to use for the landing page and were should it be in the IA (what URL)?
- Social media promo?
- Newsletter signup?

**Comment by taisdesouzalessa** [comment]
**Taís to do list:**
- [ ] add footnote style to template
- [ ] get designers' approval
- [ ] send new template to Eeva
- [ ] research how to style items on Airtable
- [ ] once Stephan give me access to graphics in Google Drive, style them to be on brand
- [ ] once Eeva add items to Airtable, style them to be on brand and see if any issues arise.

**Note:** 
Eeva and her team will start adding docs to the template starting next week.

**Comment by kristinashu** [comment]
I've opened two tickets for our next sprint:
- Data stewardship landscape analysis: Create PDFs #4829
- Data stewardship landscape analysis: Create a home #4830

@taisdesouzalessa does these cover everything?

**Comment by taisdesouzalessa** [comment]
@kristinashu thanks for those tickets! 

I feel the 2 last items from #4829 will start this sprint
- [ ] On brand AirTable of database - "Suggested initiatives" tab) draft - _likely to be finished on this sprint_
- [ ] All graphs/charts are styled and on brand - _I'll start those on this sprint but there are some "bumps": learning how to style them using Kumu (complex graphics) and Google Drive charts (driven by Stefan) are still in progress, so I'll come up with a "style guideline" this sprint and probably apply to the final graphics next one_

should I create a ticket for this sprint covering those 2 items?

**Comment by kristinashu** [comment]
I think this ticket can cover those two things. But of this sprint I think they'll be more about "exploring" and then next sprint will be finalizing them.

**Comment by taisdesouzalessa** [comment]
### **Kumu charts** 
[Alternative Governance Model Canvas →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997348_Before-After-Kumu-Charts-Alt-Governance) | [Kumu link](https://kumu.io/taislessa/alternative-governance-model-canvas)
[Decision Tree →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997349_Before-After-Kumu-Charts-Dec-Tree) | [Kumu link](https://kumu.io/taislessa/decision-tree)
[Data Stewardship Mapping →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997350_Before-After-Kumu-Charts-Mapping) | [Kumu link](https://kumu.io/taislessa/data-stewardship-mapping-64b2)

**To do:**
- [ ] get stakeholders style approval
- [ ] apply style to original graphics

**Comment by taisdesouzalessa** [comment]
**### Google Sheets charts**
[Color scheme example here](https://docs.google.com/spreadsheets/d/1q5gDrmJul8y2iqPoNFKKjt9M0XsflieVO_tySPpm1G8/edit?usp=sharing)

**To do:**
- [ ] get stakeholders style approval
- [ ] apply style to original graphics once they are finished by Stephan

**Comment by kristinashu** [comment]
These look great!

**Comment by taisdesouzalessa** [comment]
### **Airtable** 
- entry point: [readme page →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997875_Airtable-Readme)
- [projects tab →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997874_Airtable-Projects) - Since Kasia mentioned we may not be able to upload logos and because we can't do custom illustrations to every item on the table due to time restrictions, the recommendation is to use 4 types of patterns as images and alternate them (patterns already created and placed in Airtable). 
- [Authors and Contributors tab →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997873_Airtable-Authors_Contributors) - recommendation: team can upload their pictures (no design work required)
- [Authors and Contributors tab →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997873_Airtable-Authors_Contributors) - recommendation: team can upload their pictures (no design work required)
- [Supporting Entities tab →](https://mozilla.invisionapp.com/share/ZFXY0HI5E28#/423997876_Airtable-Suppoprting-Entities) - recommendation: remove logo field since we can't upload logo (no design work required)

[link to Airtable  →](https://airtable.com/invite/l?inviteId=invzI3wYuSsGGgMS4&inviteToken=5389fe06086916cabfde65dd103dada3ecfa1e6f204ff72ce325a173a1432f28)

**Comment by taisdesouzalessa** [comment]
Created a new ticket for next sprint, related to feedback round and tweaks: #4871 - the planning phase from this sprint is done.
