### ISSUE TITLE
Blog author photos

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#4840]
We need to create an easy way to get blog author photos (example use case: blog cards). 

- [ ] Explore adding a ForeignKey to the Author/Profile class. 

Note: These will be used in Blog Cards. We'll want to keep queries low or consider caching so we don't slam the database with necessary queries to the Images table.

**Comment by kristinashu** [comment]
Design needs do a little more thinking around this. I've opened https://github.com/mozilla/foundation.mozilla.org/issues/4846 to be done in the July 20 sprint. Design will need need to consult engineers on this but building it out is blocked until design is done.

**Comment by Pomax** [comment]
Talking through the comps, backend-wise this will require:
- updating the current Blog `author` field to a foreignKey to a new Author model with fields:
  - `name`: the author's full name
  - `image`: the image that is associated with that author
  - a migration `run` definition that automatically `get_create`s the `mozilla` author, with its associated graphic
- prepopulating the author list with the current user (if there is a name-matching `Author` instance)
  - a migration `run` definition that uplifts preexisting `author` charfields to the new `Author` model (with `get_or_create` rather than blind `create` =)
- adding a `clean` def to Blog pages so that you can't publish a page unless there is at least one Author set


Front-end wise this will require:
- implementing the new card layout, with
  - `<wbr>` between the list of icons and names, so that a line wrap splits between images/text first
  - ideally, `nowrap` on author names, so that line wrapping does not leave a name split over consecutive lines

**Comment by Pomax** [comment]
Question: there is a `People` app that I don't think we're still using. Can we:
1. investigate whether that is indeed unused by now, and
2. determine whether it makes more sense to reuse, or retire

/cc @cadecairos

**Comment by cadecairos** [comment]
we're exposing the model still via public API but I do not think any of our templates, pages, or snippets depend on it. 

I'm satisfied that it's safe to remove that route. 

Re-purposing is possible, but there's a bunch of existing data in there though which I doubt we need still, so starting a new model might be a cleaner approach, rather than a data migration to get it in the right format or clean it out altogether.

**Comment by Pomax** [comment]
let's go for clean. I've filed https://github.com/mozilla/foundation.mozilla.org/issues/4908 to track removing the `People` app.

**Comment by KalobTaulien** [comment]
@taisdesouzalessa Just to confirm, there _can_ be multiple blog authors on each blog post right? If so, how many would be the max?

**Comment by taisdesouzalessa** [comment]
@KalobTaulien yep, here is an example: https://foundation.mozilla.org/en/blog/rapid-virtual-meeting-prototyping-age-pandemic/ - in this post we have 3 authors. Do we need to impose a max number of authors? Ideally we should have as many authors as needed. 

For UI display purposes, it seems @natalieworth planned max 3 pictures for bigger areas and max 2 for small ones (if it exceeds it, we add "+2" for instance), as per this mockup: https://redpen.io/sb271478cae0b6a0f8

**Comment by beccaklam** [comment]
Hi @KalobTaulien and @taisdesouzalessa please see this ticket for what we decided for blog authors: https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/4846

Basically there will be no limit to blog authors as we foresee 2-3 authors being used and if there is such a case there will probably be good reason. 

We also decided to forego condensing authors since the purpose of displaying blog author images is to highlight staff. This means all authors will always be displayed. Please let me know if you have any questions!

**Comment by beccaklam** [comment]
Final redpen designs are here: https://redpen.io/p/dn2ff4a99909ffc5b7

**Comment by KalobTaulien** [comment]
@taisdesouzalessa @beccaklam Thank you both!

**Comment by beccaklam** [comment]
test

**Comment by Pomax** [comment]
Let's not put a max_num on authors: there will be rare cases where we might want more than 3, but most will have a reasonable number as determined by the person writing the blog entry. No need to restrict that value.

**Comment by KalobTaulien** [comment]
@Pomax Understood, I've removed that max length. 

I did some sloppy surgery on the featured_blogs.html include/fragment to get the images in there. Think I'll make a template tag for this instead of having so much logic in the template
