### ISSUE TITLE
Design blog author experience

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4846]
Based on: [IA refresh] Homepage design #4648 and [these homepage comps](https://redpen.io/p/bn82314af4898269e1) we would like to add authors to blog posts.

### Design to mock-up and consider
- [x] How authors are added in the CMS (working closely with the devs on this) _(keep it simple!)_
- [x] How to handle multiple authors (working closely with the devs on this) 
- [x] Mock-up desktop and mobile version for the homepage
- [x] Mock-up desktop and mobile version for the /blog page
- [x] Mock-up desktop and mobile version for a blog detail page
- [x] Mock-up desktop and mobile version for the Recent blog entries component

**Comment by beccaklam** [comment]
@kristinashu @natalieworth Sorry a bit confused, didn't Nat already mock up homepage desktop and mobile designs that includes this? Am I missing something?

**Comment by kristinashu** [comment]
She mocked it up for the homepage but there are still some questions around how many profile pictures to show and when. Should we show all the authors. and up to how many? When to show +2 or +3... authors? Is that the best format? Does it work everywhere?

**Comment by beccaklam** [comment]
[Benchmarks doc here](https://docs.google.com/document/d/1aUl-ke2c6vzzKGXnNEa_XJNJ26VQPZzVy7LKOu_GFQ0/edit?usp=sharing)

**Comment by beccaklam** [comment]
@kristinashu @natalieworth 

## Mockups
[Redpen for mockups is here](https://redpen.io/p/dn2ff4a99909ffc5b7)

## Recommendations:

- Keep overlap
- Show all author images and names (no condensation). Reasoning for this is because if the goal is to highlight staff we should just highlight everyone. Even if we tried to be fair with alphabetical ordering it would mean some folks would be disproportionately featured more than others. Also, I think we have enough space to feature multiple authors anyway
- Start author names on second row if group of names exceed container width
- Switch from double column to single column when listing out multiple blog entries (this relates to /blog and the recent blog entries component)
- Blog author images should be optional
- Blog author images and names link to profile and tagged blog posts, something similar to this:
![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/da1122a4-0ba9-4cbe-8460-c839e657d369)

**Comment by beccaklam** [comment]
Hi @Pomax, see final designs below. Will also slack you to organize a time to meet to talk through the first two items in the checklist above.

## Final Designs
[Redpen here](https://redpen.io/p/dn2ff4a99909ffc5b7)

**Comment by beccaklam** [comment]
Met with Pomax. He will open up some engineering tickets for this work. Basically we'll add an author image input along with the current author input and also enable multiple author fields. If an author field is left unpopulated the default behaviour will be a fallback image and the name of the user who posted the blog post. We both decided there isn't really a need to limit the number of authors as we don't see users exceeding two to three authors most of the time anyway (and if they do there's probably a good reason). This is done!
