### ISSUE TITLE
Update copy on petition confirmation screen 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#4880]
A moco ux researcher has pointed out that our "No, I'll share instead" copy is a considered _no shaming_ and that we should update it.

#### To see the screen
- Go to https://foundation.mozilla.org/en/campaigns/tell-amazon-ring-stop-sharing-information-police-services/
- Fill in info and click on "Add my name"
- See the donate light box and the text under the donate button

#### Todo
- [x] Update copy from "No, I'll share instead" to "No thanks"

#### Screen cap from prod
![image](https://user-images.githubusercontent.com/1068783/86851585-159d8d00-c068-11ea-8237-5ae3c7d6cfde.png)

cc @cadecairos for triage

**Comment by Daniel-Davies** [comment]
Hello, I'd love to take this issue as my first contribution to a Mozilla project, if that's ok.

**Comment by mmmavis** [comment]
Ah! I thought this would only require an easy text change in the template (frontend) so I added this ticket to this milestond. It turned out requiring changing default value for `DonationModal`'s [`dismiss_text` field](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/donation_modal.py#L40) (backend). Let's wait for the new homepage work to be done first to avoid migration issues.

I'm gonna remove this unplanned stretch ticket from this milestone.

**Comment by mmmavis** [comment]
I have bandwidth this sprint so I can work on this if it's something we still wanna do. @kristinashu ?

/cc @TheoChevalier This requires text changes. I will tag you on PR so you can verify that I don't break anything 😂

**Comment by kristinashu** [comment]
Yes please!

**Comment by mmmavis** [comment]
I filed a PR to change donation modal's default "dismiss link" text to `No thanks`. If there's a specific existing modal we want to update link text, we can always do it in the CMS.
