### ISSUE TITLE
Update `picture_ratios.html`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4924]
Clean-up work for the new homepage. This should wait until the new hero section is done to avoid code conflicts.

Let's update `picture_ratios.html` so it's generalized and not specifically built fo the existing homepage hero image.

---

1. Update `picture_ratios.html` so image sizes are passed as arguments instead of hard-corded.
2. Replace the following "picture" code with {% optimize_images page.quote_image %}

**Comment by KalobTaulien** [comment]
I looked into a few different methods for passing in arguments into the `optimize_images` template tag to make working with `pciture_ratios.html` easier, but nothing really stood out as "making it easier". It was either backend heavy with some math to autoscale different image sizes or frontend heavy where every include takes ~6 thumbnailing modes, which also doesnt seem very intuitive.

I think we could rename `picture_ratios.html` to `optimized_images.html` for better naming consistency, though. 

We could work with the template tag to auto generate image sizes for us, but it will become a bit more "magical" as it'd be backend heavy. The image renditions would be generated in the template tag instead of the template, and we'd pass in the image sizing/dimensions into this new template tag. And ideally we'd pass in just one size (the largest) and the smaller sizes could be auto-generated. 

Example:
```
{% optimize_images page.the_image fill-500x500 %} 
``

Then we could take the percentage of smaller images, like 75% of 500px is 375px. But then we get into text parsing for various methods (ie. width-* doesn't have a height) and error handling. This idea could get big pretty fast, whereas using the existing template code (or copying it and adjusting as needed) would be easier to work with, in my opinion. 

As always, more than happy to discuss this as the needs for this site may differ from my thoughts.

**Comment by mmmavis** [comment]
Closing. Looks like this isn't something we can find a good and easy to maintain solution for. Thanks for investigating it, @KalobTaulien .
