### ISSUE TITLE
[Frontend] News you can use

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#4940]
desktop

![Screen Shot 2020-07-29 at 12 52 43 PM](https://user-images.githubusercontent.com/177243/88846512-91d44d80-d19a-11ea-8320-7f7b3d17c2e1.png)

tablet

![Screen Shot 2020-07-29 at 12 52 57 PM](https://user-images.githubusercontent.com/177243/88846519-9436a780-d19a-11ea-81dd-e6f7e08f2812.png)

mobile

![Screen Shot 2020-07-29 at 12 53 37 PM](https://user-images.githubusercontent.com/177243/88846526-97ca2e80-d19a-11ea-8645-5849cdd6f227.png)
![Screen Shot 2020-07-29 at 12 53 42 PM](https://user-images.githubusercontent.com/177243/88846531-98fb5b80-d19a-11ea-9160-9044e76c67d3.png)

**Comment by mmmavis** [comment]
@Pomax I'm working on template code & styling for the blog author section in my Spotlight ticket. Once my PR is merged you should be able to add that section in by including the fragment.

e.g., 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/2896608/88827577-f97c9f80-d17e-11ea-9af6-c31e51fc79c1.png">

**Comment by Pomax** [comment]
@mmmavis @KalobTaulien I won't be able to finish this today, so I've assigned you both and whoever gets to it first can lay claim to the issue, and the associated PR 4993 =)

**Comment by mmmavis** [comment]
@KalobTaulien I'm gonna work on this ticket later today. 

Removing you from the assignee list.

**Comment by mmmavis** [comment]
👋 @taisdesouzalessa I have some design questions. Please see screencap below: 

<img width="926" alt="image" src="https://user-images.githubusercontent.com/2896608/89836417-93e3c800-db1b-11ea-90a3-22fad07443f5.png">

WIP PR [here](https://github.com/mozilla/foundation.mozilla.org/pull/4993) in case you wanna play around with the review app.

**Comment by taisdesouzalessa** [comment]
@mmmavis for the "News You can use" the blog title will have a limit of 80 characters (3 lines max) and the body copy should be no longer than 156 characters (3 lines too) as per [this comment](https://github.com/mozilla/foundation.mozilla.org/issues/4847#issuecomment-662028565)

Here is a mockup with the max limit:
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/22157921/89917201-60517e00-dbad-11ea-8a43-0e5cdb46679e.png">

• the white box should increase or decrease depending on the size of the copy, with the max limit as represented above
• if possible we should try to center align the white box with the image (that is why in the image above we have 10px distance top and 6px bottom (because the black line at the bottom has a height of 4px: 6px+4px=10px). If not possible, it is okay.

let me know if those guidelines help.

**Comment by taisdesouzalessa** [comment]
About the color of the h6, I am talking to other designers and I'll let you know soon.

**Comment by mmmavis** [comment]
@taisdesouzalessa thanks for the detailed reply. 

The "body copy" here is pulled from blog page's own "search description". By 156 characters do you mean we want to display at max 156 characters and append `...` at the end of the actual copy is longer? 

**A note about having a content-heavy + fixed height block:**
We can't really predict how many lines of text there will be considering localization, length of each word (if words are longer, the text will end up wrapping into more lines), and responsiveness.

> the white box should increase or decrease depending on the size of the copy, with the max limit as represented above

The image on the left will also need to decrease/increase in height. Otherwise, for some cases, the white box will outgrow the image. I can try vertically center the whitebox with the image. Will the minimun top and left margin be 10px each?

**Comment by taisdesouzalessa** [comment]
Hey @mmmavis sure, let's add the (...) if copy is longer than 156 characters

I see what you mean by not being possible to control the number of lines, thanks for the insight here. In this case we could go the route you suggested: ecrease the image on the left in height accordingly. 20px taller than the whitebox works. 

Do you think we can keep a min height as we have in the mockup though when the copy is small? So in case we have just a small copy we end up with something like this:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/22157921/89923481-87ac4900-dbb5-11ea-9f49-605fe1a0b448.png">

And not like this:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/22157921/89923738-e245a500-dbb5-11ea-97d5-ff78455f1ddc.png">

Does it make sense?

**Comment by mmmavis** [comment]
PR merged!
