### ISSUE TITLE
Add blog author photos

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5020]
Add blog author photos
- [ ] Gather key author photos for blog posts
- [ ] Add them to the site once the feature has launch

**Comment by taisdesouzalessa** [comment]
[Started a list](https://docs.google.com/document/d/1NBBtCffQJpmsX5RLWorYVFMnQfTxmY6pB11oldgMIQY/edit?usp=sharing) based on the latest people who posted on our blog/frequent authors. Also send them an email requesting pictures so we can populate the database.

**Comment by taisdesouzalessa** [comment]
Pictures added to the featured blog posts (homepage). Since we have the pictures we need for launch, I am closing this ticket. We received 8 pictures (linked in [the list](https://docs.google.com/document/d/1NBBtCffQJpmsX5RLWorYVFMnQfTxmY6pB11oldgMIQY/edit?usp=sharing)) and we can gather new ones as needed (depending on who we highlight for the homepage), but we got the basics covered with the list.
