### ISSUE TITLE
Publications | Publication page template exists

### ISSUE THREAD

**Issue by phildexter** [mozilla/foundation.mozilla.org#5071]
- New page template called Publication page
- Available as a child of any of the main wagtail pages
- Only child page available is chapter page
- Use blog page header and footer

### Acceptance criteria
This is just a basic ugly template that inherits the base template for the site, doesn't match specs. 

When a user visits a publication page, they see a basic template.

**Comment by easherma** [comment]
# Acceptance Criteria 
This is just a basic ugly template that inherits the base template for the site, doesn't match specs.

**Comment by easherma** [comment]
The IA is currently not fully settled. We'll go with defaults for now. 

* make a basic wagtail model for a publication page 
* make a basic template using the model
* look at inheriting/reusing blocks from other templates (blog template is mentioned as an example, which also uses modular_page.html, so I'll want to understand that setup)

**Comment by easherma** [comment]
Questions: 

* can we briefly explain the function of `ModularPage`, `PrimaryPage`, their intended use, whether there are elements of these pages we'd expect to incorporate for these publication pages? (i.e. I see some mixins that might be for metadata/preview links or maybe other stuff). Happy to update those with a docstring
* similar questions around the `modular_page.html` template.

**Comment by Pomax** [comment]
1. modular pages are an artifact from a previous iteration of the codebase, where it was the top level class for all page types. It is involved in a chain of `ModularPage` → `MiniSiteNameSpace`  →  [`CampaignPage` | `OpportunityPage`], where the minisite has logic for generating toc/menu systems for nested campaign and opportunity pages (the idea was a campaign or activity-opportunity would be a mini site within the larger site, with a root page, and arbitrarily nested pages).

2. Similarly, the template acted as a jumping-off point to extend for more specific page types. 

It's still "used" in the current codebase mostly because changing the class inheritance is a chore and a half, and even though we've had several moments where we could do code cleanup rather than responding to the needs of staff and external request, other cleanup has taken priority so far.
