### ISSUE TITLE
[Homepage QA Bug] Areas of Focus image sizing & font size

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5103]
Originally mentioned in https://github.com/mozilla/foundation.mozilla.org/issues/5050#issuecomment-679260694

- [ ] DESKTOP/TABLET/MOBILE - "Empower action" icon is smaller than others
<img width="746" alt="image" src="https://user-images.githubusercontent.com/22157921/91075503-08763680-e5f3-11ea-8eff-78de9778bcf1.png">

- [ ] MOBILE: "Our area of focus" title is 24px instead of 22px 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/22157921/91075598-2e9bd680-e5f3-11ea-9a2c-6539f3547d99.png">

**Comment by Pomax** [comment]
@taisdesouzalessa this looks like it's because of the images themselves not being all cropped to the same size. When I use these instead, things look fine:

![empower-action-icon](https://user-images.githubusercontent.com/177243/91082865-285f2780-e5fe-11ea-8ea7-833d4ed3129d.png)

![investigate-research-icon](https://user-images.githubusercontent.com/177243/91082866-285f2780-e5fe-11ea-88c9-b2e3d99a3461.png)

![connected-leaders-icon](https://user-images.githubusercontent.com/177243/91082864-27c69100-e5fe-11ea-8d92-0295547c2c72.png)

**Comment by taisdesouzalessa** [comment]
ahh thanks @Pomax - so no fixes need then. I'll adjust that on MY end :)

**Comment by mmmavis** [comment]
PR is in!
