### ISSUE TITLE
Add a section to the styleguide that shows off the bootstrap grid

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5132]
Just to show off the base grid breakdown, in a way that can be copied for use in sketch - at the very least col12 and 12 x col1? Would we need any other sizes for usefulness or would those two cover it?

/cc @sabrinang @mmmavis

**Comment by mmmavis** [comment]
For reference, this is how Bootstrap does it: https://getbootstrap.com/docs/4.0/layout/grid/
 I like how it lays out the breakpoints 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/2896608/92507545-02b84d80-f1bc-11ea-842e-c2c2d3efe620.png">
And maybe we can add those `extra small screen/ phone`, `small screen / phone`, `medium screen / tablet` ... keywords in the chart somewhere.
<img width="338" alt="image" src="https://user-images.githubusercontent.com/2896608/92507772-55920500-f1bc-11ea-9c0f-b518e0b724f3.png">


@sabrinang I've noticed some desktop mockups were designed on canvas for "extra large" screen instead of "large" screen. I'm not sure if this happens to all mockups in the master Foundation site Sketch file but we should make sure we use desktop canvas for desktop mockups in the future.

Happy to chat over Zoom on this further.

**Comment by sabrinang** [comment]
In our Style Guide.sketch file, we've been referencing these grid templates: 

**Grid / Extra Large (≥1200px)**
- width: 1110px
- number of columns: 12
- gutter width: 30px
- column width: 65px

**Grid / Large (≥992px=1024px)** 
- width: 930px
- number of columns: 12
- gutter width: 30px
- column width: 50px

**Grid / Medium (≥768px)** 
- width: 690px
- number of columns: 12
- gutter width: 30px
- column width: 30px

**Grid / Small and Extra Small (≥576px) - using 320px for mobile**
- width: 290px
- number of columns: 6
- gutter width: 30px
- column width: 23px

<img width="272" alt="image" src="https://user-images.githubusercontent.com/2492510/92535203-8f2e3480-f1eb-11ea-9b37-83b665475056.png">

Link to sketch file in abstract here: https://share.goabstract.com/a4054f68-5805-4cc1-83f3-1cea30e75b89?sha=7dbc886612215b9c9ce21b59978ffda768b63ebf

We haven't updated these so they may have followed some previous bootstrap version when we first made the style guide years ago.
