### ISSUE TITLE
PNI: homepage sketches 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5153]
Sketch out several options for the homepage. 

Benchmarks here https://github.com/mozilla/foundation.mozilla.org/issues/5245

### Goals of the homepage:
- Inform users what the guide is
- Show products in order of creepiness (and user to understand what that means - PNI home: clarify creepiness #4037)
- Show which products have the 'privacy ding' (and user to understand what that means)
- A way for users to find a specific product
- A way to highlight “All Star products"
- A way to add more and more categories to the guide (sub-nav is at max capacity)

### Possible filters include
- search bar
- product category filter
- all star products filter

I _think_ that if we keep products in order of creepiness then we don't need to filter by creepiness.

Goal for this sprint is to have the initial sketches, we can share them with devs and Jen in the following sprint.

**Comment by kristinashu** [comment]
I've put some of my initial thoughts in [this doc](https://docs.google.com/document/d/13SdWDZx7zBDK_vKjUogrzGoco10YSdErjLDzjLtsjbo/edit?usp=sharing).

**Comment by sabrinang** [comment]
I iterated on directions for the homepage in sketches and jumped in to turn them into digital mockups and cleaned up the file to build on. 

Homepage Option A: https://share.goabstract.com/8b35dce7-f8f8-4a7e-ba8c-fa2417911643
- Secondary navigation
- Clarifies creepiness with sort by not creepy to super creepy by default
- Clarifies privacy ding with hover tool tip and symbol
- Search helps users find specific product
- All star category
- Moving about and home icon reduces some sub navigation width


Homepage Option B: https://share.goabstract.com/dbe3aa68-17d2-4064-a9c9-eeb628ceb0b4
- Removed secondary navigation
- Speech bubble to help clarify creepiness
- Clarifies privacy ding with hover tool tip and symbol
- Search helps users find specific product
- Categories in drop down which includes all star
- More categories do not affect sub navigation since it is in drop down

I prepared a presentation to discuss two options for Monday’s check-in: https://docs.google.com/presentation/d/1-iaPgIvrXPv-4Qbr9CaAfmoqpJ724vubjJ--EikGV1E/edit?usp=sharing

I also have prototyped separate artboards if we want to show clickable flow in sketch.

**Comment by sabrinang** [comment]
@kristinashu Design review that the presentation and abstract share links are ready for our homepage design check-in this afternoon?
