### ISSUE TITLE
Merge Dependabot Pulls (JavaScript dependencies)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#5189]
https://github.com/mozilla/foundation.mozilla.org/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies+label%3Ajavascript

**Comment by mmmavis** [comment]
I've merged all open JS dependabot PRs except this Sentry one: https://github.com/mozilla/foundation.mozilla.org/pull/5207 @cadecairos @Pomax can you take care of it? It doesn't seem to mention any breaking changes. But since I don't know how Sentry was set up, it's better to let someone who does to take a look at the PR. 😄
