### ISSUE TITLE
Page anchors aren't working 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5192]
Adding a page anchor isn't working. 

I've added two links at the top of https://foundation.mozilla.org/en/what-we-fund/directory/ but they don't work.

Links were creating using the anchor option (tried both with and without the #)
![image](https://user-images.githubusercontent.com/1068783/92533946-6b1d2400-f1e8-11ea-82be-7b6fe6b1edd9.png)

Links with the anchor e.g. https://foundation.mozilla.org/en/what-we-fund/directory/#fellows-by-year look like they would work but they don't.

**Comment by Pomax** [comment]
It turns out the problem was that the heading had additional markup that made the heading itself a link to somewhere else, in which case the automatic linking code we're using cannot kick in. https://foundation.mozilla.org/en/docs/how-do-i-wagtail/creating-anchor-links/ describes the process, but the short version is:

- mark up headings with the h2/h3 buttons, and do nothing else to them
- to then link _to_ those headings from somewhere else (e.g. hyperlinked words in a text somewhere else on the page) you can create a link to that heading's `#heading-id-string`, which gets auto-generated by the cms
