### ISSUE TITLE
PNI: improve UX of the Related Products selector in the CMS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5194]
Currently the selector shows ALL the products, which is hundreds. It makes selecting four for every product page very time consuming, and frustrating.

Is it possible to only show the most recent products (i.e. products added within the last ~ 6 months)?

Screen cap from CMS
<img width="591" alt="image" src="https://user-images.githubusercontent.com/1068783/92556570-2496ec00-f21f-11ea-98b6-c6b967d13005.png">

**Comment by Pomax** [comment]
If @caltrider can specify what a useful cutoff metric is, we should be able to add that in, although I would imagine things to be a little more complicated than that as some related products will be from way back when (e.g. a new Apple product being related to one that was part of the very first release of PNI), suggesting it probably requires us figuring out how to add filtering to an admin page, rather than hardcoding a date filter.

**Comment by cadecairos** [comment]
@caltrider can you respond to the above question?

**Comment by kristinashu** [comment]
What rule do we use for the homepage? It only shows "recent" products. The same rule could probably apply to this selector. If I had to pick a number tho, I would say show products that have a review date within the last 11 months.

**Comment by caltrider** [comment]
Agree with @kristinashu. Anything within the last 11 months sounds good. We'll learn how this goes with year-round PNI, but for this version of the guide, I will only use related products that have been reviewed for this version of the guide. Everything is now officially out-dated. So the 11 month time frame works.

**Comment by Pomax** [comment]
I've set it to "anything from 2020 or after", and finally managed to add in logic that'll also alphabetically sort that list, so that it's (a hell of a lot easier) to find the thing you want to crosslink to.  Review app is currently building.
