### ISSUE TITLE
Update default pages created by load_fake_data

### ISSUE THREAD

**Issue by cadecairos** [mozilla/foundation.mozilla.org#5204]
Current nav:

- Who we are (primary page)
- initiatives (initiatives page)
- news  (news page)
- What you can do (Participate page2)
- style-guide (styleguide)

Should be:

- Who we are  (primary page), already in place
- What we do (banner page), does not exist
- What you can do (Participate page2), already in place
- Blog (blog index), exists but needs to be put in the nav

Tasks:

- [x] create "what we do" fake_data page
- [x] update fake data so that "what we do" and "blog" links show_in_menu
- [x] update fake data so that old pages no longer show_in_menu

Question marks:

- [ ] ~remove initiatives page?~
  - [ ] ~remove all code for this?~
- [ ] ~remove news page?~
  - [ ] ~remove all code for this?~

**Comment by Pomax** [comment]
@kristinashu are we keeping the initiatives and news pages, or should those get cleaned up (probably in a separate issue, if so)

**Comment by kristinashu** [comment]
Initiatives will go away but design still has some work to do. Content of the news page will also go away but design needs to check with Kevin first (and then we're going to update the "blog" name to "news" - this was based on the IA refresh work. I believe most of this url work by design will be done in https://github.com/mozilla/foundation.mozilla.org/issues/5068.
