### ISSUE TITLE
"Insights" topic updates

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5205]
Follow-up on #4848 and based on [this doc](https://docs.google.com/document/d/1cjvoU2fVqLnY7lGHNsBtrIBRTuiRZp8S3sXT6W2BPZg/edit?usp=sharing) we need to:

- [x] **Edited by Taís**:  after talking to Insights team, it seems they have to figure out some things internally before having a unified hub with other teams. My proposal was to do a phased approach: stage 1 is to have a hub just for them, called Insights as in the original plan proposed by Kristina but in the meantime they keep in mind the stage 2 and do the discussions that need to happen for us to achieve this second stage, which would be a one-stop-shop for all things research (the ideal solution). cc: @kristinashu 

The items above have to be solved before the items below:
- [x] Update the IHR blog category to `Insights`  > To be done by **Kristina**, who has the privileges
- [x] Once item above is done, redirect this URL foundation.mozilla.org/blog/category/internet-health-report
- [x] Create the parent page at [/insights](https://foundation.mozilla.org/en/insights/)
- [x] Hand off /insights to Eeva to populate with content
- [ ] Get the green light from Insights team that the page is ready to go and we can do the redirects
- [ ] Move relevant URLS and set up redirects
- [ ] Add link to https://foundation.mozilla.org/what-we-do page
- [ ] Is that everything? 

**Things to keep in mind (edited by Taís):**
• MVP version, do versions with what is available in Wagtail
• This is a team hub so it makes sense to align it with language of other hubs (Fellowships and Awards) for instance
• Insights is a broader hub (broader than IHR, or data futures, it encompasses them all)

**Comment by taisdesouzalessa** [comment]
> have a conversation with Insights team to see if they are open to the idea of a hub for research (shared w/ all things research at Mozilla, like "Trustworthy AI" paper). This conversation is an opportunity to raise challenges and uncover blindspots. 

Sent a message to Eeva and Kasia via Slack and they will discuss this item in their 1:1 and follow up with us once they have reached a team decision.

**Comment by taisdesouzalessa** [comment]
Moved this ticket to current sprint

**Comment by taisdesouzalessa** [comment]
Met with Eeva and got the info I need to start this project. Brief here:
https://docs.google.com/document/d/1ofQRfw8rznX_6JEBXt-jCSXZmVAL5iBtrieEKMCKt0U/edit?usp=sharing

**Comment by taisdesouzalessa** [comment]
**Eeva:**
Here is the published hub (since it's not linked from anywhere on our site yet, I don't expect much traffic for now). Feel free to do edits on Wagtail there.
https://foundation.mozilla.org/en/insights/

Here is a version of it with my comments (feel free to add yours and your team's there) - I feel it is easier if we have notes on pages for quick alignment.
https://mozilla.invisionapp.com/share/BEZHKC3N57H#/438269978_Overview

**Next steps:**
- [ ] Eeva, please ping me if you need any design help and let me know once your team had the opportunity to give feedback on this page, so I can act on it.

Once the item above is unblocked by the Insights team, we can:
- [ ] Move relevant URLS and set up redirects
- [ ] Add link to https://foundation.mozilla.org/what-we-do page

**Comment by taisdesouzalessa** [comment]
I'll break this ticket in 2 as I expect feedback won't be completed this sprint.  #5676 is the follow up ticket. Closing this one.
cc: @jamilasnell
