### ISSUE TITLE
Run the page revision history conversion command for wagtail 2.10 on prod

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5266]
Wagtail 2.10 changed how the history works, and the old revision records need to get converted to the new type.

https://github.com/wagtail/wagtail/pull/6084/files#diff-3c513306b75bdbdd1867560a3f20e280

**Comment by KalobTaulien** [comment]
I dumped the staging db into my local docker container and ran `python manage.py create_log_entries_from_revisions`. It took a little while to execute, it's certainly a slow task so be careful if there are any timeout limits with our hosting. 

Otherwise, it looks like it worked out as expected. I'd say it's safe to run this management command on production.

**Comment by Pomax** [comment]
sweet @cadecairos we'll probably want to schedule a day/time where we can safely run this command, with the site set to maintenance mode while it runs.

**Comment by cadecairos** [comment]
We should be able to execute this on a one-off dyno - they don't time out until 10 minutes of I/O inactivity iirc.

I can schedule a task in for me to execute this on this coming Monday morning.

**Comment by phildexter** [comment]
Remember to prod push first!

**Comment by Pomax** [comment]
prod push has been effected, @cadecairos shall we run this tomorrow (wednesday) morning?
