### ISSUE TITLE
Open Letter Graphic 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5333]
### Describe the feature request
Ashley is talking with MoCo to see if this request can come out of the unfck campaign budget. If not, then we would be tasked with creating the creative (tbd what the creative would be). Will know by 9/29 if we need to work on this and what the creative would be. Needs to be completed by 10/2!!

### Screenshots / mock-ups
[Link to the letter](https://docs.google.com/document/d/1MSavEzYL0PZ4FUavq_4zrPi0-PLYSIkUGdpHuqNa6qA/edit)

**Comment by jamilasnell** [comment]
Checking in with Ashley tomorrow (9/30) to ask about this! Please stay tuned...

**Comment by jamilasnell** [comment]
@kristinashu Talked to Ashley on 9/30 and she is going to add me to an email with the PR team. Will have updates on 10/1 on if we can help them or not!

**Comment by natalieworth** [comment]
Hey @jamilasnell is there a brief or more context for this tic/ what they need specifically for a graphic?

**Comment by jamilasnell** [comment]
@natalieworth For this request, there are two things needed: an open letter graphic that would just be a header design, logo and style (can copy this: https://redpen.io/p/yf3b915353ab29c887
Additionally, they want a mock up add that would be used for twitter campaign. It would look like a petition but using fake names (First name, city). I believe it would be a call to action for users to sign the petition. 

This is due on Monday, Oct. 12th so I believe that Kristina can help as well once she is back on Thursday!

**Comment by kristinashu** [comment]
@jamilasnell do you have dimensions and specs for the ad?

Is there someone on the advocacy team Nat could talk to to get a better idea for the Twitter campaign?

**Comment by kaili09** [comment]
Specs are:

12" wide x 21" high in PDF format[2020 Washington Post Print Ad Specs.pdf](https://github.com/mozilla/foundation.mozilla.org/files/5367720/2020.Washington.Post.Print.Ad.Specs.pdf)

**Comment by sabrinang** [comment]
@kaili09 Please review redpen here: https://redpen.io/p/vpd7572a00d0b185c2
- approximately fits 486 signatures _(depending on how long the last names are it may be less)_
- I included a heading "An Open Letter to Facebook & Twitter"

**Comment by sabrinang** [comment]
I updated [redpen](https://redpen.io/kyfd95bb83d58b7e2f) from comments and zoom'ed with Ashley to confirm adjustments.
I've exported the files and working file in gdrive here: https://drive.google.com/open?id=1A1uXYVh8uQaZLQWG_3m2BfHY6bl8pfDS&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

I'll be getting finalized first/last signature names by Friday.

**Comment by sabrinang** [comment]
**Ashley has given an update on this and has got more clarity from Mark too:**

There's a more fundamental change conceptually to get this ad noticed as this will be an inside ad on Tuesday instead of a back cover ad so we need to have more eye-catching wow factor.

- concept to fit more names and use streaming names as the background to frame the text of the open letter
- ensure we can still read the names
- have large mozilla logo by the bottom
- make citation less emphasized _(indented or make it less obvious it is a citation)_
- iterate on making letter itself less wide but try the letter proportion concept _(try versions of heading inside or on top)_

**Examples Ashley gave and sketched:**

<img width="250" alt="firefox ad example" src="https://user-images.githubusercontent.com/2492510/96192220-6ee44a80-0efa-11eb-93f6-54d1a18f854d.png"><img width="250" alt="ashley sketch" src="https://user-images.githubusercontent.com/2492510/96192215-6db31d80-0efa-11eb-9dbc-cf51ddbbbc5f.jpg"><img width="250" alt="blm ad example" src="https://user-images.githubusercontent.com/2492510/96192299-99360800-0efa-11eb-90fd-0fc72abf32ba.png">


**DUE Oct 19th Monday 1pm PT but have draft by Friday**

**Comment by sabrinang** [comment]
I got some additional [advertisement slug guidelines](https://github.com/mozilla/foundation.mozilla.org/files/5393183/cid5E1ABC58-2701-4159-A689-5EA4E5A200C5.pdf) fro Kaili and iterated on the name frame concept 

Redpen here to collect feedback: https://redpen.io/ob6c5d8ab7ecab5ef6
- advertisement slugs included
- can fit ~1675 names but first/last names need to be cleaned up (after the first 1000)
- I'll try to adjust narrow justified spacing after design as been approved

**Comment by sabrinang** [comment]
Made a few iterations today for open letter design and proportions from feedback. Working closely with Ashley/Kaili and got finalized, clean list of names for background. 

Updated redpen here: https://redpen.io/ob6c5d8ab7ecab5ef6
Exported to gdrive as well: https://drive.google.com/open?id=1A1uXYVh8uQaZLQWG_3m2BfHY6bl8pfDS&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

**Comment by sabrinang** [comment]
Updated 'U.S.' copy and signatures. Ashley signed off, sent to Kevin/Kaili to be distributed to press and print.
Both [redpen](https://redpen.io/ob6c5d8ab7ecab5ef6) and [gdrive](https://drive.google.com/open?id=1A1uXYVh8uQaZLQWG_3m2BfHY6bl8pfDS&authuser=sabrina%40mozillafoundation.org&usp=drive_fs) links have been updated with revised files.
