### ISSUE TITLE
"What you can do" page: hero section

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5336]
### Describe the bug
The current hero section of the What you Can do page has a duplicated image: one on top (like a banner) and one behind the copy. The screenshot below is from staging but issue is also happening on prod:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/22157921/94512512-0b0b1380-01d1-11eb-9da5-5a7ba5b98a9f.png">

### To Reproduce
1. Go to '[https://foundation.mozilla.org/en/what-you-can-do/](https://foundation.mozilla.org/en/what-you-can-do/)'
2. Use the "Responsive Design Mode" > iPhone 5 (or 6/7/8)
3. See bug

### Expected behavior
When this page was built, the expected behavior was to have only the top banner.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/22157921/94512767-be740800-01d1-11eb-8493-888d3f4943c3.png">

However, since we evolved the homepage to have a full width banner behind the copy on mobile, it makes more sense we replicate the same behavior for this page as the screenshot below for 2 reasons: 1. consistency and 2. to push the content up in the page
<img width="318" alt="image" src="https://user-images.githubusercontent.com/22157921/94512436-dd25cf00-01d0-11eb-9a59-9d055ef47276.png">

### Additional context
@kristinashu @sabrinang @natalieworth: if you have any strong opinions/concerns in having this hero behaving the same as our homepage (as I am suggesting), please let's chat before engineers solve this bug. I'll tag it as only design for now so we can discuss it if needed. If you all agree, please give a thumbs up to this thread so I know we're all aligned. Thanks!

**Comment by Bhavik-Ardeshna** [comment]
@taisdesouzalessa I am ready to work on this issue 
Plz guide me :)

**Comment by mmmavis** [comment]
Hi @Bhavik-Ardeshna thanks for offering help. Our team doesn't have the bandwidth to provide full support to contributors at the moment. However, if you are already familiar with the codebase and our tech stack, please start tackling this ticket. This will be a good starting point: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/static/participate_page2.html#L10-L19

We are aiming to get this bug fixed by Feb 1 so let me know if you'd like to take on this ticket :)

**Comment by mmmavis** [comment]
@Bhavik-Ardeshna as our current sprint is gonna end soon, our team will start working on this ticket. Thanks again for showing interest!
