### ISSUE TITLE
PNI: localize fields

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5338]
As part of the revised l10n plan, let’s hook up all CMS fields for localization using the system already in place, wagtail-modeltranslation

https://docs.google.com/document/d/1RunBlPOJ7m-KfIDwazBHL3EO6Di1MQtj9pqtTDpdZwg/edit?ts=5f7226fd#heading=h.g8i1bgv9jn4e

**Comment by KalobTaulien** [comment]
Hey @TheoChevalier I requested access to this doc. I'll take a look at it tomorrow morning

**Comment by TheoChevalier** [comment]
> Hey @TheoChevalier I requested access to this doc. I'll take a look at it tomorrow morning

Thanks @KalobTaulien! You should be able to access the doc now. You’re welcome to take over this PR/branch https://github.com/mozilla/foundation.mozilla.org/pull/5339

The remaining issues (I tagged you in the doc):
- Fields are duplicated for some class (e.g "name" and "name [en]"), even after running `inv l10n-sync` and `inv l10n-update`.
- Localizing the "label" field in the `ProductPrivacyPolicyLink` class doesn’t work at all (the privacy policy link panel appears empty in the admin panel)

**Comment by KalobTaulien** [comment]
Hey @TheoChevalier I don't see the duplicate fields you mentioned. 

![image](https://user-images.githubusercontent.com/4743971/94831982-9ac7e200-03ca-11eb-9ff0-e33b2ec92886.png)

Though that's normal to have a `name` and `name_en` field when translating because as far as I can tell when we make a new env with `inv new-env` (or `inv new-db` it applies some raw SQL to add columns to tables.

**Comment by KalobTaulien** [comment]
I've added in the label translations for `ProductPrivacyPolicyLink` 

![image](https://user-images.githubusercontent.com/4743971/94835624-2e031680-03cf-11eb-96b3-e286be210c70.png)

The fix here was adding `panels = [...]` to the Orderable model. I also removed the inherited `models.Model` class because `Orderable` already extends from `models.Model`

**Comment by TheoChevalier** [comment]
Thanks a lot for fixing `ProductPrivacyPolicyLink` !

> Hey @TheoChevalier I don't see the duplicate fields you mentioned.
> 
> ![image](https://user-images.githubusercontent.com/4743971/94831982-9ac7e200-03ca-11eb-9ff0-e33b2ec92886.png)
> 
> Though that's normal to have a `name` and `name_en` field when translating because as far as I can tell when we make a new env with `inv new-env` (or `inv new-db` it applies some raw SQL to add columns to tables.

In the DB, right, I think it’s indeed expected for `name` to stay there, but in the UI, here for instance, we should just see the two [en] fields:

https://foundation-s-v4-cms-l10-mjaap1.herokuapp.com/cms/buyersguide/buyersguideproductcategory/edit/7/

Note that this only happens with the `Category` class
(Also happening with the `Updates` class, but right now, I think it’s not worth translating this at all)

<img width="575" alt="Capture d’écran 2020-10-01 à 19 30 20" src="https://user-images.githubusercontent.com/1294206/94843126-2dd93a00-0414-11eb-9e98-e0efe701de0f.png">

**Comment by KalobTaulien** [comment]
Dev note: we're going to re-create this branch with a cleaner commit history so we can test why `inv test-python` fails using `git bisect`. 

☝️ I'll do that tomorrow morning and re-set the connected PR to this ticket.

**Comment by KalobTaulien** [comment]
Closing this issue in favor of #5442
