### ISSUE TITLE
PNI: Improve UX of the Updates section

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#5390]
Jen's feedback after our CMS run through on Oct 5.

Improve UX of the Updates section to that it only show recent updates as an option (similar to the what was done to the Related Products section)

**Comment by Pomax** [comment]
Pending a nicer interface for selecting cross references, this will use the same approach as the related products, but filtering out any update before 2019-01-01, effectively cutting out any update that is 2 near-or-over years old.

**Comment by Pomax** [comment]
This will also require adding a factory for creating and crosslinking fake product updates, so that the functionality can be reviewed

**Comment by Pomax** [comment]
@kristinashu @caltrider It turns out we do not have any date information stored in product updates, and so we can't filter based on "recent"ness.  We can add some kind of "save whatever date it is when an update gets first saved", but that won't really let us do any time-based filtering for existing updates, nor would it let us do any meaningful filtering until 1 or 2 years from now. 

Is there any other (combination of) properties (looking at https://foundation.mozilla.org/cms/buyersguide/update/edit/157 etc) that can be used to sort the list a little better at least, pending figuring out how (...if?) to get a nicer "all <-> include" two column picker interface set up instead of the current multiselector?

**Comment by caltrider** [comment]
@Pomax Hmm...I guess since date added is really kinda the most meaningful thing to filter by, adding in the "date added" would eventually help us out. In the meantime, I suppose doing alphabetical order is probably the best we can do for finding new or existing updates. The only other thing I can think of would be product mentions but there's no certainty the product name will always be in the update title.

**Comment by Pomax** [comment]
I'll file a separate issue to add fields that allow tracking date-entered for updates, and then set this one to at least sort alphabetically.
