### ISSUE TITLE
PNI - define analytics for PNI homepage

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5426]
Define what events should be tracked.

**Comment by taisdesouzalessa** [comment]
**Started a list with things to consider:**
- [ ] "submit a product" button tap
- [ ] ding checkbox
- [ ] search box (which terms people type there? Do people use the box?)
cc: @sabrinang @natalieworth - added those based on our[ Analytics doc](https://docs.google.com/document/d/1oWwHlyreicHybrXudDocclclWfef0m1hyUsob6FyL8w/edit?usp=sharing) - anything else missing you think it is important for us to measure?

**Comment by sabrinang** [comment]
Yeah those are good things to measure. Only other thing on the homepage I can think of is "category navigation" and how often they are clicked (perhaps to show which ones are more popular etc)

**Comment by taisdesouzalessa** [comment]
[List of events here](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit?usp=sharing). Tab "Buyers Guide", lines 17-20.

@mmmavis I have some questions there for you and we can meet next week in case you have any questions.
@sabrinang after some thinking I decided not to add events to the nav items because if we want to know pageviews for each category we can see it by looking at URL traffic via GA, does it make sense?

**Comment by taisdesouzalessa** [comment]
I think this is done in term of defining actions. Not closing this until I have the opportunity to discuss the items with Mavis, though.

**Comment by taisdesouzalessa** [comment]
Talked to Mavis and we're aligned on those. @mmmavis can I close this ticket?

**Comment by mmmavis** [comment]
Yup!

Closing it now!
