### ISSUE TITLE
PNI - Share Button Research

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5494]
Research incorporating share buttons _(or other mechanisms)_ to PNI to help the 2020 goal:
**10% more mention/shares on social media**

We can assess any baselines or benchmarks we previously had related to this.

**Comment by taisdesouzalessa** [comment]
Problems this research is trying to solve: 
• Basically, PNI doesn't have any share buttons (unless you vote). Should it?
• Are share buttons effective for this type of project and audience? (edited) 
• If so which types?

**Comment by taisdesouzalessa** [comment]
@sabrinang @kristinashu here is the conclusion of the research:

- People use the button “copy link and share” more frequently than the “share” button hidden under “vote” (in 2019, the conversion rate for “Copy Link Tap” was 0.19% vs the “Share” under vote, which was 0.11%). This makes sense because there is a barrier for people to share (they may even not know “share” exists until they decide to vote.
- The easier we make for people to share (and set some “reminders” through the site), the more likely it is they will share. Having share buttons on PNI guide may help us make the guide even more popular on Social Media channels (we see traffic from Social being around 10-11%) so there is an opportunity to increase their slice of the pie.
- All of the benchmarks researched showed visible share buttons on the interface.
- According to our Google Analytics, Facebook and Twitter are popular social media sites bringing traffic to our PNI pages. We also see those 2 social media buttons in our benchmark. That makes them the ideal candidates to be present in our site. We do see LinkedIn emerging as a potential Social media platform for us in 2020 and it would be good to consult with Audrey if she sees value on exposing this button on the interface.
- We may be careful to not pollute the interface and deviate from the main goal that is to inform people. For this reason the recommendation is to add the share button either in the middle or bottom of product pages. From the main page, we could ask people to share the guide at the end of the page - the challenge here is to find the right opportunity for this type of ask.

Full research on this doc: https://docs.google.com/document/d/15_MV1yhuiHwq5j_ZzUGIu6OPIqmEhqqvFTFtwxra10c/edit?usp=sharing

If you both agree with this report, we should file a ticket to find a placement for the social media share buttons + discuss with Audrey if she thinks LinkedIn (or any other social media) may be appropriate too.

**Comment by sabrinang** [comment]
Great thank you for the range of research Tais! :+1: the next steps sound good to me too

- great points, I was concerned too that when we removed the “copy link and share” we were removing the only visible share mechanism and makes sense hidden buttons are a barrier
- I like this overview of benchmarks from others too that relates into the recommendation of incorporating share near the end after they have seen the value of the guide and to not take away from the focus of informing people first
- +1 of incorporating reminders throughout the site perhaps it can be done with copy as to not pollute/distract the interface with too much either
- Helpful seeing stats which channels are the largest so far (yes interesting to look into linkedin potential and the audience it could bring, not sure how we could bring insta more)

**Comment by taisdesouzalessa** [comment]
Thanks for the feedback here, @sabrinang and for initiating this research, the prompt questions helped me to explore the issue in a deeper way. 
I tried to summarize this ticket in the next step, adding your contributions (#5716). Can you please take a look at it and make changes if needed? I assigned us both and asked Kristina and Jamila's help on triaging it.
