### ISSUE TITLE
[MozFest] Add link to footer

### ISSUE THREAD

**Issue by marcwalsh** [mozilla/foundation.mozilla.org#5503]
The top nav of the MozFest website is getting a little crowded. 

Would it be possible to move the Become a Sponsor (https://www.mozillafestival.org/en/sponsor/) to the footer?

**Comment by kristinashu** [comment]
@marcwalsh hey, did you still want this done? I can try putting it in an upcoming sprint.

**Comment by marcwalsh** [comment]
I'll double-check with Jesse W and make sure - but we'll need the space for the tickets and schedule early next year so it might be good to just get done. 

I'd also be interested to see how difficult the code change is - I tried it myself and found the file in the repo that contains the footer where I can add additional links, but I wasn't sure if there's more involved.

**Comment by taisdesouzalessa** [comment]
@marcwalsh did you have the opportunity to check it with Jessie W?

For context, this top nav element doesn't receive too many clicks (only 1% of the traffic clicked there = around 120 clicks from Oct 12, 2019 - Nov 24, 2020) and it has a very specific audience (not the general one) so from the UX perspective, it makes more sense to move it to the footer, as you recommended.
I would also suggest you add a "Become a Sponsor" copy blurb on "Get Involved" page (at the end of it) because this seems a spot where people would look at if they want to sponsor the event.
<img width="1593" alt="Screen Shot 2020-11-24 at 11 13 47 AM" src="https://user-images.githubusercontent.com/22157921/100140736-34999180-2e46-11eb-8d3b-1de1fb46b239.png">


Here is how the footer would look like (desktop) and I would recommend we loop in an Engineer to do the implementation so we make sure the localization needs are addressed and the code is clean :).

<img width="1319" alt="Screen Shot 2020-11-24 at 11 12 49 AM" src="https://user-images.githubusercontent.com/22157921/100140621-12077880-2e46-11eb-8131-c5a693b4e7d2.png">

**Comment by kristinashu** [comment]
Excellent recommendations, thank you Tais!

**Comment by taisdesouzalessa** [comment]
Checked with Marc and this project is good to move on. Will do the mockups and create the implementation ticket.

**Comment by taisdesouzalessa** [comment]
- [Here are the mockups](https://share.goabstract.com/5bea23cc-eee3-4a86-972c-d57c41891d2b?collectionLayerId=bc33fe87-ea1f-4378-b0f1-3ccd9c6e70e8&mode=design) on Abstract (second row - MozFest footers)
- **Implementation ticket here:** #5737
