### ISSUE TITLE
[PNI] - Implement Link Preview Image (OG Image) 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#5537]
Corresponding engineering ticket that implements designs from https://github.com/mozilla/foundation.mozilla.org/issues/4593

Assets are here https://drive.google.com/open?id=14-8OR8iuFRythRhXVnO99CQWtmMv_kMG&authuser=natalie%40mozillafoundation.org&usp=drive_fs

Todo
- [x] Homepage, Best Of, and About pages should have the general graphic
- [x] Each category will have it's own unique graphic

**Comment by jamilasnell** [comment]
@sabrinang is this image available yet? Please let us know when this image is here so we can proceed with this task. Thank you!

**Comment by sabrinang** [comment]
@jamilasnell No, design issue is blocked - Natalie mentioned they sent last round of feedback to contractor so should have them today or tomorrow.

**Comment by mmmavis** [comment]
Updates:

Had to merge my original part 2 PR #5632 today because we wanted to land it ASAP. However, og:image on category pages were still showing the old og image on staging and I couldn't find a good fix to it. We've landed #5647 as a temp solution so all PNI pages show the same, new generic og:image.

I'm working on a fix (PR #5636, WIP) and will most likely need help from other engineers to figure out the wrong image location issue.
