### ISSUE TITLE
Investigate making the slug field non-localizable

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5633]
We need to remove the ability to localize slugs, as it’s breaking locale negotiation and causing various other issues like thumbnails not being displayed in the /blog page.
From an earlier discussion with Cade, it was also causing issues when copying pages.

It used to be okay-ish when I was the only user publishing localized content, but:
- it’s not the case anymore
- Wagtail now quietly auto-populates the slug fields for locales when you input a title. Which is definitely nice when you actually want localized slugs

I believe we don’t have any page using localized slugs, but we may want to double check by running a SQL query

**Comment by TheoChevalier** [comment]
Ok, not as straight-forward as I thought it would be. Looks like slugs are localizable by default in wagtail-modeltranslation, so I have no clue how to override this. Removing estimate and unassigning myself

**Comment by Pomax** [comment]
yeah, this is not something we added, but something that becomes enabled because of wagtail-moderltranslation. However, we can certainly ask on their issue tracker whether it's possible to get a settings var like `WAGTAIL_MODELTRANSLATION_NO_AUTO_SLUG_LOCALIZATION` (but then not as crazy long =D) so that the only change on our end would be to turn that flag on.

@KalobTaulien any thoughts here?

**Comment by TheoChevalier** [comment]
wagtail-localize will allow us to do this easily, this ticket is superseded by #6031
