### ISSUE TITLE
[bug] When we use the word "News" in H2 or H3, it seems to break the page.

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/foundation.mozilla.org#5635]
Whenever I use the word "News" in H2 or H3, it seems to bring back an old layout on top of the existing one.

To Reproduce the bug:
1. Go to the page "News", inside the hub "Mozilla Insights"
2. In the Body copy change the title "Mozilla Insights News" and replaced it by "News" (keep it as H2)
3. Publish the page

Here is a gif that may be helpful
![news-bug](https://user-images.githubusercontent.com/22157921/99107010-08565900-259a-11eb-8124-d42eaa388ec3.gif)

cc: @jamilasnell - I didn't assign any engineer to that, tagging you for triage.

**Comment by KalobTaulien** [comment]
This is likely a CSS issue. Headings tend to come with an ID. So **News** would look like:
```html
<h2 id="news">News</h2>
```

Chances are we have a `#news` CSS selector somewhere. Though I can take a deeper look at some point.

**Comment by Pomax** [comment]
This looks like it's being caused by wagtail having changed the HTML it generates from streamfield body text blocks. Our code relies on the tags being "bare" (e.g. just `<h2>`) to which we manually add the `id` attribute, but the newer wagtails already include the `id` attribute, so we'll need to change https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailcustomization/templatetags/wagtailcustom_tags.py

**Comment by Pomax** [comment]
Nope, this is entirely unrelated to that: it's caused by this file: https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/foundation/inject-react/news.js

Which looks for _anything with id="news"_ and turns it into a `<News>` element, no matter what page you're on. Time to change that.
