### ISSUE TITLE
Travis-ci Migration 

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5685]
### Describe the feature request
Travis-ci.org is shutting down on December 31, 2020 and merging into travis-ci.com - we want to move all our repos over to Github Actions.

- [x] foundation.mozilla.org
  - [x] node
  - [x] wagtail
  - [x] cypress/percy
  - [x] turn off travis integration on travis.org
  - [x] turn off travis integration in the branch protection settings
- [x] donate-wagtail
  - [x] turn off travis integration on travis.org
  - [x] turn off travis integration in the branch protection settings
- [x] network-pulse
  - [x] turn off travis integration on travis.org
  - [x] turn off travis integration in the branch protection settings
- [x] network-pulse-api
  - [x] turn off travis integration on travis.org
  - [x] turn off travis integration in the branch protection settings
- [x] mofo-redirector
  - [x] turn off travis integration on travis.org
  - [x] turn off travis integration in the branch protection settings

`fomo-l10n` and `donate-l10n` work will be tracked in https://github.com/MozillaFoundation/mofo-devops/issues/810

maintenance page deployment to be tracked in https://github.com/mozilla/foundation.mozilla.org/issues/6018

**Comment by TheoChevalier** [comment]
(Copying over from #5919)
Just saw #5918, and realized we will need to migrate from Travis for the l10n repos as well, otherwise localization will be totally broken.
We’re currently relying on Travis CI to:

    Generate a translation package and upload it to S3 for Wagtail consumption
    Run checks on translations at each commit to raise errors via mofo-pontoon-check

We’re doing that for both the foundation site and donate:

https://github.com/mozilla-l10n/fomo-l10n/blob/master/.travis.yml
https://github.com/mozilla-l10n/donate-l10n/blob/master/.travis.yml

**Comment by Pomax** [comment]
@TheoChevalier do you know who owns the "mozilla-l10n" org? Because they will have to rewrite their travis yml to github actions yml, too.

**Comment by TheoChevalier** [comment]
That would be @flodolo, but I'm not sure I understand what's actually needed at the org level...

**Comment by flodolo** [comment]
As far as I'm aware, we have very little remaining on Travis (a handful of PHP projects, for which I still need to figure out the migration to GitHub actions).

Having said that, my understanding was that it's not completely shutting down? Is it a problem with permissions on the new travis-ci.com?

**Comment by TheoChevalier** [comment]
> Having said that, my understanding was that it's not completely shutting down? Is it a problem with permissions on the new travis-ci.com?

No, the only issue is it’s not free anymore (because the foundation site repo runs a lot of CI), and it looks like if we have to pay for CI, we’re going to pick Circle CI instead.

Looks like the plan for the foundation website is to temporarily migrate to GitHub actions before the end of the month, then properly migrate to Circle CI next year when we have more time to prepare.

For the localization repos, I think the free plan on travis-ci.com may still be enough for now? @Pomax what do you recommend we do this month and longer-term?

**Comment by flodolo** [comment]
> Because they will have to rewrite their travis yml to github actions yml, too.

Just re-read this part. My team didn't work on this, it was done entirely by MoFo folks. We're only hosting localization repos because it's easier and more convenient to manage them (e.g. set up Pontoon access).

My personal suggestion would be to go with GitHub Actions. The only part to figure out is the upload to S3 ([this might be relevant](https://github.com/marketplace/actions/s3-sync)). 

All other repos that we manage have been migrated to GitHub actions, and both Python and PHP have been proved really easy to set up.

**Comment by Pomax** [comment]
we've already moved the foundation CI to github actions, so if the mozilla-l10n repos still work then: that's great, but the mofo eng. team does not own them, and we don't control whether they _keep_ working, so whoever owns them will have to make a decision on how to move forward =)

**Comment by flodolo** [comment]
> the mofo eng. team does not own them

To be extremely clear, neither does my team. Who owns/manages access to those S3 buckets? As said, the automation on those repositories was set up by MoFo folks.

**Comment by Pomax** [comment]
@benhohner @tomusher can we find out who "owns" these repos and associated buckets?

**Comment by Pomax** [comment]
@TheoChevalier I am not part of the mozilla-l10n group, but if you have rights to those two repos, uplifting the travis yml files to github actions is pretty straight forward and I can help with that if you'd like.

**Comment by Pomax** [comment]
I've filed a tracking issue on the mofo-devops repo so we can coordinate the work for the l10n repos there.

**Comment by benhohner** [comment]
@Pomax can you get me a list of the S3 bucket names I'm looking for?
