### ISSUE TITLE
Offset viewport where footnotes jump to

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#5788]
Offset viewport where footnotes jump to (currently top section hidden behind nav)

Example URL:
- https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/what-helps-the-ecosystem-for-needs-and-support/#footnote-1
- click footnote's `[1]` to go to the footnote in the content.
- click the footnote link in the content
- footnote ends up underneath the `.article-navbar` div

**Comment by mmmavis** [comment]
The [CSS-only solution](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/sass/components/article-page.scss#L247-L255) seems to only work if the **inline** anchor itself is set to have `display: block`... which is def not what we want. I ran out of all the CSS-only solutions I could think of. Gonna ask the team for help. Fallback plan will be using JS for this.

**Comment by kristinashu** [comment]
This was fixed but seems to be an issue again.

**Comment by mtdenton** [comment]
Marking this for purge because of how old this is. If this gets closed, my thoughts in case it's important enough to reopen:

Could we just link all of these footnotes to an anchor slightly above the footnote list, like the "Footnotes" title? Seems like a disproportionate amount of time was spent on this vs the value that it brings.
