### ISSUE TITLE
Meeting to discuss Separate Hubs for PNI/Insights/Trustworthy

### ISSUE THREAD

**Issue by jamilasnell** [mozilla/foundation.mozilla.org#5820]
Meeting to discuss different online presence for these three different groups who all used to be under insights but have their own presence now.

**Comment by kristinashu** [comment]
@jamilasnell could you please elaborate on this? 

Tais and I have done a lot of URL mapping [here](https://docs.google.com/spreadsheets/d/184z7LnHIghXDp2NIns4T8zlpBDAdaRFuPMUDX7ijHYY/edit#gid=50754596).

**Comment by sabrinang** [comment]
I can’t recall entirely but it had something to do with being asked about how the TAI research shows up on the site among other teams doing research when we were going over TAI pub. Not sure if Becca is aware of the URL mapping work but that may be helpful for her to know where research is housed or where she can house her research if she isn’t aware already. Perhaps it was seen that insights/research being oriented around the ‘teams’ or ‘reports’ (exp. seen as insight team itself rather than category; I don’t recall what it was about PNI or data futures being mentioned though). Not sure if the various teams producing research have been oriented around the mapping this already to understand where their work shows up.

**Comment by kristinashu** [comment]
I'm going to close this. There are talks between Kasia and Becca R (and many others) about this. We will continue to put all research and analysis under insights. We might need to rename this to research at some point but I feel like this will be an ongoing thing...
