### ISSUE TITLE
Consider adding a "show numbering in ToC" toggle box to Publication Page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5846]
### Describe the feature request
Consider adding a new toggle box to Publication Page for editors to decide whether or not they want to have auto-numbering appear in ToC.

### Additional context
Context: #5840

/cc @sabrinang

**Comment by Pomax** [comment]
@sabrinang assigning to you mostly to decide who is most qualified to _actually_ pick this up =)

**Comment by Pomax** [comment]
marking as 1 for the engineering side, I am unfamiliar with how much work is required on the design side so feel free to update that value

**Comment by kristinashu** [comment]
@sabrinang is there actually any design required for this? Or it is just about you giving the go ahead that this should be implemented?

**Comment by sabrinang** [comment]
@kristinashu The design for this was mocked up previously https://share.goabstract.com/c5b5156f-9bb9-4147-a45d-0bf020c0c76b?collectionLayerId=82da8aba-b9f0-4507-b7f0-6475b14b2b19&mode=design

Since the numbers have conflicted with numbering in the content use cases so far, I'd have the numbering toggle off by default if implemented. There hasn't been urgent need for this request so not a high priority.

**Comment by kristinashu** [comment]
Chatted with Sabrina over slack about this. We decided that since this feature has not come up in any other use case and we don't want to unnecessarily over complicate the cms, we will close this and re-open it if the need arises.
