### ISSUE TITLE
GA pageview event seems to stop being fired

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#5909]
### Describe the bug
Pageview numbers on GA dashboard seem very low for the past few days. I used the the Chrome GA plug-in to check and it looks like pageview events aren't being fired. 

### Expected behavior
Pageview events are being fired and tracked.

**Comment by Pomax** [comment]
We turned this off in https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/common/google-analytics.js#L49 because we had added google tag manager and were worried about double events for page views, @benhohner is this something we need to reenable, or do we want to keep that turned off and onboard folks to the GTM system?

**Comment by mmmavis** [comment]
Debugged this with @benhohner . It turned out to be that we forgot to whitelist the external script that's supposed to fire GTM's events. I've added both `https://www.googletagmanager.com/gtm.js` and `https://www.googletagmanager.com/debug/bootstrap` to production's `CSP_SCRIPT_SRC` so things should work fine now.

Fun fact: the reason why we were still getting _some_ pageview events was because that it somehow got recorded by GA when an interaction action was trigger by the user (e.g., button clicks).
