### ISSUE TITLE
wagtail-localize: Investigate foreign key bug on PNI products

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#5953]
[This snippet of code](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/products.py#L352-L360) makes wagtail-localize crash, we will need to find another way to handle this.

<img width="913" alt="Capture d’écran 2020-12-16 à 15 55 26" src="https://user-images.githubusercontent.com/1294206/102912715-a250d180-4475-11eb-8b5f-99ca112d459d.png">

Note: you can only reproduce the error with [this branch](https://github.com/mozilla/foundation.mozilla.org/tree/wagtail-2-11) (enabling wagtail-localize), by creating a new locale in http://localhost:8000/cms/locales/ then translating a PNI product in that locale.

**Comment by Bhavik-Ardeshna** [comment]
@TheoChevalier I want to contribute to this issue and plz I am new to this plz me ....

**Comment by TheoChevalier** [comment]
Hey @Bhavik-Ardeshna thanks for your interest, but I don’t believe this ticket is suitable for a first contribution. It’s part of something bigger and requires more work to find the best approach to fix it.

**Comment by Pomax** [comment]
If things break on foreignkeys, that feels like a bug in wagtail that needs fixing, because foreign keys are kind of essential to Django models. @KalobTaulien any ideas here?

**Comment by TheoChevalier** [comment]
Note: having a similar issue for the MozFest site, with a field that is a simple `CharField` in #6030

**Comment by KalobTaulien** [comment]
For the Mozfest Homepage it was caused by the `header` field not being added to the `content_panels` but having the field still exist. We can add `header` and any other missing fields to the content panels to solve this issue. 

For this issue, we're looking at ForeignKey and it cannot be exposed to the CMS admin. The solution is to add `FieldPanel('votes')` to the `content_panels` but then we're trying to translate votes, which are purely numeric, *and* exposing a field that should be hidden. 

I opened an issue for this on the wagtail-localize repo https://github.com/wagtail/wagtail-localize/issues/306 and pinged Karl about this.

**Comment by KalobTaulien** [comment]
We can use the same solution as in #6030 and simply ignore the fields we don't want to add. 

```
    translatable_fields = [
        TranslatableField('title'),
        ...
        # SynchronizedField('votes'), # <- Removed and all works well.
    ]
```

I also tried adding `editable=False` to the ForeignKey field and that didnt quite do the trick. Karl might look into adding a property where we can ignore certain fields instead of having a super long list of TranslatableFields and SynchronizedFields. But for now, this is the solution.
