### ISSUE TITLE
Improve the CMS image management

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#5954]
Our current image approach is "all images in the root collection, 20 thumbs per page" which is becoming a bit unwieldy. Let's see if we can't:

- increase the number of thumbs per page (60? 100?)
- start using collections (PNI, blog, ...?)
- try to make sure to title and tag all images so that discoverability isn't just visual but can rely on text search working?

**Comment by Pomax** [comment]
It would be nice to turn on the setting that tells us which pages makes use of specific images

**Comment by kristinashu** [comment]
> It would be nice to turn on the setting that tells us which pages makes use of specific images

That would be amazing!

> increase the number of thumbs per page (60? 100?)

Yes please! 

> start using collections (PNI, blog, ...?)

Yes. But maybe not as useful as the other features you mentioned. This one might be trickier since one image might get used in different places. 

> try to make sure to title and tag all images so that discoverability isn't just visual but can rely on text search working?

This is probably the most important! I can relay to designers to do a better job naming images. But maybe we could also add a note / tool tip / hint text to the upload?

One other idea is to allow more staff to edit images? This might help reduce instances like this were people test out different images:

<img width="931" alt="Screen Shot 2021-02-02 at 12 27 22 PM" src="https://user-images.githubusercontent.com/1068783/106668339-0085cf80-655f-11eb-84e9-3edd260b6719.png">

**Comment by KalobTaulien** [comment]
@kristinashu For image positioning, we can use a Focal Point. Setting a focal point will _try_ to move the selected area into the center of the image. It'll try it's best to center it, but it's not always perfect. Setting a focal point will definitely be helpful. And if there's a particular image in a template that NEEDS to always be close to the focal point, devs can set that in the template.

![image](https://user-images.githubusercontent.com/4743971/106791864-bcec9d80-6612-11eb-9f7a-17041501d608.png)

**Comment by kristinashu** [comment]
cc @taisdesouzalessa who has open a ticket about create a template for the hero image which can help plan out where text will be (at different widths) and how much contract is needed.
