### ISSUE TITLE
wagtail-localize: investigate QuoteBlock localization

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#6183]
I’ve added a QuoteBlock to a blog post, and this content didn’t get extracted for localization. We should investigate why that is. 

It may require some changes to the model, or a fix in wagtail-localize

**Comment by Pomax** [comment]
for reference: python code [is here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/pagemodels/customblocks/quote_block.py), template file [is here](https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/quote_block.html).

**Comment by KalobTaulien** [comment]
Hey @TheoChevalier So QuoteBlocks are supported, but we're dealing with a ListBlock here which is _not_ supported. 

The next best thing we can do it convert ListBlocks into StreamBlocks (because StreamBlocks are supported). There's hope that one day ListBlocks will be supported. 

I'm going to move this back to "needs discussion" so we can talk about moving forward with this ticket. 

/cc @Pomax @TheoChevalier

**Comment by Pomax** [comment]
What is the _reason_ listblock doesn't work, though? nesting is arbitrary by design, what part of wagtail-localize is having trouble with this? Is it that it can't figure out how deep it needs to go? (e.g. is it not consulting the class/field relations?)

**Comment by TheoChevalier** [comment]
Hm, looks like it’s covered by https://github.com/wagtail/wagtail-localize/issues/22 with a Wagtail fix detailed in this RFC https://github.com/wagtail/rfcs/blob/listblock/text/065-listblock.md

**Comment by KalobTaulien** [comment]
It's because ListBlocks don't have unique ID's for the items in each one of them (I believe). So there's no clear and streamlined way to extract items out of a ListBlock, translate it, and inject it back into its proper spot. At least that was my understanding of it. 

The idea is to hopefully improve ListBlocks in Wagtail Core so this can be supported. There's a Wagtail Core RFC that's relatively new [here](https://github.com/wagtail/rfcs/pull/65) to add this support in to ListBlocks.

**Comment by KalobTaulien** [comment]
Quick update: 

As far as I can tell, we're only using QuoteBlocks for one quote at a time even though we've enabled it to use multiple quotes (using a ListBlock).

```python
    quotes = blocks.ListBlock(blocks.StructBlock([
        ('quote', blocks.CharBlock()),
        ('attribution', blocks.CharBlock())
    ]))
```

That's the code in our codebase. What we need to do is convert this to a StreamBlock, or better way convert it to a singular StructBlock so there aren't multiple quotes in the same template. 

In order for us to move away from the ListBlock we would need to copy the content from the BlogPost.QuoteBlock. There's quite a few of them, but they are simple edits on each page, and I don't think writing a manual data migration for this is going to be faster than copy/pasting the data into a new block type.

That would allow us to move forward with this ticket, remove the need for nested blocks for singular Quotes, simplify the codebase a little bit, and enable localization. 

Or as mentioned in the last comment, we can wait until the RFC is approved and added into Wagtail so wagtail-localize can support ListBlocks.

**Comment by KalobTaulien** [comment]
Update: The RFC for adding unique IDs to ListBlocks has been accepted. Awaiting implementation.

**Comment by KalobTaulien** [comment]
Quotes on ArticlePages work fine. Its the `base_fields` that has the ListBlock. 

For our QuoteBlock/ListBlock problem, where ListBlocks aren’t localized because they dont have a UUID - it turns out we aren’t using the ListBlock (I checked 40 production pages and none of them use more than one quote in the listblock). And The template is hard coded to only show one quote anyway, so even if there were more, we’re only showing the first one.

There are two ways to tackle this. Both require us to create a new QuoteBlock for pages that are using the ListBlock version of it and then either:
1. Manually updating each Quote in the admin (copy and paste from the ListBlock to a new QuoteBlock), or
2. Automate it for a one-time action  —  Write a data migration to: create the new block, migrate data from old block to new block, delete old list block.

I'm leaning towards the automated solution so less hands need to be involved.

**Comment by KalobTaulien** [comment]
Going with option number 2: automation. 

New ticket here: #6934
