### ISSUE TITLE
[Publications] H2 Anchor Links Break with Bold/Italic Applied

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6326]
H2 links auto-generate anchor links in the summary box and drop down. When other styling such as bold and italic are also applied with H2 the link doesn't jump down to the section when clicked. 

This may be a bug as the links should still work. If we don't want people to use both as a practice we should make it more obvious as it isn't clear why sometimes H2s don't work.

**Comment by Pomax** [comment]
This is by design, the idea is that headings already use our style guide heading classes, so allowing bold or italic inside a header would violate that. However, the fact that it doesn't warn when people add that anyway is certainly less than ideal, and we should look at generating an error for richtext blocks that contain headings that aren't just text.

**Comment by jamilasnell** [comment]
@sabrinang Does bold or italic text in a heading violate our style guide?

**Comment by sabrinang** [comment]
Yeah I'd say so as a true .h2-heading style is not bolded or italicized https://foundation.mozilla.org/en/style-guide/
