### ISSUE TITLE
[Spike] Improve SCSS building speed

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6403]
SCSS files get rebuilt super slowly on dev mode. Let's see how we can update the tasks to improve the building speed.

- [ ] create task based on research outcomes

**Comment by Pomax** [comment]
So far I've not been ablet to determine a good way to speed SCSS building, but we can improve our docker-compose.yml to:

- not have the backend depend on the watch task (as they're technically independent)
- set a chokidar interval so that it's only polling every, say, 2 seconds

Doing this I do notice that loading https://localhost:8000 has an odd quirk: loading the site the moment the backend is up and running shows that the CSS files turn into a "cancelled" network request, and I'm not sure what that means. Reloading then works fine.

**Comment by Pomax** [comment]
something else to try:

- [ ] separate docker containers for JS vs. CSS bundling/watching

Might at least make things more responsive?
