### ISSUE TITLE
Document why we have a sentry debug url still

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6434]
In our `urls.py` we have:
```python
path('sentry-debug', lambda r:  1 / 0) if settings.SENTRY_DSN and settings.DEBUG else None,
```

Turns out we actually want to keep this in case we need to do local debugging through sentry. 

Let's add some documentation around this (code commends are fine) stating _why_ this is here, and _why_ we're keeping it even though it's only useful in local development.

**Comment by Pomax** [comment]
- [ ] find the appropriate places to document this
  - this includes in the settings.py

To explain that line: it shims sentry so that when you're running with sentry enabled locally, rather than sending sentry errors over to the remote service, we cause an intentional crash so you can see that in your local dev console.

**Comment by Pomax** [comment]
assigning as part of my documentation work
