### ISSUE TITLE
[Documentation] Update repo README with notes about SCSS and JS

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#6504]
As part of repo README, explain 

- when to use React vs Vanilla JS
- selector naming convention

**Comment by jamilasnell** [comment]
@benhohner this ticket feels like it should be a part of #6281 (the onboarding ticket). If so, we should add this work as a step in your onboarding ticket and close this one.

**Comment by Pomax** [comment]
making this part of my documentation work

**Comment by Pomax** [comment]
With the tailwind work and the CMS styleguide in place, the CSS part is essentially covered. For React vs. Vanilla, I'm going to leave that decision up to the team rather than setting it in (docs) stone. It will depend on what the team is more comfortable writing. (plain JS can do a lot, but when to switch to React is really a matter of need)
