### ISSUE TITLE
[Data Visualization] Stakeholder Needs Assesment 

### ISSUE THREAD

**Issue by sabrinang** [mozilla/foundation.mozilla.org#6524]
### Context
To assess the needs of staff around the ability to create data visualizations to accompany their work, content or data. This will help clarify the demand and abilities of staff being able to create data vis on the Foundation site and how we can best support the work they produce.

Teams & use cases to reach out to:
- Insights team — Kasia
- Advocacy team — Kaili
- Internet Health Report team 
- Content team — Audrey, Xavier
- Data Future Lab?
- Jackie (data lead)?
- Staff who makes polls, survey result share outs? bloggers?

We can conduct this by a qualitative survey or casual slack interviews to help define the needs/goals of the brief.

### Reference
Planning document: https://docs.google.com/document/d/1ySaJMH4mWxgZLqt7PvdVeNdS-IHekfKBYLF-ZSI9Nk4/edit?usp=sharing
Planning issue: https://github.com/mozilla/foundation.mozilla.org/issues/6192

**Comment by sabrinang** [comment]
I've created a google form as an internal staff survey for gauge needs and desires for "Data Visualizations on the Foundation Website": https://docs.google.com/forms/d/1rq4SMsFiKfj7kYrvguoKHTrIs1liSx_bONWeKAwadFg/edit?usp=sharing

@kristinashu @benhohner Please review the questions and structure. It will automatically collect staff mozilla emails and if I missed any questions you want to add please let me know so I can revise it.

**Sharing out plan**
I intend to share the link on Slack in the #mofo-staff channel and again in #advocacy-and-engagement-team to ensure it has been seen by our broader team.

Slack message:
`Our team is considering to add data visualization features to the Foundation website. We have a quick 5 minute survey to help us understand staff interest, needs and desires around the ability to create or incorporate data visuals that accompany your work on foundation.mozilla.org. Please let us know if you are interested and how we can best support you by filling out: <link here>
Thank you!`

**Comment by benhohner** [comment]
@sabrinang looks good! 
I have a couple comments:
1. Let's remove the microsite option from "Where would you want to use data visualization on?", as we're moving away from microsites because they're bad for SEO and extra work to maintain, and we don't want to prime users to request them more.
2. The "Would you want your data visualization to be ..." section feels like something we should be recommending to stakeholders based on our user research? I guess, simply put, it seems like we're venturing into technical territory where a stakeholder might want to rely on us to make best decisions because we're experts in interaction design. I don't know if what I said here gets to the root of my feelings about this question, but I think maybe we need to rethink it.

I think your distribution plan is great, though I anticipate we may also have to personally ping key stakeholders if they haven't completed the survey as we're asking them to take time out of their work days to complete this.

Thanks for creating this survey! Excited to see the results :)

**Comment by kristinashu** [comment]
Looks good Sabs and +1 to Ben's comments.

For your slack message, I'd recommend giving people a deadline for fill out the form.

**Comment by sabrinang** [comment]
I appreciate the great feedback @benhohner and @kristinashu !

**Survey Revised** https://docs.google.com/forms/d/1rq4SMsFiKfj7kYrvguoKHTrIs1liSx_bONWeKAwadFg/edit?usp=sharing
1. I removed the microsite option and makes a lot of sense why we want to discourage them.
2. Thanks for pointing out the _“Would you want your data visualization to be ...”_ question. I like how you framed it that we should be making the recommendations based on our findings. I’m going to remove this question as it seems to specific this early anyway and if staff want to tell us about features/style desired there is a long answer box previously and open comment question at the end too.

**Slack Distribution Plan**
- Yes I can also personally ping the key stakeholders to ensure they’ve completed it. 
- Ah yes a deadline! I’m thinking next Friday. Do you think this is enough time?
    - I can update the last sentence to be:
`... Please let us know if you are interested and how we can best support you by filling out the survey by next week Friday, May 14:  <link here> Thank you!`

**Comment by kristinashu** [comment]
R+

**Comment by sabrinang** [comment]
Thanks both again and it is shared!
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2492510/117366287-60995400-ae75-11eb-8f80-3ba7a73a5da1.png">
 I posted the form in mofo-staff and a+e team channel 🚀

**Comment by sabrinang** [comment]
Survey responses can be seen in the _Responses_ tab: https://docs.google.com/forms/d/1rq4SMsFiKfj7kYrvguoKHTrIs1liSx_bONWeKAwadFg/edit#responses

You can also see responses in google sheets here: https://docs.google.com/spreadsheets/d/1IsqORuloqMwnqp64FX2oMfVtEX6DKgSRCwA2gMU-vQw/edit?usp=sharing 


I filed a follow up placeholder issue related to data visualization components here #6645
