### ISSUE TITLE
Finish Engineering definition of done

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#6594]
We need to define what "done" means to us, when is something "done". 

Done may be different from "complete" or "finished" depending on the dept. that's working on a ticket. So we may want to consider what is "done" for devs vs. what is "done" as in completely finished. 

- [x] Research common definitions of done
- [x] Create a call to discuss with devs
- [x] Create a strategy for including in our tickets
- [ ] Document definition of done in our dev ops repo

**Comment by Pomax** [comment]
Some thoughts before meeting: there are three levels of "done" for work:

1. the user/stakeholder level
2. the design level
3. the engineering level

(1) doesn't care about (2) or (3), it is mainly concerned with:

- [ ] the feature/functionality/pages/whatever is live
- [ ] if functionality, there is documentation
  - [ ] if there is documentation, that documentation is discoverable

(2) I can't comment to much on, although ultimately done is "it's live", too.

(3) ultimately means "it's live, and working", rather than the "it's been merged into master" that we're currently using
- [ ] all acceptance criteria have been met
  - [ ] any implementation issue should have these, no matter how small. If it's work we're doing, we should clarify what that work is, so that there's no feature-creep, instead:
  - [ ] any follow-up work has been filed separately.
- [ ] any new or changed functionality is documented
  - [ ] that documentation is discoverable
- [ ] the code change has been verified on production

**Comment by benhohner** [comment]
For Engineers:

## Pre-merge
* Code follows our code style guide
* Code is documented according to our documentation standards
* Unit Test Coverage
* Integration Test Coverage
* Any technical debt is documented
* Peer code reviewed by at least one other developer
* Code has error handling with any required logging/metrics
* Incomplete features are hidden behind feature flags
* Business requirements are met
* Secrets are up to date
* Code is deployed to Staging

## Post-Deploy
* follow up ticket is created to address technical debt.
* Code is deployed on Production

**Comment by danielfmiranda** [comment]
Closing this issue as I have created some follow up tickets: 
[Update/create issue template that includes new definition of "done" #6647](https://github.com/mozilla/foundation.mozilla.org/issues/6647)
[Document new definition of done in Dev-Ops Repo #6648](https://github.com/mozilla/foundation.mozilla.org/issues/6648)
