### ISSUE TITLE
Storytelling Wagtail Component: Header Image/ Hero Video Block

### ISSUE THREAD

**Issue by natalieworth** [mozilla/foundation.mozilla.org#6675]
### Intro
To allow for more compelling storytelling on the Wagtail blog pages, we want to implement a larger hero image/video block section within the Wagtail blog template.
![Screen Shot 2021-05-10 at 7.33.27 PM.png](https://images.zenhubusercontent.com/57a10963e40e5714b16cdb3b/813e8ed2-ba23-4400-9cfb-2140fb067d50)

---

###  Design -> Dev Handoff Checklist

- [x] Design has been finalized 
- [x] Link to original design ticket (original design ticket is in #828 (https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozillafoundation/design/828)
- [x] [Link to Redpen](https://redpen.io/p/wu5fe36cd1366a0cad)
- [x] [Link to Figma file](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=0%3A1)
- [x] Desktop, tablet, and mobile mockups are included
- [ ]Assets are included. Link (https://drive.google.com/open?id=15XTjgbU_UpnGBEGvslNe5AvX4kMGONM3&authuser=natalie%40mozillafoundation.org&usp=drive_fs)
- [x] Hover state for elements are designed ([the prototype is here for the play/pause states on the page](https://www.figma.com/proto/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=55%3A766&scaling=min-zoom&page-id=55%3A700) and the designed [Figma file is here](https://www.figma.com/file/OTFsYEpkuXcR6HgowgDlyO/Wagtail-Storytelling-Components?node-id=55%3A700) for reference

Please reach out to @natalieworth if you have any questions or need clarification! :)

@benhohner I'm going to leave the estimate up to your team. I'm not sure what's best or how long each issue will take! :)

**Comment by benhohner** [comment]
MVP with Vimeo embed, using JS api

- One thing to investigate is what the video will do/look like on large images

**Comment by danielfmiranda** [comment]
Hi @Pomax @KalobTaulien, 

At the moment I have the front end portion of this ticket pretty much completed, using the hardcoded example from the mozfest page. However since we want to allow the users to add a video of their choice I was wondering if we can have a discussion around how we should store/host the videos, so far the following options have been mentioned:

- We can use the [wagtail media](https://github.com/torchbox/wagtailmedia) package and link to them that way
- We can host the videos on Vimeo, and allow the user to enter the URL to the video using a charfield in the admin

Would there be any drawbacks to using the wagtail media package? For example, space or server resources

Thank you!

**Comment by danielfmiranda** [comment]
Hi @Pomax @KalobTaulien , have another question regarding this ticket:

I now have the video working through a charfield. For example, if you edit a page and paste a url to a MP4 in the "hero_video" section, the hero-video will render on the blog page. 

However, in order to get them to load I had to add a '*' to the CSP_MEDIA_SRC environment variable. 

I know thats not the safest to do once this hits prod, so my question is:
- Are we only going to use videos that are uploaded to the whitelisted s3.amazonaws url? 
- Or should we make a change to the security settings? 

Thank you in advance!

**Comment by danielfmiranda** [comment]
Hi @benhohner !

Upon further research, it looks like the ability to get the direct link to the MP4 files from vimeo to work with our player would require a vimeo **pro** subscription: https://vimeo.zendesk.com/hc/en-us/articles/224823567-Direct-links-to-video-files

With a **plus** subscription, which is the tier below the pro, that would give us the option to customize their video player, such as removing things like the logo, time bar, title, etc. and leaving just the play button.

With that said I think there are two possible options if we want to move forward using vimeo:

- The first and the easiest would be to get the pro subscription, as with that we all we would need to do is copy and paste the video URL in the "url" field in the CMS, and our existing, customized player will work as expected. 

- The second and more cost effective, though probably a little more hacky then the first, would be to get the plus subscription, and over ride the controls through CSS to fit our design.
