### ISSUE TITLE
Publications template enhancements for Fellowships & Awards Report

### ISSUE THREAD

**Issue by benhohner** [mozilla/foundation.mozilla.org#7100]
See designs here:
https://www.figma.com/file/CW7wI9UFdCzMQjsAqnkRas/F%26A-Report-Site-Wireframes?node-id=0%3A1

Make sure to leave slack in this sprint for developer time to work on this.

- [x]  Go through designs, assess whether suggested changes fit within our visual language. Assess whether changes will improve overall usability of publications template across all usages.
- [x] Determine feasibility
- [ ] Let Simply Secure know about our decisions to implement
- [ ] Onboard developers

**Comment by kristinashu** [comment]
### Additional links
- [Copy doc for the report](https://docs.google.com/document/d/1cf4x-TQYuIP6JJmITQjU7Xj9vjoqDk7devEBtRPtba8/edit)
- [Their timeline](https://docs.google.com/document/d/1BymMF0IcvkgqBeWyduRRiHDa4vX8C6v05g0hHUtdaeo/edit)
- Pages in the CMS: ["landing page" for all research ](https://foundation.mozilla.org/en/what-we-fund/research/) & [full report](https://foundation.mozilla.org/en/what-we-fund/research/fellowships-awards-evaluation/)

### Communication with Katie

After reviewing Katie's wireframes, this is our response:

> Ben and I ran this past the team and we are concerned about making this big of navigation updates within the timeline. Both the nav changes to make the Banner template they way you wireframes as well as the nav changes to make the Publications template they way you wireframes. We are happy to make component updates but the navigation make us a little nervous since it will have a trickle effect to many other places on the website. We recommend using the Publications templates since it can handle the IA of having multiple levels of sequential pages (both on desktop and mobile). Want we would recommend: 
- Add quote component to publications template [in progress https://github.com/mozilla/foundation.mozilla.org/issues/7057]
- Devs could remove the secondary ToC page mentioned [need ticket]
- Devs could add a card component, if still needed (wouldn’t be available until just before launch) [need ticket]
- Design recommends putting more content on each page i.e. instead of putting the Executive summary on 4 separate pages, put it on one. Here’s an example https://foundation.mozilla.org/en/insights/trustworthy-ai-whitepaper/ai-challenges/ of a long page with the anchors link. Wide image component is a nice way to break up the sections within a page. 
- Perhaps we could add some more component options to the main ToC page
- Sabrina, one of our designers, could meet with Katie to jam on ways to divide up the content [scheduled for Jul 27]
- Longer-term, we will work to implement some of the bigger nav updates but do not want to block the launch of the report nor can we rush to get it done in time
- Lastly, not sure if you’ve seen this example https://foundation.mozilla.org/en/data-futures-lab/data-for-empowerment/ but for reference, it has a similar amount of content as your report

### Next steps
- Kristina and Sabrina to meet with Katie
- Kristina to open dev tickets
