### ISSUE TITLE
[wagtail-localize] Localize PNI categories

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7120]
<img width="1147" alt="Capture d’écran 2021-07-22 à 15 15 55" src="https://user-images.githubusercontent.com/1294206/126645664-17ad18b6-27ca-49ab-80d1-8e158d8f78b7.png">

- [ ] Menu entries appear translated on the page
- [ ] Category URLs actually use the slug field value instead of a slugifyed category name.

Currently https://foundation-localize.herokuapp.com/fr/privacynotincluded/categories/meilleurs-produits/ is valid while only https://foundation-localize.herokuapp.com/fr/privacynotincluded/categories/best-of/ should be.

- [ ] Menu entries appear on PNI home
<img width="1200" alt="Capture d’écran 2021-07-27 à 19 49 18" src="https://user-images.githubusercontent.com/1294206/127203143-8ec6477b-abd2-4c4b-8395-3f56c3e6fca5.png">

**Comment by Pomax** [comment]
Digging into this, it looks like we can't generate the correct URLs because there doesn't appear to be a way to find the "original" snippet from a localized instance in the same way that you can ask for a `page.alias_of` to get the original page.

```jinja
{% for cat in categories %}
  {% if cat.published_product_page_count > 0 %}
    {% routablepageurl home_page 'category-view' cat.slug as cat_url %}
    <a class="multipage-link {% check_active_category current_category cat %}{% if cat.featured is True %} featured{% endif %}{% if category == cat.slug %} active{% endif %}" href="{{ cat_url }}" data-name="{{ cat.name }}">{{ cat.name }}</a>
  {% endif %}
{% endfor %}
```

In this, `cat` is the localized category instance, but the `for...` needs to check product population against the _original_ category, not the localized version (because the localized version will have zero products under it). Then, the `routablepageurl` slug should be building the URL for whatever locale we are currently on, and it doesn't, instead yielding the `/en/` URL instead.

**Comment by Pomax** [comment]
This literally just got fixed.
