### ISSUE TITLE
Audio player: Volume control

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/foundation.mozilla.org#7205]
The new audio player in the foundation site could probably use a volume control feature. 

We will want to run this by the design team first.

**Comment by Pomax** [comment]
While this is definitely true on mobile devices as well as for OSX users, for windows and linux users this is unfortunately not the case, where controlling the volume at the system level is quite hard. Having volume controls on media elements is pretty important for users on those operating systems.

**Comment by kristinashu** [comment]
Thank you Pomax, it's good to get input from a windows and linux user! 

Design agrees that we should add in volume control for better accessibility. But we do think the design needs an icon to better explain what the second slider is for. Design will mock-up some options but do please share any examples you see. Note that this is a sketch goal for us so we night not get to it right away - which I think is ok since this component isn't yet being widely used on the site.

We also all like the track head so do feel free to add that in as is!

**Comment by jamilasnell** [comment]
Mock-up to come from design
