### ISSUE TITLE
Share-button-group React component should probably be a Django/Wagtail Template

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#7258]
Share-button-group component should probably not be react component since its mostly links but we still need to keep  `copy-to-keepboard.js` usage for the copy button

**Comment by danielfmiranda** [comment]
Originally I thought that this may not be possible as there is alot of custom react-logic since these buttons are shared by multiple pages, however, after reviewing Simons PR: https://github.com/mozilla/foundation.mozilla.org/pull/8112 I do believe this is possible! 

Updating estimate to a 3 to reflect the level of work this is, and moving this to up next
