### ISSUE TITLE
[PNI] Product page - content update: "tips to protect yourself"

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7380]
- Add a "tips to protect yourself" section to the product page
  - [x] create a `streamfield` field in the ProductPage for 0...N rich text blocks
    - rich text with reduced button bar: plain text, bold, italics, links
    - ability to create lists
  - [x] update the product page template to show tips if the tips streamfield has more than zero blocks
    - include the tips icon. SVG icon here: https://drive.google.com/open?id=1TtPLknFz6kPc9Ni064yLoIYaKnvgV36g&authuser=sabrina%40mozillafoundation.org&usp=drive_fs

Relevant part of the updated product page comp:

![image](https://user-images.githubusercontent.com/177243/133166631-587dfdb1-cfbc-4186-bd86-6a38a2ad6097.png)

Comps on figma: https://www.figma.com/proto/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?page-id=548%3A72128&node-id=611%3A77813&viewport=283%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=611%3A77813

**Comment by danielfmiranda** [comment]
Hi @Pomax have a quick question about this ticket, I noticed that you mentioned the ability to add 0 ... N rich text blocks, and also said we should have the template check if there are > 0 blocks, and if so to render them.

Does that mean if the user does in fact have multiple blocks, we want to render multiple boxes of the same style that say "Tips to protect yourself?"  

Asking because I am curious about the need for multiple blocks, I was under the impression this was a singular section on the product page, and was wondering why use multiple blocks, VS just adding one new "tips_to_protect_yourself" richtext field, and only rendering the section if it is not blank or "" 

Thanks in advance!
