### ISSUE TITLE
Blog posts are not sorted in chronological order

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/foundation.mozilla.org#7404]
On https://foundation.mozilla.org/en/blog/ blog posts are no longer sorted by chronological order.

Currently, https://foundation.mozilla.org/en/blog/announcing-common-voices-kiswahili-community-event-this-august/ appears first while we definitely posted multiple blog posts afterwards

**Comment by Pomax** [comment]
This one's definintely puzzling, because when I run the main branch with a copy of the production database, the `blog` page is ordered correctly: 

![image](https://user-images.githubusercontent.com/177243/134059156-4f99f8fa-831a-48c8-81fb-318b35eb605b.png)

However, the live site has a very different order. BLog page sets _are_ cached, so it's possible that cache is somehow not clearing. @tomusher could Redis be interfering here?

**Comment by tomusher** [comment]
Is the issue here that blog posts aren't appearing chronologically, or that new ones aren't appearing at all (or at least take a while to show)?

If it's the latter, the redis cache is probably the problem - that queryset of entries is cached for 24 hours.

If it's the former issue, I don't expect the cache is the issue but would be good to get this clarified so I can investigate further.

**Comment by Pomax** [comment]
As far as I can tell, the items are chronologically ordered, but the top item showing up is from August 24, not just "from yesterday". If I run the code locally (which isn't hooked up to any redis/etc) then the blog page rendered off of the same database shows all the most recent posts instead.

**Comment by Pomax** [comment]
This might have been front-end caching, but it looks like whatever was going on isn't going on anymore, and we don't know why. Let's file this anew if it happens again, as we have no way to determine what may have gone wrong =(
