### ISSUE TITLE
Epic: Mozfest ticket purchaser opt in for subscriber email

### ISSUE THREAD

**Issue by wilhitem** [mozilla/foundation.mozilla.org#7435]
### Describe the feature request
We have not yet estimated this feature. This is not MVP for the tito embed widget for mozfest.

Per Marc:
This is to address data collection for MozFest, and one of the problems we’re trying to solve together is firing off a double opt-in email to those that want to subscribe to the MozFest / Mozilla newsletter when purchasing a ticket.
Would it be possible to look into using the functionality we’re building into the site with TiTo’s widget to call the basket API and add the user details to a list, if they’ve opted in to really solidify the sign up process? 

### Additional context
From Jackie who heads the data team:
the CRM + data team is currently exploring a number of technical pathways to supporting the near term need of having Tito sign-ups trigger the sending of the double-opt-in email via Basket to Acoustic.

I was chatting with Marc about another issue, and along the way I realized that there is front-end dev work happening to embed ti.to on the MozFest site, and suggested that we explore this as another implementation option that we can all consider.  the scope of this would be to only post to the Basket newsletter API based on the person selecting a checkbox that they would want to sign-up for email marketing.

in the medium term, MoFo should start consolidating data about how people interact with us across various front-end platforms, in the data model that is in Cinchy, so we can start building out that elusive “cross-org” or “customer 360" view of how people interact and engage with us (aka movement metrics).   however, in order to do that, we would need to build a more robust data integration across these platforms, but at our current level of resourcing / backlog, that is not feasible to even consider doing before MozFest sign-ups open.

**Comment by b-ggs** [comment]
Only send request to Acoustic if they have opted in to the newsletter

**Comment by richbrennan** [comment]
I think this can be achieved if the correct fields are added to the Tito widget. There are callbacks we can hook into to send a request at the basket API: https://ti.to/docs/api/widget#tito-widget-v2-callbacks

**Comment by richbrennan** [comment]
Hi,

Can I just confirm the newsletter signup checkbox would be part of the Tito form?

**Comment by marcwalsh** [comment]
@richbrennan - there will be a question Tito that we’re using for that checkbox - you can see them in the callback for on:registration:finished under tickets > answers. We’re just confirming the question and answer and will let you know once we have it (unless it will be configurable from the CMS)

**Comment by marcwalsh** [comment]
Confirming the wording for the question that should appear in answers:

The question is: 
`Check the box below to be added to our Mozilla Festival list and be the first to know about the latest news and updates from the festival. You'll also be joining our Mozilla news list to stay informed in the fight for a better internet for all.`

The answer they would need to check for us to opt them in is: 
`I'm okay with Mozilla handling my info as explained in the above Privacy Notice.`

The slug for the question is: 
`the-mozfest-team-would-like-to-send-you` 

I’m trying to find the ID

**Comment by richbrennan** [comment]
I haven't been able to locate the answer to the relevant question in the `data` object that gets passed to the `on:registration:finished` callback (see screenshot). This is because the questions are asked after the callback is run, when the user assigns tickets. I think assigning tickets would lead to a `complete` status, but there isn't a callback for that in the documentation: https://ti.to/docs/api/widget#tito-widget-v2-callbacks. This step can be deferred to later with a reminder, so is not part of the order data:

> on:registration:finished

>This happens when the order is finished but not necessarily complete. It might not be complete if tickets have required questions that have yet to be filled in. It comes with full data about the order.

**Question:** Can the Tito widget be changed so this data is captured as part of the order?


If we can get the answers, Daniel kindly looked into the Basket integration and found that there is [existing code](https://github.com/mozilla/foundation.mozilla.org/blob/main/source/js/basket-signup.js) for signing users up to a newsletter. We can hopefully use this code and pass the required values in the `transaction` object when calling it.

The required values from the callback `data` are:

- newsletter: ??
- email: data.email
- privacy: true (they have to provide consent to submit the form)

**Basket signup code questions:**

1. Where will the value for `newsletter` come from?

1. Do we need to provide any extra fields to the subscribe endpoint for this integration: https://basket.readthedocs.io/newsletter_api.html#news-subscribe



![Screenshot from 2021-12-03 13-20-11](https://user-images.githubusercontent.com/3485411/144614517-d1e49632-d163-4d57-b259-577e2ae936fe.png)

**Comment by a-zim** [comment]
> The required values from the callback `data` are:
> 
>     * newsletter: ??

Greetings - are we looking for the newsletter slug here?  If so: `mozilla-festival`

**Comment by marcwalsh** [comment]
@richbrennan I heard back from TiTo this morning and it appears that it's not possible to get the answers using on:registration:finished.

They have suggested looking into the ticket.completed [webhook](https://ti.to/docs/api/admin#webhooks-triggers) as a potential alternative.

**Comment by richbrennan** [comment]
Thanks Marc.

We can't use the JavaScript solution with the web hook, we'll need a new Django view that receives the [ticket payload](https://ti.to/docs/api/admin#webhooks-payloads) from Tito, [verifies it](https://ti.to/docs/api/admin#webhooks-verifying-the-payload) and then sends a POST request to the [Basket API](https://basket.readthedocs.io/newsletter_api.html#news-subscribe).

Fortunately there is a [Python library](https://basket-client.readthedocs.io/en/latest/index.html) for integrating with the Basket API and examples in the MoFo codebase.

Dev note: how to develop locally with Tito: https://ti.to/docs/api/admin/#webhooks-developing-locally
