### ISSUE TITLE
BE: Mozfest Tito Ticket purchase embed

### ISSUE THREAD

**Issue by b-ggs** [mozilla/foundation.mozilla.org#7534]
Epic: #7433 

### Describe the feature request
A clear and concise description of your feature request

Figma for quick reference: https://www.figma.com/proto/2knnwWmmqCXuMyF6WPiOuG/MozFest-Additional-Features?page-id=0%3A1&node-id=23%3A37&viewport=288%2C48%2C0.27&scaling=min-zoom&starting-point-node-id=23%3A37&show-proto-sidebar=1

### Implementation Checklist
- [ ] Editor can add a new StreamField block that has the Tito widget
- [ ] Editor can specify the button label
- [ ] Editor can specify the Tito event 
- [ ] Editor can specify the Tito release(s)
Ideally checklist also includes:
- Want to have it set a redirect page so that when the user completes the purchase they are sent to a thank you page.

**Comment by wilhitem** [comment]
Hey @b-ggs - wanted to add the ability to set a customer redirect URL (see updated checklist in initial github comment.

Ideally they can set the page to redirect, but Marc said if it needs to be hardcoded we can do that for now.

**Comment by richbrennan** [comment]
I'm not sure that the redirect is going work because it redirects the user as soon as the Tito order complete info is displayed in the widget, so they don't get the opportunity to view it. Someone with more JS knowledge might be able to come up with a way to redirect once the widget closes, but there isn't an official Tito callback that I can hook into to achieve this: https://ti.to/docs/api/widget#tito-widget-v2-callbacks
