### ISSUE TITLE
Gather Feedback on Demo Pages

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#7586]
The pages have been built and before we share with staff it would be great to get some eye balls on these pages for review!
[Link to Page Type MVP](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/page-types/)
[Link to Streamfield Blocks MVP](https://foundation.mozilla.org/en/docs/how-do-i-wagtail/streamfield-blocks/)

- [x] @Pomax 
- [x] @danielfmiranda 
- [x] @sabrinang 
- [x] @kristinashu 
- [ ] @benhohner 

Can you give these pages a quick glance over and let me know if you see anything that needs fixing? Thanks!

**Comment by sabrinang** [comment]
These are looking good @beccaklam

For the Streamfield Blocks page:
- Linkbutton— can show a secondary example too since it’s mentioned
- Paragraph — can show rich text options applied (bold, italic, list etc) since its mentioned
- Table — do we need to note tables are only on article pages or will this change to be on all templates so it is here?

For Page Type page:
- related to the last point, do we want to mention page specific components exist like audio & looping video for blog types, tables for article pages etc. but that could be out of scope

**Comment by beccaklam** [comment]
Made some changes based on feedback:
- Added suggested edits from Sabrina but will hold off on adding the blog and article specific streamfield blocks
- Added which streamfield blocks are supported on each Page Type per Pomax's comment (decided against doing the reverse on the streamfield block page because I felt it would be difficult to keep up to date and the information seemed a bit repetitive)
- Added some cross linking per Krsitina's comment

Thanks to everyone who gave a review! A follow up ticket for the article and blog specific streamfield blocks is here: #7992
