### ISSUE TITLE
Set up a redirect from mozillafoundation.org/regretsreporter to foundation.mozilla.org/youtube/regretsreporter

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#7931]
This will require two steps:

- [x] Make sure the redirect from mozillafoundation.org to foundation.mozilla.org preserves paths and query args,
- [ ] Add a redirect in the CMS from `/regretsreporter` to the regretsreporter page once the final page has been put up and its internal page exists.

The mozillafoundation.org is an AWS based domain with a route53/cloudfront/s3 (originally set up by @jbuck) so will either need a bit of coercing into doing the right thing, or we should remove its from AWS entirely and set up a new, better, redirect using modern redirecting tools.

**Comment by jbuck** [comment]
Mozilla has a redirecting service called [refractr](https://github.com/mozilla-it/refractr/) that could be used to customize all of the redirects for mozillafoundation.org as you see fit - I'd recommend filing a bug in [jira](https://mozilla-hub.atlassian.net/jira/software/c/projects/SE/boards/292) to get that ball rolling on that

**Comment by Pomax** [comment]
corresponding jira ticket: https://mozilla-hub.atlassian.net/browse/SE-2915

**Comment by floatingatoll** [comment]
corresponding PR from Jira ticket, both of which are now cancelled: mozilla-it/refractr#215

I helped MoFo trace this historically — it was last worked several years ago, and Websre has sufficient admin to be of use.

Coercing the current mozillafoundation.org redirect to preserve paths/args was the simplest solution to save migrating it twice. In the `mofo-secure` AWS account, access-managed by Phonebook group `mofo_aws_secure`, I opened the S3 bucket `` (configured as the origin for CloudFront distribution ``), edited the `Static website` configuration, and replace this block:

```
[
    {
        "Condition": {
            "HttpErrorCodeReturnedEquals": "404"
        },
        "Redirect": {
            "HostName": "www.mozilla.org",
            "HttpRedirectCode": "301",
            "Protocol": "https",
            "ReplaceKeyWith": "foundation/"
        }
    }
]```

With this block:

```
[
    {
        "Condition": {
            "HttpErrorCodeReturnedEquals": "404"
        },
        "Redirect": {
            "HostName": "foundation.mozilla.org",
            "HttpRedirectCode": "301",
            "Protocol": "https"
        }
    }
]
```

It now uses a path/query-preserving redirect directly to foundation.mozilla.org, which is the desired outcome. (I can't check the box up top, so that's yours to do, @Pomax.)

**Comment by kristinashu** [comment]
Sorry to dredge this up but this is done and good to close, right @Pomax?

**Comment by jzinner** [comment]
The original ticket / ask was captured by @beccaklam - she indicated that Marketing wanted a "more memorable url" than foundation.mozilla.org which is why the mozillafoundation.org redirect was originally proposed.

In [Issue 7926](https://github.com/mozilla/foundation.mozilla.org/issues/7926#issuecomment-991196260) the decision was made to not set a precedent other than using our true URL [domain] which is foundation.mozilla.org.

I agree with this decision, as setting up redirects from different url's is generally bad for SEO (Search Engine Optimization) and becomes difficult to manage references.   We should collect our content under foundation.mozilla.org.
