### ISSUE TITLE
Update rich text streamfield blocks to open external links in a new tab

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8002]
Follow up from - [PNI] Make external links open in a new tab #7878 

We've started testing to see if opening external links in a new tab affects our analytics around bounce rate and sessions in a positive way. tl;dr is yes so we've have decided to expand this to include universal new-tab link behaviour from the rich text streamfield component in order to update this across the entire CMS.

- [x] All rich text streamfield blocks open external links in a new tab

**Comment by mattcfilbert** [comment]
I don't have the full context, but is there an easy way to manually update the links in the rich text?

If not, may be worth looking into leveraging [an HTML serializer like this one](https://prismic.io/docs/core-concepts/html-serializer) to automatically add the `target="_blank"` attribute to each link.

**Comment by Pomax** [comment]
There is not, and while we can hack something together, this is CMS-managed content and templates so the first step is to see if the Wagtail folks have ideas here.

**Comment by tbrlpld** [comment]
I just wanted to raise that the "open in new tab/window" behaviour is not recommended from a usability and accessibility stand-point. Especially low-vision users might miss that a new tab has been opened.

There are use cases when the "new tab/window" behaviour is beneficial (e.g. while filling a form), but these are context dependent so that making it the default would not be recommended. 

See also: https://www.nngroup.com/articles/new-browser-windows-and-tabs/

**Comment by tbrlpld** [comment]
Re: implementation: Since the change is requested for rich text fields and blocks and both are/should be rendered with the `richtext` filter, that might be a good place for it. This would also avoid having to mess with Wagtails mechanism for storing and retrieving richtext.

**Comment by tbrlpld** [comment]
Thinking about this now, I think 1 is a fairly ambitious estimate.
