### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by gvn** [mozilla/foundation.mozilla.org#806]
We need to explain that contributors need to contact us to be added as a collaborator so they can create PRs on this repo.

cc @cadecairos @alanmoo

**Comment by alanmoo** [comment]
Why can't they create PRs?

**Comment by cadecairos** [comment]
I think we should just mention in CONTRIBUTING.md that continuous integration tasks for PRs will fail unless they're for branches on the upstream repository. 

For PRs to pass, a contributor will need to be given write permissions on the repo by an admin (which should be fine, since we've got branch protection enabled)

**Comment by gvn** [comment]
Well, we should mention they need to reach out to be added otherwise it's just extra frustration they have to go through wondering why their patch fails when they make a PR from their fork.

**Comment by gvn** [comment]
@alanmoo See https://github.com/mozilla/network/pull/799 thread

**Comment by Pomax** [comment]
recent contributions have shown this isn't too much of an issue atm.
