### ISSUE TITLE
Snippets not letting you save after making changes

### ISSUE THREAD

**Issue by nancyt1** [mozilla/foundation.mozilla.org#8148]
### Describe the bug
I tried to change the share image or add in a share image to a product category page of PNI and it doesn't let me save with the error that "A category with the name already exists". This happens with a few other categories I've tried. 

### To Reproduce
1. Go to Snippets
2. Go to Buyers Guide Product Categories
3. Edit Smart Home
4. Change the image for the Share Image section
5. Click Save
6. See error that snippet could not be saved.

### Expected behavior
I should be able to just save the snippet and update the share image.

### Screenshots
![Screen Shot 2022-01-25 at 1 26 48 PM](https://user-images.githubusercontent.com/74557207/151060915-19134c9c-8aa2-4160-bce2-67317310c04e.png)

### Desktop (please complete the following information):
 - OS: MacOS Big Sur
 - Browser: Firefox
 - Version: 96.0.1

**Comment by Pomax** [comment]
I suspect it's trying to save its new values, during which it checks that there aren't any categories with the same name (to prevent people from creating duplicate categories), but I strongly suspect it's forgetting to check that only for the English locale.

Escalating to unplanned up next, because multiple folks have run into this now.
