### ISSUE TITLE
UTM query args may be going missing

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#8221]
Submitted on behalf of Audrey:

Question! If I make a button, like on this page https://foundation.mozilla.org/blog/new-research-tinders-opaque-unfair-pricing-algorithm-can-charge-users-up-to-five-times-more-for-same-service/ I noticed that the UTM info gets stripped when you click on it. So for example, I don’t think I would know how many people signed the petition having come to that page from Twitter. How do I stop that from happening?

**Comment by Pomax** [comment]
Looking at the edit page in the CMS, the button does not have any UTM values in its URL, so it doesn't seem to be a matter of UTM getting lost "on click", but that they're not there at all.

**Comment by kristinashu** [comment]
The believe the idea is:
- A user clicks on the tweet and is linked to our blog post with this UTM code https://foundation.mozilla.org/en/blog/new-research-tinders-opaque-unfair-pricing-algorithm-can-charge-users-up-to-five-times-more-for-same-service/?utm_campaign=tinderresearch2022&utm_source=twitter&utm_medium=social&utm_content=1644319897
- User reads the post and clicks on the "Sign Petition" button
- The petition button link entered in the CMS is https://foundation.mozilla.org/campaigns/tell-tinder-its-time-for-meaningful-transparency-into-your-pricing-algorithms/
- The expected behaviour is that the button link would retain the UTM code from twitter. So the petition page url should be more like https://foundation.mozilla.org/campaigns/tell-tinder-its-time-for-meaningful-transparency-into-your-pricing-algorithms/?utm_campaign=tinderresearch2022&utm_source=twitter&utm_medium=social&utm_content=1644319897

I believe this is a feature @danielfmiranda @fessehaye worked on for RegretsReporter buttons where the UTM tags get carried across the user journey - https://github.com/mozilla/foundation.mozilla.org/issues/7968. The difference here is that the buttons are not hardcoded but also that we're looking to track the user across our own website rather than external ones.

**Comment by bheasman** [comment]
This needs further discussion to firm up requirements/approach before pressing ahead

**Comment by Pomax** [comment]
meeting planned for March 16th.

**Comment by Pomax** [comment]
The idea is that we want to know which medium users came from when they fill in petition/form/etc data

**Comment by kristinashu** [comment]
Thank you for running the meeting Pomax! 

@bheasman turns out this is more of a Google Analytics need rather than a UTM need. I believe the Enduring Metrics work we are talking to Torchbox about will help solve for this - both by helping us set up GA and also by teaching staff (including Audrey, Lindsay, and Marc) how to interpret the data.

I think this ticket is good to close, what do you think @Pomax?

**Comment by Pomax** [comment]
I believe we can safely close this given the Enduring Metrics work.
