### ISSUE TITLE
Updating PDF isn't working

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#8223]
I would like to update the PDF in this link https://assets.mofoprod.net/network/documents/Personalized_Pricing.pdf without breaking the link ulr since it's been used with press and across our site.

I can typically do this via Documents when the PDF url is https://foundation.mozilla.org/documents/[number]/[name].pdf

However in this case, updating the PDF via Documents doesn't seem to be working. Documents  has the url https://foundation.mozilla.org/documents/241/Personalized_Pricing.pdf. I am unsure of were https://assets.mofoprod.net/network/documents/ comes from.

Acceptance criteria:

- [x] fix the way pdf links are presented in wagtail
- [x] update any CSM page with links to pdf documents
- [x] update the actual document at the S3 location

**Comment by tbrlpld** [comment]
@kristinashu do you have a page where the document is embedded? The `assests.mofoprod.net` domain is the S3 bucket where the documents are really stored. The `https://foundation.mozilla.org/documents/241/Personalized_Pricing.pdf` is only a redirect. 

I think it might be better to only share the redirect links (like`https://foundation.mozilla.org/documents/241/Personalized_Pricing.pdf`) to avoid this issue. 

I will investigate what we can to to update the original asset URL.

**Comment by tbrlpld** [comment]
@kristinashu I see the issue now. For some reason, our richtext definition does not include the "document link" option that is usually active in Wagtail by default. This appears to have pushed the editor to add the document link as an external link. Therefore it is not possible for Wagtails "change document" logic to take any effect (because we are shipping around it). 

![Screenshot 2022-02-16 at 08.25.15.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/56fb18fb-1d4c-4c16-be9d-8bee339fd396)

I guess a good move to avoid this issue in the future would be to allow document links in the richtext blocks. @Pomax are there reasons I am not aware of why we don't have the document link feature in the richtext blocks active?

**Comment by kristinashu** [comment]
Oh interesting, I was wondering how Kevin even got that assets url. Sounds like this fix will solve our issue!

**Comment by kristinashu** [comment]
Thank you for fixing this!

Here is the updated PDF for S3 https://drive.google.com/file/d/1EWw5ak1QYs1bm68gbVIIOWfPWmLvki3w/view.

**Comment by Pomax** [comment]
reassigning to myself to make sure the bare S3 document gets updated as well.

**Comment by tbrlpld** [comment]
@Pomax How are we going to deal with " update any CSM page with links to pdf documents"? This seems like it would require scanning the content of each individual page, because the links can be inside of richtext and we can not simply query them.

**Comment by kristinashu** [comment]
Thank you Pomax, it looks like the PDF in S3 has been updated so this link is now downloading the latest version https://assets.mofoprod.net/network/documents/Personalized_Pricing.pdf. 

Pomax has also updated the URL on our site so that it links to "documents" rather than "assets"

Is this good to close?

**Comment by Pomax** [comment]
I've just updated the original pdf document on S3, so we're good to close this.
