### ISSUE TITLE
Research hub | backlog creation

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#8249]
Aim of this ticket is to create the ticket backlog for the Research hub pages off the back of the [designs](https://www.figma.com/file/6BXnlCvPcQrtIaxunvuBYc/Mozilla-Research%3A-Inspiration?node-id=25%3A290)

Timeboxing to 3hrs initially.

**Comment by tbrlpld** [comment]
https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/8306

**Comment by tbrlpld** [comment]
@Pomax I have created this epic and a couple of tickets under it. I was wondering if you could give it a quick sanity check if you have a moment. 
https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/8306

I was also wondering if we might want to a short catchup about it, because I am already reconsidering the approach to the search page. I have tried to keep the tickets in a logical order and getting leaving more complex functionality for later, but I think there could still be improvement for simplification of the order in which we implement this. E.g. I was thinking we could make the MVP even simpler and only implement the "full-page" reload version first and then start adding the dynamic update features based on that. This would be very much following the "progressive enhancement" idea. Was wondering how you feel about that.
