### ISSUE TITLE
Fix passing arguments to `inv makemigrations`

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#8292]
The option to be able to pass argument to the `inv makemigrations` command was added recently. 

```python
@task(aliases=["docker-makemigrations"])
def makemigrations(ctx, arguments=""):
    """Creates new migration(s) for apps"""
    manage(ctx, f"makemigrations {arguments}")
```

Unfortunately it is not working quite right. 

```console
$ inv makemigrations "-n test"
No idea what '-n' is!
$ inv makemigrations "--name test"                               
No idea what '--name test' is!
$ inv makemigrations --name test 
No idea what '--name' is!
$ inv makemigrations '--name test'                               
No idea what '--name test' is!
$ inv -V
Invoke 1.6.0
```

Goal of this ticket if to make it possible to pass arguments to the `makemigrations` management command in the container successfully (which unlocks naming the migrations files).

**Comment by danielfmiranda** [comment]
Hi @tbrlpld!

It looks like the way to pass in arguments to this command would be: `inv makemigrations --arguments="-n testname"`.

I just tested this out and can confirm that it works as expected. However, `makemigrations` is the only command that uses `--arguments` instead of `--args`, and also lacked a note on how to use the flag. 

I created #9495 in case we want to update the code to be a little more descriptive on how to use these flags, as well as have `--args` be the uniform flag across tasks.

Thanks!
