### ISSUE TITLE
Add MozFest Slider to Foundation Site

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#8473]
Torchbox and designed and built a few new blocks for the mozfest site. Design looked over the new blocks and decided to add the Slider to the Foundation site with some adjustments to the front and back end.

---

### Design to Dev handoff Checklist:
Link to original design ticket: #8019
[Figma File](https://www.figma.com/file/P06Q7hWuILgc9g19AXcP39/Publications-template?node-id=574%3A25973)
[Redpen](https://redpen.io/p/dz260c9693be38fb73)
- [x] Reorder the card content to be Image first, followed by Text
- [x] Remove the Subheading Link field
- [x] Change Image aspect ratio
- [x] Adjust padding
- [x] Add photo detail text
- [x] Add a counter by the slider arrows on desktop
- [x] Make the following optional: Slider Title, Slider Item Title, Body, Buttons, Image detail text

The following should be included in Body:
- [x] Body Large text
- [x] Bold
- [x] Italic
- [x] Link

**Comment by beccaklam** [comment]
Hi @cdanfon ! Just saw that this was removed from the May 9th sprint. I'm just curious when you think this work will be addressed because I know that the Insights team may have a use for this block and they were hoping to start setting up their report in May?

**Comment by cdanfon** [comment]
Hey @beccaklam I've been making some changes to the way the engineering team uses the [board](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/board)

As the label 'engineering' was added to this issue I assumed I could make those changes to this ticket too - apologies if I messed something for you, it wasn't my intention. 

The sprint of May the 9th is perfect, but the idea with the engineering team moving forward is that no sprint gets assigned to tickets/issues beforehand, only during our sprint planning sessions. If the sprint labels get added to tickets ahead of planning, the session becomes a little bit redundant as the work has already been planned and sometimes we lose visibility of what we're meant to be doing during a particular sprint. 

If there are things that need to happen in a particular sprint, I think is best if this is communicated to me so that I can plan accordingly having a full picture of priorities. 

Happy to elaborate further in our standup today :)

**Comment by cdanfon** [comment]
Hey @fessehaye After a chat with @beccaklam yesterday I've removed #8374 from your sprint in favour of this ticket as it has higher priority. 

I can see that both you and @danielfmiranda have been assigned to this ticket, is this something you need to work together on and that would take 4 story points for each of you?

**Comment by beccaklam** [comment]
@cdanfon I think I assigned both simon and daniel to that ticket so they can decide who would take the ticket!
