### ISSUE TITLE
SEO | Unlocalized pages being published

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#8549]
# Description

Mozilla.org currently localizes content using methods that make it difficult for Google to find our non-en content and to understand which countries it is intended to serve.

**Domain Redirect**
We respond to requests for the domain name, i.e. https://www.mozilla.org/, with a redirect to a localized version of the site, based on the IP address of the requestor. Please see the HTTP viewer results here to see a redirection to en-US without a browser language setting.
Global navigation links to other Mozilla subdomains, e.g. from the www site to https://foundation.mozilla.org/ in global navigation, are not localized, and again rely on a redirect to find localized content.

**SEO Recommendation**
1. Do not auto-select a language and country for a user. Allow the user to choose their language and location.
     a) Serve a static page at https://www.mozilla.org/ with static links to all of the regional Mozilla sites. The …/locales/ page content would be ideal. Crawlers will be able to find all of the sites by following the links, and we will present no unintended prioritization of en-US over all other languages and regions.
     b) Use a pop-up to suggest which localized site we think will be best for the user, based on their IP or language setting. Allow the user to select from other choices if we offer the wrong language.

2. Use correctly localized links in all navigation. Do not use redirection to find localized content.
      a) Update all links between subdomains to use the appropriate localization string.

**Inconsistent Translation**
It appears that Mozilla has only localized some of the content for some of the languages that we wish to support (e.g. ach, gd, is). Navigation links in those non-English locales use English anchor text, and some localized pages link to unlocalized pages from the global navigation or footer.

To see a link to a localized URL that does not exist and results in a redirection, please see HTTP viewer results here.

**SEO Recommendation**
1. Remove all links to unlocalized pages. 

2. Translate all English copy on non-EN pages.

3. All English-language pages that were previously published on non-English URLs should be deleted. Those URLs should return a 404 “File Not Found” server status code, e.g. …/ach/firefox/privacy/, which Google indexes with en-US content.

# Acceptance criteria

- [ ] Add criteria here 

# Dev tasks 

- [ ] Add dev tasks here

**Comment by cdanfon** [comment]
Hey @tbrlpld I can't add any tags or info to this ticket other than comments. Can you do the following for me please?

1. Add the following tags: engineering,Maintain
2. Move it to 'Backlog' pipeline

Thanks!

**Comment by cdanfon** [comment]
@fessehaye to catch up with Kalob about grooming this ticket

**Comment by KalobTaulien** [comment]
I might be able to add some additional context here. 

First, this issue was an audit done for Mozilla.org that _could possibly_ be applied to foundation.mozilla.org. 

For the SEO Recommendation, if I recall correctly, we _wanted_ to auto select the language and country for a user. It looks for their browser settings and uses their preferred language, if it's set. Otherwise it should default to English. We chose not to implement a popup and instead use the method we had in the footer to change the users language setting using a dropdown. If they change their language on the site, that will change the URL of the page and redirect them to the localized version of the page they were on. 

Using localized links with Wagtail is tricky. The Foundation site a multisite instance of Wagtail, not a separate website for each language. So it's one codebase running at least 2 websites with multiple languages. Because of that we _want_ to link to the non-localized version of a page and let the users browser (or selected language on the website) settings kick in. So if a user went to https://foundation.mozilla.org/what-we-fund/ it would auto-detect the language their browser is using (or the language they selected on the site) and redirect to https://foundation.mozilla.org/{language_code}/what-we-fund/. Redirecting can sometimes be bad, but in this case I think it's good. This allows us to link to any page from anywhere on the foundation website and keep the preferred language for the user.

If we were running different websites for each language, we wouldn't need to auto detect languages and could offer a popup for the viewer to select, and redirect from there. But because it's a single website that's probably not a good idea. If we explicitly linked to localized urls, we could accidentally be sending non-English users to English pages, even if they don't want to see that. So it's better for us to detect the language and redirect than it is to constantly give them links to pages using the wrong language. 

All of these decisions were made on purpose for the foundation site last year because:
1. We don't want to force people to read pages that aren't in their preferred language, and
2. They might prefer a different language on the site than what their browser has, and should be able to change it at any time, and 
3. Using middleware to redirect users was more friendly than forcing a popup modal on the viewer

I hope this context helps! Feel free to reach out to me any time for further clarification.
