### ISSUE TITLE
[Blog] - [Author] - Author Detail Page Template

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8796]
The goal of this ticket is to create the "Author Detail" template that will render whenever a user visits an Author's Detail page.

A good example of a page touring and rendering detail pages is the [research hub author detail page](https://github.com/mozilla/foundation.mozilla.org/blob/7f955673295ff6d593bbdb9cc407a531d308747d/network-api/networkapi/wagtailpages/pagemodels/research_hub/authors_index.py#L51)

Acceptance Criteria:
---

- [x] There is a new route, along the lines of "blog/author/<author_name>  that will render the new template when visited.
- [x] Based on the author in the URL params, it should pull their data. At the moment, just rendering name and bio without styling will work.
- [x] Blog cards and blog posts are updated so that the author names are linking to the authors detail page.

Dev Steps:
---

- [ ] Create a new route for this template, using the link above for reference
- [ ] Figure out what behavior we would like for the "/authors/" route, should we render a list of authors? Or, should we redirect back to the blog page.
- [ ] Create a new template for the author detail page
- [ ] Render with minimal styling, the authors name and bio when visiting the author detail page

**Comment by tbrlpld** [comment]
@danielfmiranda Since we are already using the routable page approach for the topics, maybe we can also reuse that for the authors? In that case we wouldn't need a separate page model. Overall the blog is a bit different from research hub in that the blog index combines the landing, library and author index page types into one.

**Comment by tbrlpld** [comment]
@kevinhowbrook Yes, you are right the dev task and acceptance criteria are not quite lining up. @danielfmiranda do you think we really need a new page type or would a route also work? 

Good question about the authors on the blog cards / blog pages. I think that would make sense to turn the author names on the card/posts into links to the author page from there, because I think there is no other way of reaching the author pages. @danielfmiranda @nancyt1 Do you have more info on this?

**Comment by nancyt1** [comment]
@tbrlpld Yes, author names on the cards and posts should link to their author page.

**Comment by tbrlpld** [comment]
Thanks @nancyt1 

@kevinhowbrook I have added the respective acceptance criterion

**Comment by tbrlpld** [comment]
Perfect. Thanks @danielfmiranda

**Comment by kevinhowbrook** [comment]
I've marked my first pr ready for review https://github.com/mozilla/foundation.mozilla.org/pull/8982

I imagine it might need some more template work, keen to get a handle on the working patterns so thought I'd open for review :)
