### ISSUE TITLE
[Blog] - [Search] - Search Functionality

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#8843]
This goal of this ticket is to implement the search functionality of the blogs "search" page.

The search rankings are as follow:

1. Title
2. Category
3. Author
4. Tags
5. (Search/Meta) Description 
7. Body text
8. Date
9. Language

Dev Steps:
--- 

- [ ] Render the search bar template from #8778 into the new search page template from #8772 
- [ ] Implement the search functionality, using the search rankings above.

Acceptance Criteria:
---

- [ ] Users should be able to type a search query in the search bar, when they hit enter or click the icon, the list of search results should filter and update accordingly, displaying the first 6 entries of the list.

**Comment by tbrlpld** [comment]
@danielfmiranda @nancyt1 I am also unsure if the search for "date" will work. This might get extremely complex because of all the different date formats that are possible. In the database dates are saved as timestamps, like so `2022-05-13 20:26:34.000000 +00:00` This would not match if someone searches for "may" for example. It could match if someone enters a timestamp format. If we wanted to translate from something like "may" to a timestamp, that would mean we would need to parse every query in many ways to see if it fits a date format, which I think gets really complex quickly.

**Comment by tbrlpld** [comment]
@danielfmiranda @nancyt1 What does "preview text" refer to? Is that the text on the blog cards? If so, I believe that is only the combination of the "meta description" and the first bit of the "body text" if no meta description exists.

**Comment by nancyt1** [comment]
@tbrlpld Hm, yeah for date I was thinking if someone knew the time frame they wanted to look in about a particular topic they can search that but if it's too complicated, I don't think it's crucial right now.

And yes, I think we have some articles that are only in non-english languages so it could be nice to look up those articles without needing to change the language of the whole page. 

Sorry yeah the preview text and description are the same thing, I was referring to the meta description.

**Comment by tbrlpld** [comment]
Ah ok. I think I need to think about that language thing a bit more. Usually I think we try to avoid showing pages from other languages/locales when searching. For example, when a page in a different locale is not yet fully translated it is an alias of the english page and has all the same content. That means we would show all those pages too when someone searches in english. 

@TheoChevalier do you have some input on this maybe?
