### ISSUE TITLE
[RH] SPIKE - can't save reordered research links

### ISSUE THREAD

**Issue by bheasman** [mozilla/foundation.mozilla.org#9031]
### Describe the bug
Reordering research links on the research detail page doesn't work

### To Reproduce
1. Go to a Research detail page in staging (e.g. https://foundation.mofostaging.net/cms/pages/18276/edit/)
2. Reorder the research links
3. Hit Save
4. The links revert to their original order

### Acceptance criteria

- [ ] Research links save in their reordered position and render accordingly in the FE

### Desktop (please complete the following information):
- Chrome on Mac OS Monterey

**Comment by cdanfon** [comment]
[timebox of 2 hours]

**Comment by danielfmiranda** [comment]
Hi Everyone, 

After looking into the issue a bit, I found this article https://github.com/wagtail/wagtail/issues/4477 which was actually created by Pomax 😄 if I understand correctly, since this model is set to inherit from the translatablemixin as well as orderable, we need to manually update the meta to:

```
    class Meta(wagtail_models.TranslatableMixin.Meta, wagtail_models.Orderable.Meta):
        ordering = ['sort_order']
```

which I have done in https://github.com/mozilla/foundation.mozilla.org/pull/9112

Another example of us doing this can be found here https://github.com/mozilla/foundation.mozilla.org/blob/f413a52501b3d169b1774cd1e66ddaf3b71af363/network-api/networkapi/wagtailpages/pagemodels/products.py#L441-L443

**Comment by bheasman** [comment]
Thanks @danielfmiranda - nice find!

**Comment by bheasman** [comment]
Thanks @danielfmiranda - have tested this on staging and it looks good. Has it been merged to prod yet?
