### ISSUE TITLE
[PNI] - Create PNI Article Page [Backend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9083]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=2303%3A126762

* This can basically be a copy of the blog page type
* Authors
    * Already exists on the blog page. But, is a little different here.
    * Since we have no author index, the names should not be links. 
    * Orderable through-model to profile. 
* Content category
    * Can this be more than 1 content category (topic)? -> Yes
    * Orderable through-model to content category (#9111). 
* Related articles (TBD)
    * Similar to the “related articles” for the “product categories”, this can be one list that is split and rendered in two locations on the page.
    * Orderable, through-model to other article pages. 
* Body – same as blog.
* Banner image – same as blog
* Newsletter CTA is frontend only.

Dev Tasks:

- [ ] Create backend page type
- [ ] Add factors for new page type

Acceptance Criteria:
* [x] PNI Article Page Type Available
* [x] Article Page Type only available under PNI content index page
- [x] As a Wagtail user I can add Authors to the article and order them manually 
- [x] As a Wagtail user I can add more than 1 content category
- [x] As a Wagtail user I can order the content categories using the same approach as per #9111
- [x] As a Wagtail user I can add related articles
- [x] As Wagtail user I can add locations on the page that are orderable through-model to other article pages. 
- [x] As Wagtail user I can a 'body' field to the article
- [x] As Wagtail user I can I can add a 'banner image' field to the article
- [x] As Wagtail user I can add a 'Newsletter CTA' to the article that only shows front end

<img width="805" alt="image" src="https://user-images.githubusercontent.com/2374073/178846595-fcca7a20-3250-4705-8bd3-2a0d68207588.png">
<img width="804" alt="image" src="https://user-images.githubusercontent.com/2374073/178848292-aaae641d-26de-459d-a109-d4d5cb6f397e.png">

**Comment by beccaklam** [comment]
@tbrlpld Re: authors did we want to link to the author index we're using for the foundation site? cc: @kristinashu @nancyt1

**Comment by tbrlpld** [comment]
@beccaklam My first hunch was not. That is because currently there isn't really a central profile/author index. We have separate ones for blog and research hub. Maybe this is something we could handle more centrally? 

The question there would be what related posts should we show?

**Comment by kristinashu** [comment]
In terms of content entry: Both blog and research hub pull info from Profile https://foundation.mozilla.org/cms/snippets/wagtailpages/profile/, right? It would be nice to be able to pull the names from there rather than having to add them in again. 

In terms of IU and what our audience see: I agree that, at this stage, we should not make the names clickable.

**Comment by tbrlpld** [comment]
@kristinashu Yea, we will definitely be pulling the information from the profiles. Only so far there is not way to reach further information about the author.

**Comment by tbrlpld** [comment]
@cdanfon This is now ready on the preview app: https://foundation-pni-2022.herokuapp.com/cms/pages/1444/

**Comment by cdanfon** [comment]
@tbrlpld  A few questions regarding some ACs: 

_- As a Wagtail user I can add more than 1 content category_ - **There's a limit of 2, is this intended?** 
_- As Wagtail user I can add locations on the page that are orderable through-model to other article pages._ **I couldn't do this**
_-  As Wagtail user I can I can add a 'banner image' field to the article_ **I can add an 'image' to the back end, however this won't show in the FE, is that the expected behaviour, or should the image appear even if not styled?**
_ - As Wagtail user I can add a 'Newsletter CTA' to the article that only shows front end_ **This field is not present in the BE (screenshot attached)**

![Screenshot 2022-08-12 at 13.11.51.png](https://images.zenhubusercontent.com/624c0bfa(994c73e54a68130b/37ddda8f-d27c-4f3e-b40e-37fc94a84490)

**Comment by danielfmiranda** [comment]
Hi @nancyt1 @beccaklam!

I was wondering if you could please help me find the answer to some of the questions above:

- **As a Wagtail user I can add more than 1 content category**
  - If I remember correctly there was discussion to limit this at 2, similar to how blog pages are limited to two topics, however, I was wondering if you could please confirm if this is the case
- **As Wagtail user I can add locations on the page that are orderable through-model to other article pages.**
  - I am not too familiar of this ask, I was wondering if one of you or @fessehaye  could provide more context on this one please.**
- **As Wagtail user I can add a 'Newsletter CTA' to the article that only shows front end**
  - Is the newsletter sign up box supposed to show up on every product page, or should the user be able to select whether or not they want the box to appear. (we can have it default to yes/no). Also, which style of sign up box would this be: the "popout" style or the new "PNI" Style

---

@cdanfon to answer the question **"I can add an 'image' to the back end, however this won't show in the FE, is that the expected behaviour, or should the image appear even if not styled?"**:

- I just tested this out on my local machine, and it appears that this field is covered by the "hero image" field in the CMS. However, since this ticket was just for the back end work, the image appears, however it is unstyled as this is going to take place in the front end ticket 👍 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/18314510/184763591-5ee7c5bf-4b8e-41e8-a5ff-1fd1f0dc7e5a.png">

**Comment by nancyt1** [comment]
Hi @danielfmiranda !
- Yes we should still limit to 2 categories
- I'm unsure what this question is asking, what do you mean by locations?
- And yes, newsletter cta should show up on every article page and in the PNI style. Here's the [link](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3406%3A38682) to the most recent design.

**Comment by danielfmiranda** [comment]
Thanks @nancyt1!

In regards to the "Location" question, I had a discussion with @beccaklam and we believe that this line is actually referring to the "Related Articles" which has been implemented.


---

@cdanfon it looks like we have the answers to these questions now :D 

- As a Wagtail user I can add more than 1 content category_ - **There's a limit of 2, is this intended?** 
        - (Yes, this is intended)
- As Wagtail user I can add locations on the page that are orderable through-model to other article pages._ **I couldn't add locations to the page**
       - (This is referring to the "Related Articles" section, I pulled this branch and can confirm that you can set these)
-  As Wagtail user I can I can add a 'banner image' field to the article_ **I can add an 'image' to the back end, however this won't show in the FE, is that the expected behaviour, or should the image appear even if not styled?**
       -  (The image does appear in the template, though unstyled, as the styling takes place in #9238 )
- As Wagtail user I can add a 'Newsletter CTA' to the article that only shows front end_ **This field is not present in the BE (screenshot attached)**
       - (This work is also taken care of in the front end ticket #9238)

**Comment by cdanfon** [comment]
All good, thanks @danielfmiranda
