### ISSUE TITLE
Remove grey line at bottom of featured posts

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#909]
Remove the grey line at the bottom of the featured post for both 'Latest from the Network' and 'Get Involved' sections:

### Production:
<img width="1133" alt="screen shot 2017-11-15 at 12 30 21 pm" src="https://user-images.githubusercontent.com/1068783/32858620-eff51880-ca00-11e7-924c-1617f739463f.png">

### Comp:
![screen-shot-2017-11-15-at-12 30 21-pm2](https://user-images.githubusercontent.com/1068783/32858690-2e6b8f5e-ca01-11e7-9c7c-8b57eaf3ef98.jpg)

@taisdesouzalessa @sabrinang is that ok?

**Comment by taisdesouzalessa** [comment]
@kristinashu I think for the desktop it looks ok but for the mobile view, I feel the card without the line loses the sense of "unity" - the copy gets a bit lost there...what do you think? Curious about what Sabrina thinks as well.

I wonder if there is any alternative treatment for this featured item we coul use.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/22157921/32866838-8063ab94-ca1e-11e7-98d5-32964755895b.png">

**Comment by sabrinang** [comment]
Yes - good point @taisdesouzalessa 
Since we are using this white card in a 2 column style we will run into the white spaces blending together over a text section on mobile. The mozilla.org site avoids this issue by making the section the full width so a gradient divider always falls below and as well as having a built in divider/underline for their read mores (there are lots of horizontal lines happening visually though would prefer if this was less heavy) 
<img width="324" alt="image" src="https://user-images.githubusercontent.com/2492510/32867166-6c9d0ea0-ca20-11e7-95f2-ce9afbe11faa.png">

Is the point is to unify these styles with broader moz.org or just cleaning up this area visually?

**Comment by kristinashu** [comment]
Yes, good point! Goal is to have fewer styles so we can be more consistent but let's leave this one as is for now.
