### ISSUE TITLE
[PNI] - Related component - [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9095]
[Link to Figma Components](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3240%3A32961)

![image](https://user-images.githubusercontent.com/2374073/181870712-2ce50805-be3a-44e2-9e70-3561ece4913c.png)

Related blocks will be included on:
* Article Pages
* Product Pages
* Category Pages
* Home page 

Related Content block will both be using PNI articles for data

Dev Tasks: 
* [x] Add wagtail template for related block
* [x] allow optional `All Articles` link on bottom
* [x] Uses 3 articles max

Acceptance Criteria:

- [x] Component is created to be reused for multiple PNI Pages
- [x] "Related" in the Featured section of the Homepage, Product detail page, and Article Index pages do not have CTA links
- [x] All "Related" blocks have short squiggles
- [ ] "Related" on Category pages articles should have "**All articles**" CTA link

**Comment by fessehaye** [comment]
typeface hasn't been finalized yet

**Comment by beccaklam** [comment]
@danielfmiranda Styling for this still needs to be finalized, hopefully by the end of this week (July 21, I'll let you know if it's done sooner). If you get to this ticket before then, can we break this up into backend and frontend work and you can start the backend work first? cc: @kristinashu @nancyt1

**Comment by cdanfon** [comment]
@fessehaye Can you please split this ticket into FE and BE tasks please?

**Comment by cdanfon** [comment]
This can be completed after #9151 has ben done.

**Comment by cdanfon** [comment]
Hey @danielfmiranda  #9151 is now complete and this ticket finalised.

**Comment by danielfmiranda** [comment]
Thanks @cdanfon! I have opened #9333 and submitted it for review

**Comment by cdanfon** [comment]
Hey @danielfmiranda thanks! Is this ticket ready to be tested. I'm confused as I can see all the ACs marked as passed. 

I would expect the ACs to be marked as passed by a non dev QA tester (on this case myself) but I don't recall testing this ticket.

**Comment by danielfmiranda** [comment]
Hi @cdanfon! Yes this ticket is ready to be tested :+1:

**Comment by cdanfon** [comment]
Looks good to me, passing QA and closing!

**Comment by cdanfon** [comment]
@fessehaye @tbrlpld Same with this one, it has been marked as passed because the ACs had been satisfied, but when navigating the staging site the "Related articles' keep appearing on random places. See below:

![Screenshot 2022-09-22 at 14.06.08.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/0f68dc2b-5a48-428b-86d0-abc4b80e3506)
![Screenshot 2022-09-22 at 14.06.54.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/19f6e9a4-9d4b-4146-adc9-8b3dc3da6981)

As Daniel is out we might need to discuss in our daily huddle the best approach with the time we've got left 

@mtdenton & @kristinashu fyi

**Comment by cdanfon** [comment]
Thanks for explaining Tibor! Makes sense
