### ISSUE TITLE
[PNI] - Category Page Visual additions

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9096]
https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3080%3A30591

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/2ae1c670-d267-4c25-abf9-f34b84e267a5)

![image.png](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/4f01b672-c8ef-4501-8247-96bccb1ef376)

Dev Tasks:
* [ ] Add Event Component before Product Items (2x Width)
* [ ] Add Related Readings Component after 5 Products (2x Height)
* [ ] Need more info for ~`More from PNI`~ 'What to read next'

Acceptance Criteria:
* [ ]  Category pages should always include `What to read next` subsection on the bottom
* [ ] Campaign ask is always visible in product review grid
* [ ] Related Readings is always visible in product review grid

**Comment by cdanfon** [comment]
@beccaklam to update the design, @fessehaye to update the ticket if needed

**Comment by beccaklam** [comment]
Design has been updated. @fessehaye I'm not sure what you need regarding 'More info on 'What to read next'?

**Comment by tbrlpld** [comment]
@fessehaye I am confused about the ACs here. Requiring the sections to be visible would require the data to be present in Wagtail. Especially the "what to read next" section can only be shown if at least 4 related articles are defined. Is this definitely a requirement? Because I am not sure we will have enough content in the beginning to have articles to fill "what to read next" for every category. And probably we want to avoid situations where we render the heading but there are no articles to show.

**Comment by tbrlpld** [comment]
I believe this ticket is outdated.

**Comment by fessehaye** [comment]
This ticket has mostly been done via other tickets/tasks. It is outdated now so I am closing
