### ISSUE TITLE
[PNI] - Create PNI Article Page [Frontend]

### ISSUE THREAD

**Issue by fessehaye** [mozilla/foundation.mozilla.org#9104]
[Desktop comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3406%3A38682)
[Mobile Comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3471%3A46724)
[Tablet Comp](https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3738%3A45437)

* This can basically be a copy of the blog page type
* Authors – already exists on the blog page
* adding related reading are apart of a seperate ticket that will be added later

Dev Tasks:

- [x] Style Article page
- [x] Include mobile styling
- [x] Include tablet styling
- [x] Add Newsletter CTA

Acceptance Criteria:
* [ ] PNI Article Page Styled Correctly
* [ ] PNI Article Page Works for Mobile and Tablet
* [ ] Newsletter CTA is visible

![Article Page Type.jpg](https://images.zenhubusercontent.com/57acd65ce40e5714b16d4215/126ebb64-31c7-4a95-8d01-d3c1519c1065)

**Comment by tbrlpld** [comment]
@fessehaye The newsletter CTA is a frontend thing. Might need a separate ticket for that.

**Comment by fessehaye** [comment]
* Related reading card is the same as homepage
* Current blog is MVP for stylings

**Comment by fessehaye** [comment]
https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/articles/this-is-a-test/

**Comment by cdanfon** [comment]
Hey @fessehaye I've checked the link, thanks for adding it. 

A couple of notes: 

1. In the desktop version, on Chrome, looks like there's too much padding-top & bottom compared to the Figma design. 
2 In the mobile version, using inspect tool and Samsung Galaxy S8 the shape of the box is horizontal instead of landscape as per Figma file. 
3. In the table version, using inspect tool and iPad Air, there's too much padding top & bottom.

See attached examples: 

![desktop.png](https://images.zenhubusercontent.com/624c0bfa994c73e54a68130b/2e6cdfdc-00e6-4f61-a08a-950b6420f852)

**Comment by fessehaye** [comment]
@nancyt1 reviewed the updated changes and approved so I will move this to the next column 

![image](https://user-images.githubusercontent.com/2374073/186768052-3e0cf145-c80d-4b77-b860-0e53bd42994f.png)
