### ISSUE TITLE
[PNI] CTA component [Backend]

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9188]
# Description

Create a `BuyersGuideCallToAction` snippet. This ticket is only for the backend. No **styling will be added as part of this ticket**. 

Design: https://www.figma.com/file/GwdoUiY4fzVyeLfXsAJGPq/*Privacy-Not-Included-Website?node-id=3231%3A33672
Implementation notes: https://docs.google.com/document/d/12AmWzlOVll6hHBPL-lu3E4rAtOM9vX6wgO6U8uOxCxk/edit#heading=h.f77npuk7soin

![image.png](https://images.zenhubusercontent.com/61e1e4f0d1fded7471402d12/6b2c0fd0-075f-45a9-aa23-62299961ad1a
)

# Acceptance criteria

- [x] As an editor, I can create `BuyersGuideCallToAction` snippets.
- [x] As an editor, I can set a sticker image, title, content (rich text) and an action link text and action link target for the snippet.
- [x] As an editor, I can select a Wagtail page or provide a full URL for the action link target.
- [x] As an editor, if  add a action link target but select neither, a Wagtail page nor  a full URL for the action link target I get an appropriate error message telling me to select one.
- [x] As an editor, if select both, a Wagtail page and a full URL for the action link target I get an appropriate error message telling me to only use one.
- [x] As an editor, I can select on the buyer's guide homepage which of the buyer's guide CTAs should be the "buyer's guide featured CTA". 
- [x] As a site visitor, I see the featured CTA displayed on the buyer's guide homepage. 
- [x] As a site visitor, I see the featured CTA displayed on the buyer's guide editorial content index page. 
- [x] As an editor, on the buyer's guide product category snippet I can define whether or not I want the CTA to display on this categories detail page
- [x] As a site visitor, the CTA should only show up on Category detail pages with "show_cta" set to True
- [x] As a site visitor, any product with a category set to show the CTA, will also show the CTA as well.

**Comment by cdanfon** [comment]
@cdanfon to add ACs to this ticket

**Comment by danielfmiranda** [comment]
Hi @tbrlpld, I have a quick question about the last acceptance criteria:

"As a site visitor, on a product page I see the CTA related to the most specific category of that product. E.g. if the parent and the child category both have a related CTA defined then I see the child's CTA because that would be more specific."

It appears that products have no limit regarding how many categories can be set as related. What should we do if there are multiple categories with CTA's linked to the product? 

For example, a product with two level 1 categories with CTAs.

**Comment by tbrlpld** [comment]
> Hi @tbrlpld, I have a quick question about the last acceptance criteria:
> 
> "As a site visitor, on a product page I see the CTA related to the most specific category of that product. E.g. if the parent and the child category both have a related CTA defined then I see the child's CTA because that would be more specific."
> 
> It appears that products have no limit regarding how many categories can be set as related. What should we do if there are multiple categories with CTA's linked to the product?
> 
> For example, a product with two level 1 categories with CTAs.

Sorry @danielfmiranda I don't know. One for @beccaklam, maybe.

**Comment by beccaklam** [comment]
@danielfmiranda I think that would be a really rare instance, and actually the way we've designed the site we should only have one CTA going at a time. We're quite far from having to multiple CTAs on the site right now so I think that will be something we solve for in the future when the need arises. @kristinashu any thoughts?

**Comment by kristinashu** [comment]
So an example would be: there's a product page for a kids watch, the product is in both Wearables and Toys, both Wearables and Toys have CTAs, which CTA should we show on the product page? idk lol. It does seem like a rare case. I'd say go with whichever is easiest to implement - random, alphabetical??

**Comment by danielfmiranda** [comment]
Thanks @kristinashu @beccaklam!

Just commenting to keep record that after our discussion in slack, we are only running one CTA at a time and it is set on the Buyers Guide home page

**Comment by danielfmiranda** [comment]
Hi @cdanfon! This ticket is now ready for review on the staging app: https://foundation-pni-2022.herokuapp.com/en/privacynotincluded/ using the AC above.


One thing to note however, is that the CTA on the **category** page will only display if you also set some related articles.
This has been fixed in https://github.com/mozilla/foundation.mozilla.org/pull/9408 and is awaiting review. Sorry about that! 

If you would still like to test, please set some related articles for a category, and the "show_cta" functionality will still work as expected.

**Comment by cdanfon** [comment]
All ACs satisfied and ready to go! 

@tbrlpld @fessehaye  'cc you in as Daniel is out today
