### ISSUE TITLE
GA4 | Add data layer for form tracking 

### ISSUE THREAD

**Issue by cdanfon** [mozilla/foundation.mozilla.org#9271]
TBX Digital Marketing team have put together 2 data layer pushes as part of our ongoing work for GA4:

**1) Petition Signature**

The following is a populated example of a  data layer push that should take place whenever a form has been successfully submitted.

Example form: https://foundation.mozilla.org/en/campaigns/petition-slack-block-abuse/

```
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
	'event' : 'form_submission',
	'form_name' : 'Tell Slack: #BlockAbuse',
	'form_location' : 'foundation.mozilla.org/en/campaigns/petition-slack-block-abuse/',
	'form_type' : 'petition-form',
         'form_id' : '8611'
});
```

**2) Comment Submission**

The following  is a populated example of a  data layer push that should take place whenever a comment is submitted

Example form: https://foundation.mozilla.org/en/privacynotincluded/threema/

```
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
	'event' : 'form_submission',
	'form_name' : 'Threema',
	'form_location' : 'foundation.mozilla.org/en/privacynotincluded/threema/',
	'form_type' : 'petition-form',
         'form_id' : '8611'
});

```

I've attached a Guide document which includes a Reference guide providing descriptions for the variables featured in the above example.

[Mozilla - data layer guide.pdf](https://github.com/mozilla/foundation.mozilla.org/files/9432567/Mozilla.-.data.layer.guide.pdf)

****NOTE:** Please add to staging first so that TBX DM team can test.**

**Comment by cdanfon** [comment]
@danielfmiranda Please prioritise and let me know once completed so that TBX can test

**Comment by danielfmiranda** [comment]
Hi @cdanfon!

 I was able to get the event to work for when users submit petitions 👍

However, I do have a question for the second ask of this ticket, which is firing an event when a user submits a comment on a product:

<img width="1198" alt="Screen Shot 2022-08-31 at 5 22 02 PM" src="https://user-images.githubusercontent.com/18314510/187807022-8e41fcf2-bbcd-4351-a6cd-f9989fb4e392.png">


The comment box above is actually not rendered/controlled through us, it is being rendered using a package called [Commento](https://commento.io/). 

The only commento related code that we use, is defining a block where we want the comment box to appear, and the package's external JS handles the rest:

```
# The div where the comment box renders
<div id="commento">
</div>

# External script
<script async defer data-hide-deleted="true" data-no-fonts="true" src="https://cdn.commento.io/js/commento.js</script>
```



Due to this, I think there are two ways in which we can get this to work, and I was hoping to hear your and the torchbox teams opinion:


**Option 1 (a bit of a workaround, but I believe it will do what we need it to)**
---
- I can create a new JS file, with a function that will fire off when the user clicks the "add comment" button
- This function can check for the following:
    - A div that only renders when a user is logged into commento
    - That the text box element has content within it
- If these requirements are met, I think its safe to assume that a comment will be submitted successfully, and we can fire off the datalayer event


**Option 2 (though might not be possible)**
---
Looking at the commento docs, I found the following paragraph:
 ``` 
Commento is quite configurable. You're free to inject custom styling CSS, **JavaScript**, display comment counts, and so on. 
``` 
Beyond this however, there was no other mention on how to inject custom javascript for commento. I also took a look at the source code and from what I could see, was not able to find any functionality regarding custom JS or callbacks.

However, it might be worth a shot to reach out to commento support to see if they have a built-in method of firing events whenever a comment is submitted succesfully? 

If we would like to go this route, I can create a new ticket just for the comment datalayer event as communicating with support might take some time.




Thanks in advance!

**Comment by cdanfon** [comment]
Hey @danielfmiranda thanks for the detailed explanation! 

We would recommend Option 2 as the first approach, if it turns out not to be possible we can always fall back on Option 1. 

Thanks!

**Comment by cdanfon** [comment]
Hey @danielfmiranda to confirm, when you say:

> _I was able to get the event to work for when users submit petitions 👍_

Do you mean this has been pushed to staging already or that you managed to get it to work for you locally? 

Just checking as TBX have tested the Petition Signature data layer push in staging and doesn't seem to be working :)

**Comment by danielfmiranda** [comment]
Hi @cdanfon! Responding to the second comment, I meant that I was able to get it to work locally, and have the changes ready in the Draft PR #9295. 

If you would like, I can get this merged into staging, and then handle the product comment event in a different PR!

**Comment by cdanfon** [comment]
Yes, please! Thanks @danielfmiranda

**Comment by danielfmiranda** [comment]
Will do! @cdanfon 

The first PR is now merged into staging and ready for testing by the torchbox team.

I also have sent an email to commento support, and will update you next Tuesday with their response.

**Comment by cdanfon** [comment]
Hey @danielfmiranda 

TBX has tested the event on this page https://foundation.mofostaging.net/en/campaigns/petition-slack-block-abuse/ and unfortunately it does not seem to be working. 

Can you confirm if you've applied this to all forms? If not can you please send a link to a page with a form that can be tested? 

Thanks

**Comment by danielfmiranda** [comment]
Hi @cdanfon! Apologies for that 😅 I had forget to push to staging, it is now ready for testing whenever you or the torchbox team have time. Thanks and let me know if there is anything else I can help with!

**Comment by cdanfon** [comment]
Hey @danielfmiranda we have tested 1) Petition Signature and it's working on staging. Thanks for doing that. 

Can I check with you if a ticket has created for the follow up of _Option 2_ for the Form Submission data layer push? Thanks!

**Comment by danielfmiranda** [comment]
Hi @cdanfon I have created https://github.com/mozilla/foundation.mozilla.org/issues/9336 to represent the work needed for commento comments. Should I assign it to myself for this sprint?

**Comment by cdanfon** [comment]
Hey @danielfmiranda thanks for creating this ticket! Yes, please assign it to you :)
