### ISSUE TITLE
Figure out why redirects aren't working

### ISSUE THREAD

**Issue by alanmoo** [mozilla/foundation.mozilla.org#937]
Redirects added at https://foundation.mozilla.org/admin/redirects/redirect/ aren't working (they 404). Let's figure out why.

**Comment by alanmoo** [comment]
It appears that locally it's doing a 301. That's...not ideal, as the redirect I want to use for now will eventually be disabled to hit pages served by Mezzanine

**Comment by cadecairos** [comment]
Here's what I found out:

* Only breaks when `DEBUG=False`
* The view handler `handler404` in urls.py is a RedirectView, so it's returning a 302 response to `/errors/404` if the router can't match the requested path to a view.
* When `DEBUG=True` handler404 doesn't execute, it seems.
*  Handler404 turns what would be 404s into 302s, so when the RedirectMiddlware is executed for the request, it doesn't do anything, because it only looks for 404s 

In order to fix this, our handler404 can't set the response code to 302 before the redirect middleware executes. I see two ways forward:

1. Make the 404 page a view in Django
2. Remove the `handler404` setting, and sub-class the RedirectMiddleware to do what we want (lookup redirects in the DB, or redirect to `/error/404`

**Comment by cadecairos** [comment]
@alanmoo This is still assigned to me - we need to make a decision as to which way to fix this. I'm okay with either of the options I laid out, however #2 diverges our code from Django/Mezzanine core even more, which might burn us in the future.

**Comment by alanmoo** [comment]
Then yeah, let's stick with option 1. What's the actual work required for that? It might be something we can leave up for a contributor to pick up if they're interested until someone on the team has a chance to get to it.

**Comment by alanmoo** [comment]
Will this be resolved once Wagtail is handling our 404's?

**Comment by cadecairos** [comment]
It should be resolved once we stop relying on a statically built frontend that's served via whitenoise.

**Comment by kristinashu** [comment]
Will redirects work now?

**Comment by cadecairos** [comment]
Not yet, we still need fix the problems outlined in [this comment](https://github.com/mozilla/foundation.mozilla.org/issues/937#issuecomment-356433137)

**Comment by alanmoo** [comment]
We have stopped serving those pages statically, and I believe I added a djano-based 404 page last week.

**Comment by cadecairos** [comment]
if it's ready to go, we should update [this line](https://github.com/mozilla/foundation.mozilla.org/blob/11cffb166109cb068a6056ebd50e8c4c454a23eb/network-api/networkapi/urls.py#L87) so that it's not a redirect to a static page.
