### ISSUE TITLE
DFL 2022 | Events - Text only card grid

### ISSUE THREAD

**Issue by kevinhowbrook** [mozilla/foundation.mozilla.org#9399]
### Describe the feature request
We'll need a `text grid` block to house / add individual text-only cards to.

### Screenshots / mock-ups
![Screenshot(7)](https://user-images.githubusercontent.com/2128707/191286471-0020e20b-fa98-4a68-90f1-bcf972f8460c.png)

### Additional context
Link to [designs](https://www.figma.com/file/goD9bRqPoedQAxi8OsInkR/Data-Futures-Lab%3A-Designs?node-id=644%3A7784)

---

**Dev Tasks:** 
* [ ] Create new text only grid block so text-only blocks can be added (up to 3 per)
* [ ] Configure new text block template

**Acceptance Criteria:**
- [ ] Design to look as per Figma files
- [ ] As an editor creating a banner page I can add  a text-only grid block with up to 3 inner text only cards 
- [ ] Template stacks verticle on mobile

NOTE: To be tested with #9398

**Comment by kevinhowbrook** [comment]
As per #9398 - this is ready for staging https://github.com/mozilla/foundation.mozilla.org/pull/9511

**Comment by kevinhowbrook** [comment]
Actually hold off on this. It's blocked by https://github.com/mozilla/foundation.mozilla.org/pull/9456 while the FE is done as it's based off that branch

**Comment by kevinhowbrook** [comment]
This has been rebased and is ready to deploy to staging https://github.com/mozilla/foundation.mozilla.org/pull/9511

**Comment by cdanfon** [comment]
@tbrlpld Another one for you please :)

**Comment by cdanfon** [comment]
@stevedya The underline should be black as per styler guide [here](https://foundation.mozilla.org/en/style-guide/#headers-links)

**Comment by stevedya** [comment]
@tbrlpld I've fixed this border issue and this is ready for you to to review here: https://github.com/mozilla/foundation.mozilla.org/pull/9566

**Comment by tbrlpld** [comment]
Two small question for me @stevedya

**Comment by stevedya** [comment]
@tbrlpld I've replied and will pass these back to you now

**Comment by cdanfon** [comment]
Looks good to me as per #9399 - over to you for MoFo testing @gutermul

**Comment by gutermul** [comment]
Looks good to me. The only thing I noticed when I recreated the events page is that the space below with the "mini image picker" has a fairly wide space between, but I think that that's actually because of the "mini image picker" rather than extra spacing below the text only card grid. See attached screenshot:



![Image](https://user-images.githubusercontent.com/21171146/198995168-2323cf7f-5e30-4647-a387-1973a49b3ee0.png)

**Comment by cdanfon** [comment]
Hey @gutermul yes, the spacing is due to the 'mini image picker' which was an element that already existed in the mofo website. 

I've created an example for you to see this: 

<img width="1179" alt="Screenshot 2022-10-31 at 11 25 28" src="https://user-images.githubusercontent.com/102978346/198997507-ef37eb91-dfbc-467e-b3ef-31b8c6bc5806.png">

**Comment by cdanfon** [comment]
This is now on prod. Closing as completed
