### ISSUE TITLE
Improve UX of promote tab on blog posts

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#9464]
Follow up from https://github.com/mozilla/foundation.mozilla.org/issues/7638

Goal: Make it easier for staff to add info in the promote tab as well as image the quality of our OG images for blog posts.

- [ ] Update name of `Search image:` to `Share image:` since this is a more accurate discretion 
- [ ] Make the `Share image:` a required field on all blog post pages
- [ ] Add hint text under `Share image:` that says "Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines [see here.](https://foundation.mozilla.org/docs/brand/brand-identity/social-media/#og-images)" Question for devs: Does the file size of the image matter or does Wagtail compress it?
- [ ] Make `Meta description:` a required field
- [ ] Remove the `Show in menus:` since it  doesn't actually do anything for blog posts
- [ ] Let Audrey know when this is live

Screen cap of current promote tab
<img width="683" alt="image" src="https://user-images.githubusercontent.com/1068783/194384042-9b7107c2-75c1-4307-be7a-1e7deae993ba.png">

cc @cdanfon @mtdenton

**Comment by cdanfon** [comment]
Thanks @kristinashu, we can include this in the sprint starting on Tuesday

**Comment by danielfmiranda** [comment]
Hi @kristinashu,

Was wondering if the following requests were for blog pages only, or sitewide:
- Update name of `Search image:` to `Share image:` since this is a more accurate discretion 
- Make the `Share image:` a required field on all blog post pages
- Add hint text under `Share image:` that says "Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines [see here.](https://foundation.mozilla.org/docs/brand/brand-identity/social-media/#og-images)"
- Make `Meta description:` a required field

Thanks!

**Comment by kristinashu** [comment]
Thank you for checking @danielfmiranda! 

Sitewide: 
- Update name of `Search image:` to `Share image:` since this is a more accurate discretion 
- Add hint text under `Share image:` that says "Image must be high quality, include our logo mark and have the dimensions 1200 x 628 px. For more design guidelines [see here.](https://foundation.mozilla.org/docs/brand/brand-identity/social-media/#og-images)"

Blog only: (not sitewide since some pages inherit from their parent page)
- Make the `Share image:` a required field on all blog post pages
- Make `Meta description:` a required field
