### ISSUE TITLE
Server Error (500) when publishing a blog post 

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/foundation.mozilla.org#9468]
### Describe the bug
URL of page producing error: https://foundation.mozilla.org/cms/pages/19553/edit/

### To Reproduce
1. Visit the link above
2. Try and publish the page
3. A 500 error will appear

### Expected behavior
The page should be able to be published as expected

**Comment by danielfmiranda** [comment]
When taking a look at the heroku logs while trying to publish, it appears that this error is being caused by translation keys for blog authors. Here is an excerpt of the error message that gets returned:

```
2022-10-07T18:15:14.446018+00:00 app[web.1]: Internal Server Error: /cms/pages/19553/edit/

2022-10-07T18:15:14.446033+00:00 app[web.1]: Traceback (most recent call last):

2022-10-07T18:15:14.446035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute

2022-10-07T18:15:14.446035+00:00 app[web.1]:     return self.cursor.execute(sql, params)

2022-10-07T18:15:14.446037+00:00 app[web.1]: psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "wagtailpages_blogauthors_translation_key_locale_i_d8e610e6_uniq"

2022-10-07T18:15:14.446037+00:00 app[web.1]: DETAIL:  Key (translation_key, locale_id)=(5da1d08c-57b7-4308-a362-c6e33e6f0058, 1) already exists.

```

Going to copy over the prod db to replicate the issue and search for a fix. If I recall correctly we have experienced this somewhere else as well

**Comment by danielfmiranda** [comment]
Hi Everyone, after taking a further look into this, I believe that the error is being caused by the snippet for this blog post's author not being translated yet. 

After pulling a copy of the prod-db into my local machine and looking at blog authors for different locales, I see that there are only 4 that have been translated. I then updated the blog post in question to use one of these translated authors, and was able to publish successfully. 

@TheoChevalier I was wondering if you could please give me a hand by letting me know how to translate blog authors? I am not too familiar with the translation workflow.

Thank you very much!

**Comment by TheoChevalier** [comment]
Hi @danielfmiranda, translating the blog author would only be a work around here, and the issue would still occur every time we add new locales.

If the issue is indeed related to the alias pages as I suspect, then it makes sense to me that publishing the page works when using translated snippets, since you’re no longer relying on alias pages and each locale has its own objects (each locale has its own page and its own author snippet).

I can see the page has been copied from another one, so something may have gone wrong here. It could be alias pages from the original page *and* alias pages from this one are trying to reference the same author snippet (same as in, with the same translation_key, which is forbidden).

I’ve tried locally, and updating the author to “Mozilla”, saving as draft, then switching back to Justyna and hitting publish has worked.

I’d suggest we use the solution I just described to publish this blog post, then try to replicate the original issue by copying blog posts and file an issue to https://github.com/wagtail/wagtail-localize if we succeed

**Comment by danielfmiranda** [comment]
Hi @TheoChevalier! Thank you very much for the heads up and for the workaround. I have tested it out and can confirm that copying a page leads to the issue as you mentioned. I have created an issue in the wagtail-localize repo: https://github.com/wagtail/wagtail-localize/issues/632 and was wondering if you could please do me a favor and give it a quick second look to see if I missed anything.

If it looks good to you, I can then close this ticket. Thanks!

**Comment by danielfmiranda** [comment]
After discussing with the team in our stand up meeting, I am closing this ticket as we have made wagtail-localize aware of the issue

**Comment by TheoChevalier** [comment]
Thanks Daniel for the thorough issue filed, don’t see anything missing!
