### ISSUE TITLE
Add anchors to People page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/foundation.mozilla.org#959]
@sabrinang @taisdesouzalessa @xmatthewx should profiles on the [home page](https://foundation.mozilla.org/) link to where they are on the [People page](https://foundation.mozilla.org/people/)? Seems like this would also be useful on the upcoming Fellowship pages as well.

Having anchors to everyone on the People might be useful. I remember it was a specific ask from fellows for previous sites, so they could share a link to themselves. 

E.g. Clicking on Mishi Choudhary on the [home page](https://foundation.mozilla.org/)

<img width="1140" alt="screen shot 2018-01-15 at 9 52 46 am" src="https://user-images.githubusercontent.com/1068783/34955658-543ab300-f9da-11e7-8f56-bec56a1f584c.png">

would bring a user down the [people page](https://foundation.mozilla.org/people/) to here:

<img width="1262" alt="screen shot 2018-01-15 at 9 56 25 am" src="https://user-images.githubusercontent.com/1068783/34955688-75a87658-f9da-11e7-8cc8-5bea6b52f0c7.png">

**Comment by taisdesouzalessa** [comment]
I agree with this approach. I find that those cards in the homepage invite people to click on them and making them work as expected is important. Interesting to know that this was a specific ask from fellows for previous sites. Also, during the Lean Research at MozFest  I observed the frustration of an user when they tried to click on them. 
It would be nice if the whole block was clickable.

**Comment by sabrinang** [comment]
+1 This would be a great feature for upcoming fellows directory. Yeah, this would be a useful pattern/feature which leads me to think about where else we would link back to these anchors on the network site and about the potential overlap with pulse since it has more built out profiles than these members spotlight cards. 

For example:
Names on our site like Corinna could anchor to her member spotlight
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/2492510/34957505-bffde442-f9e2-11e7-9593-bf6382157dec.png">

Pulse version links to their profile
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/2492510/34957522-cd0958a6-f9e2-11e7-9b88-29964f8b6706.png">

This was a bit of a tangent on the system to consider but if we add anchors to their spotlight card, do we need to consider a way for people to copy that link to be shared UI wise? or it just used to connect the two pieces though.

**Comment by xmatthewx** [comment]
@kristinashu you can loop this into your work on People editorial stuff. 

In a nutshell, the current people page cards will serve the directory that we will pilot with the fellows pages. The people page will become editorial, story driven. 

Until we have profiles on site coming from pulse, we shouldn't engineer these links. But we should definitely look to make these connections in the design.
