### ISSUE TITLE
[PNI] Category nav pushes search bar off screen during load

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/foundation.mozilla.org#9647]
# Description

During load of the JS the categories are pushing the search bar of screen. 

https://images.zenhubusercontent.com/76596293/6b5050a6-ff9d-451f-9558-1b540c09feac/screen_recording_2022_11_09_at_06_34_36.mov

This feels visually a bit disruptive. 

When loading the page without JS, I can never reach the categories or search bar that are off screen. 

# Expected behavior

* Search bar stays where it, regardless if JS has loaded / is active or not.
* Before JS loads (of when JS is deactivated), the categories are allowed to overflow their container and non-visible categories can be reached with horizontal scrolling.
* When JS loads, the horizontally overflowing categories are moved into the "more" dropdown.

**Comment by cdanfon** [comment]
@beccaklam could you please QA this one?

**Comment by beccaklam** [comment]
Hi @fessehaye, so this is mostly working! Some QA questions:
1. I wonder if we need to add the horizontal scroll bar back so that it's more obvious that there are some menu items hidden horizontally. Otherwise it's not immediately clear there are menu items hidden. Unless there were some way to cut off a word in the middle? But perhaps the horizontal scroll bar is the most clear.
2. On tablet, the menu cuts off when there's still room for menu items to be displayed, can we increase the length of the category menu before it cuts off?
![Screenshot 2023-01-16 at 10 07 40 AM](https://user-images.githubusercontent.com/20977376/212743968-44d3c924-f312-4944-8466-d4df80f3a2b1.png)

**Comment by fessehaye** [comment]
@beccaklam addressed feedback on staging

**Comment by beccaklam** [comment]
Taking a look and checking with the other designers that they're ok with the horizontal scroll bar!

**Comment by beccaklam** [comment]
@fessehaye is there any chance there's an option where the horizontal scroll bar only shows on hover?

**Comment by fessehaye** [comment]
@beccaklam I am not sure we would want that on tablet view right?

**Comment by beccaklam** [comment]
@fessehaye Hmm, that is true. Okay, let's ship this for now!
