### ISSUE TITLE
[PNI] Finish setting up PNI dashboard

### ISSUE THREAD

**Issue by beccaklam** [mozilla/foundation.mozilla.org#9721]
Follow up ticket to #9616

Once PNI IDs have been pushed to prod, we need to check if the dashboard is connected and working properly.

**Goals**
- [x] Check [dashboard](https://datastudio.google.com/reporting/868245f5-7732-4fa3-a7f3-dd8f39f6666a/page/y8efC)
- [x] Get feedback from design
- [x] Get feedback from stakeholders
- [x] Share in pni production channel

**Comment by beccaklam** [comment]
I _think_ this is mostly set up but still waiting for more data to come in for some tables to populate. @kristinashu I think this is ready for design review though? Or you can wait until next week for more data to come in.

**Comment by kristinashu** [comment]
The dashboard is amazing and I've already been looking at it multiple times a day since the launch!

I've never actually set up a dashboard myself before so a few questions:

1) Bounce rate decrease is in red but isn't it a good thing? Is it possible to change the color? 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/1068783/203659604-5779a404-e2e4-4c24-a9ff-022283317fc2.png">

2) I'm curious if the bounce rate for the homepage has changed since the updates, is it possible to show that?

3) Is it possible to change the order of these? 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/1068783/203659849-af82ca39-0976-479e-91b1-fc744e8963a2.png">

**Comment by beccaklam** [comment]
@kristinashu Do you mean the PNI homepage? I'll need to look into this further but it may be difficult since the category pages are filtered variations of the homepage? But maybe we can try to exclude those variations.

**Comment by kristinashu** [comment]
Yes, I mean the PNI homepage. I can see the time spend on that page and I can see the exit pages but not the bounce rate.

**Comment by beccaklam** [comment]
I looked into this yesterday but I'm not sure we can isolate for the homepage, would need some help probably from Tyler to solve this. Is it ok if we move that request to another ticket? @kristinashu

**Comment by kristinashu** [comment]
Yeah, don't worry about it!

**Comment by beccaklam** [comment]
Dashboard has been shared with design, dev and stakeholders in the PNI channel!
